;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref .slot? object?)
        (only-in :clan/poo/mop define-type Type. element?)
        (only-in :std/list/list every))
(export PooFlowTemporalSourceAuthority PooFlowTemporalSourceAssertion PooFlowTemporalClockConversion
        poo-flow-temporal-source-authority? poo-flow-temporal-source-assertion?
        poo-flow-temporal-clock-conversion?)
(def (text? v) (and (string? v) (> (string-length v) 0)))
(def (base? v kind slots)
  (and (object? v) (.slot? v 'kind) (eq? (.ref v 'kind) kind)
       (every (lambda (s) (.slot? v s)) slots)))
(def (authority? v)
  (and (base? v 'temporal/source-authority '(identity issuer source key-identity admission-domain verification-key))
       (every text? (map (lambda (s) (.ref v s)) '(identity issuer source key-identity admission-domain)))
       (u8vector? (.ref v 'verification-key)) (>= (u8vector-length (.ref v 'verification-key)) 32)))
(def (assertion? v)
  (and (base? v 'temporal/source-assertion '(identity issuer source key-identity admission-domain predicate body-digest not-before expires signature))
       (every text? (map (lambda (s) (.ref v s)) '(identity issuer source key-identity admission-domain body-digest)))
       (symbol? (.ref v 'predicate))
       (exact-integer? (.ref v 'not-before)) (>= (.ref v 'not-before) 0)
       (exact-integer? (.ref v 'expires)) (> (.ref v 'expires) (.ref v 'not-before))
       (u8vector? (.ref v 'signature)) (= (u8vector-length (.ref v 'signature)) 32)))
(def (conversion? v)
  (and (base? v 'temporal/clock-conversion '(identity source source-domain target-domain numerator denominator offset radius first last semantic-digest))
       (every text? (map (lambda (s) (.ref v s)) '(identity source source-domain target-domain semantic-digest)))
       (not (equal? (.ref v 'source-domain) (.ref v 'target-domain)))
       (every (lambda (s) (and (exact-integer? (.ref v s)) (> (.ref v s) 0))) '(numerator denominator))
       (exact-integer? (.ref v 'offset))
       (every (lambda (s) (and (exact-integer? (.ref v s)) (>= (.ref v s) 0))) '(radius first last))
       (<= (.ref v 'first) (.ref v 'last))))
(define-type (PooFlowTemporalSourceAuthority @ Type.) .element?: authority?)
(define-type (PooFlowTemporalSourceAssertion @ Type.) .element?: assertion?)
(define-type (PooFlowTemporalClockConversion @ Type.) .element?: conversion?)
(def (poo-flow-temporal-source-authority? v) (element? PooFlowTemporalSourceAuthority v))
(def (poo-flow-temporal-source-assertion? v) (element? PooFlowTemporalSourceAssertion v))
(def (poo-flow-temporal-clock-conversion? v) (element? PooFlowTemporalClockConversion v))
