;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Exact bounded interval/point constraint propagation by enumerating the
;;; caller's finite domains. This is not an unbounded Allen path-consistency
;;; heuristic or a completeness claim about missing source observations.
(import (only-in :clan/poo/object .ref)
        (only-in :std/list/list every find delete-duplicates/hash)
        (only-in :std/crypto/digest sha256) (only-in :std/encoding/hex hex-encode)
        "types.ss" "funs.ss" "network-types.ss" "network-objects.ss")
(export poo-flow-temporal-time-network poo-flow-temporal-time-network-replay
        poo-flow-temporal-time-network-solve poo-flow-temporal-time-network-assessment-replay)
(def (digest v) (string-append "sha256:" (hex-encode (sha256 (string->utf8 (object->string v))))))
(def (unique? xs) (= (length xs) (length (delete-duplicates/hash xs))))
(def (sorted xs) (list-sort (lambda (a b) (string<? (.ref a 'identity) (.ref b 'identity))) xs))
(def (instant-row v) (map (lambda (s) (.ref v s)) '(identity domain-identity coordinate provenance-identity modality)))
(def (time-row v)
  (if (poo-flow-temporal-instant? v) (cons 'instant (instant-row v))
    (list 'interval (.ref v 'identity) (instant-row (.ref v 'start)) (instant-row (.ref v 'end))
          (.ref v 'start-closed?) (.ref v 'end-closed?))))
(def (poo-flow-temporal-time-network id choices constraints)
  (unless (and (list? choices) (pair? choices) (every poo-flow-temporal-time-choice? choices)
               (list? constraints) (every poo-flow-temporal-time-constraint? constraints))
    (error "invalid finite temporal constraint inventory"))
  (for-each (lambda (xs) (unless (unique? (map (lambda (v) (.ref v 'identity)) xs))
                         (error "duplicate temporal constraint identity"))) (list choices constraints))
  (for-each
   (lambda (choice) (unless (unique? (map (lambda (v) (.ref v 'identity)) (.ref choice 'alternatives)))
                     (error "duplicate temporal alternative identity"))) choices)
  (for-each
   (lambda (c)
     (let ((left (find (lambda (v) (equal? (.ref v 'identity) (.ref c 'left))) choices))
           (right (find (lambda (v) (equal? (.ref v 'identity) (.ref c 'right))) choices)))
       (unless (and left right) (error "constraint names an unknown time choice"))
       (unless (eq? (poo-flow-temporal-instant? (car (.ref left 'alternatives)))
                     (poo-flow-temporal-instant? (car (.ref right 'alternatives))))
         (error "a time constraint cannot silently compare points with interval extents"))
       (when (poo-flow-temporal-instant? (car (.ref left 'alternatives)))
         (unless (every (lambda (r) (memq r '(before equal after))) (.ref c 'relations))
           (error "point constraints require point relations"))))) constraints)
  (let* ((choices (sorted choices)) (constraints (sorted constraints))
         (row (list 'poo-flow.temporal.time-network.v1 id
                    (map (lambda (v) (list (.ref v 'identity) (map time-row (sorted (.ref v 'alternatives))))) choices)
                    (map (lambda (c) (list (.ref c 'identity) (.ref c 'left) (.ref c 'right)
                                          (list-sort (lambda (a b) (string<? (symbol->string a) (symbol->string b)))
                                                     (delete-duplicates/hash (.ref c 'relations))))) constraints))))
    (poo-flow-temporal-time-network-value id choices constraints (digest row))))
(def (poo-flow-temporal-time-network-replay network)
  (unless (poo-flow-temporal-time-network? network) (error "invalid time network"))
  (let (expected (poo-flow-temporal-time-network (.ref network 'identity) (.ref network 'choices) (.ref network 'constraints)))
    (unless (equal? (.ref expected 'semantic-digest) (.ref network 'semantic-digest))
      (error "time network digest mismatch")) expected))
(def (assignment-status constraints selection)
  (let loop ((cs constraints) (unknown? #f))
    (if (null? cs) (if unknown? 'unknown 'consistent)
      (let* ((c (car cs))
             (value (lambda (id) (.ref (find (lambda (s) (equal? id (.ref s 'identity))) selection) 'value)))
             (left (value (.ref c 'left))) (right (value (.ref c 'right)))
             (relation (if (poo-flow-temporal-instant? left) (poo-flow-temporal-compare left right)
                         (poo-flow-temporal-interval-extent-relation left right))))
        (cond ((memq relation '(unknown incomparable degenerate)) (loop (cdr cs) #t))
              ((member relation (.ref c 'relations)) (loop (cdr cs) unknown?))
              (else 'inconsistent))))))
(def (poo-flow-temporal-time-network-solve network limit node-limit: (node-limit 10000))
  (let* ((network (poo-flow-temporal-time-network-replay network)) (choices (.ref network 'choices)))
    (unless (every (lambda (n) (or (not n) (and (exact-integer? n) (> n 0)))) (list limit node-limit))
      (error "invalid temporal constraint execution budget"))
    (let loop ((frontier (list '())) (count 0) (nodes 0) (witness #f) (unknown-count 0))
      (cond
       ((or (null? frontier) (and limit (>= count limit)) (and node-limit (>= nodes node-limit)))
        (let* ((exhaustive (null? frontier))
               (status (cond (witness 'consistent-with-inventory)
                             ((or (not exhaustive) (> unknown-count 0)) 'unknown) (else 'inconsistent))))
          (poo-flow-temporal-time-network-assessment-value
           (digest (list (.ref network 'semantic-digest) limit node-limit count status))
           (.ref network 'semantic-digest) status count exhaustive witness frontier unknown-count limit node-limit)))
       ((< (length (car frontier)) (length choices))
        (let (next (list-ref choices (length (car frontier))))
          (loop (append (map (lambda (v) (cons (poo-flow-temporal-time-selection-value (.ref next 'identity) v) (car frontier)))
                             (sorted (.ref next 'alternatives))) (cdr frontier)) count (+ nodes 1) witness unknown-count)))
       (else
        (let* ((selection (reverse (car frontier))) (status (assignment-status (.ref network 'constraints) selection)))
          (loop (cdr frontier) (+ count 1) (+ nodes 1) (or witness (and (eq? status 'consistent) selection))
                (+ unknown-count (if (eq? status 'unknown) 1 0)))))))))

(def (selection-row values)
  (and values (map (lambda (v) (list (.ref v 'identity) (time-row (.ref v 'value)))) values)))
(def (poo-flow-temporal-time-network-assessment-replay assessment network)
  (let (canonical (poo-flow-temporal-time-network-solve network (.ref assessment 'world-limit)
                    node-limit: (.ref assessment 'node-limit)))
    (unless (and
             (every (lambda (slot) (equal? (.ref assessment slot) (.ref canonical slot)))
                    '(identity model-digest status explored-assignments exhausted? unknown-assignments action-authorized?))
             (equal? (selection-row (.ref assessment 'witness)) (selection-row (.ref canonical 'witness)))
             (equal? (map selection-row (.ref assessment 'frontier)) (map selection-row (.ref canonical 'frontier))))
      (error "finite time-network assessment differs from replay")) canonical))
