;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Interpret parser-owned structural events; no line parser or caller graph.
;;; Initial anchors are document IDs and IDs of selected ordinary headlines.
(import (only-in :clan/poo/object .o .ref)
        (only-in :std/list/list every delete-duplicates/hash find)
        (only-in :poo-flow/src/semantic/orgize-source-interface parse-org-rowan-events
                 org-source-headline-parser-identity)
        "types.ss" "objects.ss" "funs-projection.ss" "funs-scope.ss")
(export poo-flow-ai-agentic-context-org-anchors poo-flow-ai-agentic-context-org-anchors-replay)
(defstruct anchor-frame (kind start key-start key-end value-start value-end))
(def (nearest stack kind)
  (find (lambda (frame) (eq? (anchor-frame-kind frame) kind)) stack))
(def (slice bytes start end) (utf8->string (subu8vector bytes start end)))
(def (source-properties source)
  (let* ((bytes (string->utf8 source)) (size (u8vector-length bytes))
         (events (parse-org-rowan-events source)))
    (let ((stack '()) (offset 0) (roots 0) (properties '()))
      (for-each (lambda (event)
        (unless (pair? event) (error "Invalid Orgize structural event"))
        (case (car event)
          ((start)
           (unless (and (= (length event) 2) (symbol? (cadr event)))
             (error "Invalid Orgize node start"))
           (when (null? stack)
             (set! roots (+ roots 1))
             (unless (eq? (cadr event) 'OrgFile) (error "Org anchor requires OrgFile root")))
           (set! stack (cons (make-anchor-frame (cadr event) offset #f #f #f #f) stack)))
          ((token)
           (unless (and (= (length event) 4) (symbol? (cadr event)) (pair? stack)
                        (exact-integer? (caddr event)) (exact-integer? (cadddr event))
                        (= (caddr event) offset) (<= offset (cadddr event) size))
             (error "Org anchor tokens do not partition source"))
           (let (property (nearest stack 'OrgNodeProperty))
             (when property
               (case (cadr event)
                 ((PropertyKey) (set! (anchor-frame-key-start property) (caddr event))
                                (set! (anchor-frame-key-end property) (cadddr event)))
                 ((PropertyValue) (set! (anchor-frame-value-start property) (caddr event))
                                  (set! (anchor-frame-value-end property) (cadddr event))))))
           (set! offset (cadddr event)))
          ((finish)
           (unless (and (= (length event) 1) (pair? stack)) (error "Unbalanced Orgize tree"))
           (let (frame (car stack))
             (set! stack (cdr stack))
             (when (and (eq? (anchor-frame-kind frame) 'OrgNodeProperty)
                        (anchor-frame-key-start frame)
                        (pair? stack) (pair? (cdr stack))
                        (eq? (anchor-frame-kind (car stack)) 'OrgPropertyDrawer)
                        (memq (anchor-frame-kind (cadr stack)) '(OrgFile OrgSection))
                        (string-ci=? (slice bytes (anchor-frame-key-start frame) (anchor-frame-key-end frame)) "ID"))
               (unless (and (anchor-frame-value-start frame)
                            (< (anchor-frame-value-start frame) (anchor-frame-value-end frame)))
                 (error "Empty Org property ID"))
               (when (>= (length properties) 256) (error "Org anchor capacity exceeded"))
               (let (id-value (slice bytes (anchor-frame-value-start frame) (anchor-frame-value-end frame)))
                 (unless (<= (string-length id-value) 256) (error "Org property ID exceeds bound"))
                 (set! properties (cons (list id-value (anchor-frame-kind (cadr stack))
                      (anchor-frame-start (cadr stack)) (anchor-frame-value-start frame)
                      (anchor-frame-value-end frame)) properties))))))
          (else (error "Unknown Orgize structural event")))) events)
      (unless (and (= roots 1) (null? stack) (= offset size)) (error "Incomplete Org anchor tree"))
      (let (ids (map car properties))
        (unless (= (length ids) (length (delete-duplicates/hash ids)))
          (error "Ambiguous duplicate Org property ID")))
      (reverse properties))))
(def (poo-flow-ai-agentic-context-org-anchors source projection expected-scope ids)
  (unless (and (list? ids) (<= 1 (length ids) 32)
               (every (lambda (id) (and (string? id) (< 0 (string-length id) 257))) ids)
               (= (length ids) (length (delete-duplicates/hash ids))))
    (error "Org anchor request requires unique bounded IDs"))
  (let* ((verified (poo-flow-ai-agentic-context-org-replay source projection expected-scope))
         (scope-value (.ref verified 'scope)) (properties (source-properties source))
         (rows (.ref (.ref (.ref verified 'observation) 'result-set) 'rows))
         (starts (map (lambda (row)
                   (.ref (find (lambda (cell) (eq? (.ref cell 'field) 'byte-start)) (.ref row 'cells)) 'value)) rows)))
    (unless (string? (.ref scope-value 'session)) (error "Org Session anchor requires exact Session/Turn"))
    (map (lambda (requested-id)
      (let (property (or (assoc requested-id properties) (error "Unknown Org property ID" requested-id)))
        (unless (or (eq? (cadr property) 'OrgFile) (member (caddr property) starts))
          (error "Org anchor is outside selected headline Context" requested-id))
        (let* ((id-value (string-copy (car property))) (container-value (cadr property))
               (start-value (caddr property)) (value-start-value (list-ref property 3))
               (value-end-value (list-ref property 4)) (source-value (string-copy (.ref verified 'source-digest)))
               (projection-value (string-copy (.ref verified 'semantic-digest)))
               (scope-digest-value (string-copy (.ref scope-value 'semantic-digest)))
               (session-value (string-copy (.ref scope-value 'session))) (turn-value (.ref scope-value 'turn))
               (binding-value (poo-flow-ai-agentic-context-digest
                  (list 'org-property-anchor-v1 id-value container-value start-value value-start-value
                    value-end-value source-value org-source-headline-parser-identity projection-value
                    scope-digest-value session-value turn-value))))
          (.o (:: @ AiAgenticContextOrgAnchor.) org-id: id-value container-kind: container-value
              container-start: start-value value-start: value-start-value value-end: value-end-value
              source-digest: source-value parser-identity: org-source-headline-parser-identity
              projection-digest: projection-value scope-digest: scope-digest-value session: session-value
              turn: turn-value semantic-digest: binding-value)))) ids)))
(def (poo-flow-ai-agentic-context-org-anchors-replay source projection scope anchors)
  (unless (and (list? anchors) (every poo-flow-ai-agentic-context-org-anchor-shape? anchors))
    (error "Invalid Context Org anchor proposal"))
  (let (fresh (poo-flow-ai-agentic-context-org-anchors source projection scope
                  (map (lambda (anchor) (.ref anchor 'org-id)) anchors)))
    (unless (every (lambda (pair)
      (every (lambda (key) (equal? (.ref (car pair) key) (.ref (cdr pair) key)))
        '(kind org-id container-kind container-start value-start value-end source-digest parser-identity
          projection-digest scope-digest session turn semantic-digest source-authenticated? action-authorized?)))
      (map cons anchors fresh)) (error "Org anchor substitution")) fresh))
