;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Boundary shapes and invariants; no construction or runtime effects.
(import (only-in :clan/poo/object .ref .slot? object?)
        (only-in :clan/poo/mop Type. define-type)
        (only-in :std/list/list every))
(export AiAgenticContextOrgAnchorType poo-flow-ai-agentic-context-org-anchor-shape?
        AiAgenticContextDeltaType poo-flow-ai-agentic-context-delta-shape?
        AiAgenticContextScopeType poo-flow-ai-agentic-context-scope-shape?)
(def (name? x) (and (string? x) (< 0 (string-length x) 257)))
(def (poo-flow-ai-agentic-context-scope-shape? spec)
  (and (object? spec)
       (every (lambda (k) (and (.slot? spec k) (name? (.ref spec k))))
              '(bundle organization project worktree source-cut actor task destination))
       (.slot? spec 'kind)
       (eq? (.ref spec 'kind) 'poo-flow.ai-agentic-context.scope.v1)
       (.slot? spec 'epoch)
       (exact-integer? (.ref spec 'epoch)) (>= (.ref spec 'epoch) 0)
       (.slot? spec 'session) (.slot? spec 'turn)
       (or (and (eq? (.ref spec 'session) #f) (eq? (.ref spec 'turn) #f))
           (and (name? (.ref spec 'session))
                (exact-integer? (.ref spec 'turn)) (>= (.ref spec 'turn) 0)))))
(define-type (AiAgenticContextScopeType @ Type.)
  .element?: poo-flow-ai-agentic-context-scope-shape?)

(def (unit? value identity)
  (and (pair? value) (equal? (car value) identity) (list? (cdr value))))
(def (edit? value)
  (and (object? value)
       (every (lambda (k) (.slot? value k)) '(kind identity expected replacement))
       (eq? (.ref value 'kind) 'poo-flow.ai-agentic-context.edit.v1)
       (string? (.ref value 'identity))
       (let ((old (.ref value 'expected)) (new (.ref value 'replacement)))
         (and (or old new)
              (or (eq? old #f) (unit? old (.ref value 'identity)))
              (or (eq? new #f) (unit? new (.ref value 'identity)))))))
(def (poo-flow-ai-agentic-context-delta-shape? value)
  (and (object? value)
       (every (lambda (k) (.slot? value k)) '(kind base-digest target-digest edits order))
       (eq? (.ref value 'kind) 'poo-flow.ai-agentic-context.delta.v1)
       (string? (.ref value 'base-digest)) (string? (.ref value 'target-digest))
       (list? (.ref value 'edits)) (<= (length (.ref value 'edits)) 512)
       (every edit? (.ref value 'edits))
       (list? (.ref value 'order)) (<= (length (.ref value 'order)) 256)
       (every string? (.ref value 'order))))
(define-type (AiAgenticContextDeltaType @ Type.)
  .element?: poo-flow-ai-agentic-context-delta-shape?)

(def (poo-flow-ai-agentic-context-org-anchor-shape? value)
  (and (object? value)
       (every (lambda (key) (.slot? value key))
          '(kind org-id container-kind container-start value-start value-end source-digest parser-identity
            projection-digest scope-digest session turn semantic-digest source-authenticated? action-authorized?))
       (eq? (.ref value 'kind) 'poo-flow.ai-agentic-context.org-anchor.v1)
       (every (lambda (key) (name? (.ref value key)))
          '(org-id source-digest parser-identity projection-digest scope-digest session semantic-digest))
       (memq (.ref value 'container-kind) '(OrgFile OrgSection))
       (every (lambda (key) (and (exact-integer? (.ref value key)) (>= (.ref value key) 0)))
          '(container-start value-start value-end turn))
       (<= (.ref value 'container-start) (.ref value 'value-start))
       (< (.ref value 'value-start) (.ref value 'value-end) 1048577)
       (eq? (.ref value 'source-authenticated?) #f) (eq? (.ref value 'action-authorized?) #f)))
(define-type (AiAgenticContextOrgAnchorType @ Type.)
  .element?: poo-flow-ai-agentic-context-org-anchor-shape?)
