;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Native values; original ASCENT replay owns all derivation semantics.
(import (only-in :clan/poo/object .o .ref .slot? object?)
        (only-in :clan/poo/mop define-type Type. validate)
        (only-in :std/crypto/digest sha256) (only-in :std/encoding/hex hex-encode)
        (only-in :gerbil-ascent/candidate/types reasoning-snapshot-relations
                 reasoning-snapshot-generation reasoning-candidate-relations reasoning-candidate-rules)
        (only-in :gerbil-ascent/candidate/program candidate-inspect)
        (only-in :gerbil-ascent/candidate/reasoning reasoning-receipt-proof)
        (only-in :gerbil-ascent/candidate/provenance positive-proof-nodes
                 proof-node-id proof-node-kind proof-node-label)
        "positive-proof.ss")
(export PooFlowTemporalRuleProgram poo-flow-temporal-rule-relation
        poo-flow-temporal-rule-variable poo-flow-temporal-rule-literal
        poo-flow-temporal-rule-atom poo-flow-temporal-rule
        poo-flow-temporal-rule-program poo-flow-temporal-rule-correspondence-from-ascent
        poo-flow-temporal-rule-correspondence-replay
        poo-flow-temporal-rule-program-ascent-query)
(def (text? x) (and (string? x) (< 0 (string-length x) 257)))
(def (name? x) (and (text? x) (andmap (lambda (c) (or (char<=? #\a c #\z)
  (char<=? #\A c #\Z) (char<=? #\0 c #\9) (eqv? c #\_))) (string->list x))))
(def (tag? x k) (and (object? x) (.slot? x 'kind) (eq? (.ref x 'kind) k)))
(def (bounded? xs n) (and (list? xs) (< 0 (length xs) (+ n 1))))
(def (digest x) (string-append "sha256:" (hex-encode (sha256 (string->utf8
  (call-with-output-string (lambda (p) (write x p))))))))
(def (poo-flow-temporal-rule-relation id-value predicate-value columns-value)
  (unless (and (text? id-value) (name? predicate-value) (bounded? columns-value 32)
               (andmap (lambda (t) (memq t '(integer boolean))) columns-value))
    (error "invalid rule relation"))
  (.o kind: 'temporal.rule-relation.v1 identity: (string-copy id-value)
      predicate: (string-copy predicate-value) columns: (map (lambda (x) x) columns-value)))
(def (poo-flow-temporal-rule-variable name-value)
  (unless (name? name-value) (error "invalid rule variable"))
  (.o kind: 'temporal.rule-variable.v1 name: (string-copy name-value)))
(def (poo-flow-temporal-rule-literal value-value)
  (unless (or (boolean? value-value) (and (exact-integer? value-value)
    (<= -9223372036854775808 value-value 9223372036854775807))) (error "invalid rule literal"))
  (.o kind: 'temporal.rule-literal.v1 value: value-value))
(def (term-row t)
  (cond ((tag? t 'temporal.rule-variable.v1)
          (poo-flow-temporal-rule-variable (.ref t 'name)) (list 'variable (.ref t 'name)))
        ((tag? t 'temporal.rule-literal.v1)
          (poo-flow-temporal-rule-literal (.ref t 'value)) (list 'literal (.ref t 'value)))
        (else (error "invalid rule term"))))
(def (poo-flow-temporal-rule-atom relation-value terms-value)
  (unless (and (text? relation-value) (bounded? terms-value 32)) (error "invalid rule atom"))
  (for-each term-row terms-value)
  (.o kind: 'temporal.rule-atom.v1 relation-identity: (string-copy relation-value) terms: (map (lambda (x) x) terms-value)))
(def (atom-row a)
  (unless (tag? a 'temporal.rule-atom.v1) (error "invalid rule atom kind"))
  (poo-flow-temporal-rule-atom (.ref a 'relation-identity) (.ref a 'terms))
  (list (.ref a 'relation-identity) (map term-row (.ref a 'terms))))
(def (poo-flow-temporal-rule id-value head-value body-value)
  (unless (and (text? id-value) (bounded? body-value 32)) (error "invalid rule"))
  (atom-row head-value) (for-each atom-row body-value)
  (.o kind: 'temporal.rule.v1 identity: (string-copy id-value) head: head-value body: (map (lambda (x) x) body-value)))
(def (rule-row r)
  (unless (tag? r 'temporal.rule.v1) (error "invalid rule kind"))
  (poo-flow-temporal-rule (.ref r 'identity) (.ref r 'head) (.ref r 'body))
  (list (.ref r 'identity) (atom-row (.ref r 'head)) (map atom-row (.ref r 'body))))
(def (relation-row r)
  (unless (tag? r 'temporal.rule-relation.v1) (error "invalid rule relation kind"))
  (poo-flow-temporal-rule-relation (.ref r 'identity) (.ref r 'predicate) (.ref r 'columns))
  (list (.ref r 'identity) (.ref r 'predicate) (.ref r 'columns)))
(def (unique! xs) (let (seen (make-hash-table)) (for-each (lambda (x)
  (when (hash-get seen x) (error "duplicate rule correspondence")) (hash-put! seen x #t)) xs)))
(def (atom-clause a relations variables head?)
  (let* ((r (find (lambda (r) (equal? (.ref r 'identity) (.ref a 'relation-identity))) relations))
         (ts (.ref a 'terms)))
    (unless (and r (= (length ts) (length (.ref r 'columns)))) (error "missing relation or rule arity mismatch"))
    (cons (string->symbol (.ref r 'predicate))
      (map (lambda (t type)
        (if (tag? t 'temporal.rule-variable.v1)
          (let* ((n (.ref t 'name)) (old (hash-get variables n)))
            (when (or (and head? (not old)) (and old (not (eq? old type)))) (error "unbound or inconsistent rule variable"))
            (hash-put! variables n type) (string->symbol (string-append "?" n)))
          (let (v (.ref t 'value))
            (unless (if (eq? type 'boolean) (boolean? v) (exact-integer? v)) (error "rule literal column mismatch")) v)))
        ts (.ref r 'columns)))))
(def (rule-clause r relations)
  (let* ((variables (make-hash-table))
         (body-value (map (lambda (a) (atom-clause a relations variables #f)) (.ref r 'body)))
         (head-value (atom-clause (.ref r 'head) relations variables #t)))
    (cons head-value body-value)))
(define-type (PooFlowTemporalRuleProgram @ Type.)
  .element?: (lambda (v) (tag? v 'temporal.rule-program.v1)))
(def (poo-flow-temporal-rule-program id-value catalog-value generation-value ascent-value relations-value rules-value)
  (unless (and (text? id-value) (text? catalog-value) (text? generation-value)
    (exact-integer? ascent-value) (<= 0 ascent-value) (bounded? relations-value 32) (bounded? rules-value 32))
    (error "invalid rule program"))
  (let* ((relation-data (map relation-row relations-value)) (rule-data (map rule-row rules-value)))
    (unique! (map car relation-data)) (unique! (map cadr relation-data)) (unique! (map car rule-data))
    (for-each (lambda (r) (rule-clause r relations-value)) rules-value)
    (validate PooFlowTemporalRuleProgram (.o kind: 'temporal.rule-program.v1 identity: id-value
      catalog-digest: catalog-value generation: generation-value ascent-generation: ascent-value
      relations: relations-value rules: rules-value semantic-digest:
      (digest (list 'temporal.rule-program.v1 id-value catalog-value generation-value ascent-value relation-data rule-data))))))
(def (poo-flow-temporal-rule-correspondence-from-ascent program admission snapshot candidate receipt steps nodes)
  (unless (tag? program 'temporal.rule-program.v1) (error "invalid rule program kind"))
  (let* ((canonical (poo-flow-temporal-rule-program (.ref program 'identity) (.ref program 'catalog-digest)
                   (.ref program 'generation) (.ref program 'ascent-generation) (.ref program 'relations) (.ref program 'rules)))
         (verified (poo-flow-temporal-positive-proof-replay admission snapshot candidate receipt steps nodes))
         (spec (candidate-inspect snapshot candidate))
         (relations-value (.ref canonical 'relations)) (rules-value (.ref canonical 'rules))
         (original-rules (reasoning-candidate-rules spec)))
    (unless (and (equal? (.ref canonical 'semantic-digest) (.ref program 'semantic-digest))
                 (= (.ref canonical 'ascent-generation) (reasoning-snapshot-generation snapshot))
                 (= (length original-rules) (length rules-value))) (error "stale rule program or generation"))
    (let (inventory (append (map (lambda (r) (cons (car r) (cadr r))) (reasoning-snapshot-relations snapshot))
                           (reasoning-candidate-relations spec)))
      (unless (and (= (length inventory) (length relations-value))
        (andmap (lambda (r) (equal? (assq (string->symbol (.ref r 'predicate)) inventory)
          (cons (string->symbol (.ref r 'predicate)) (length (.ref r 'columns))))) relations-value))
        (error "rule catalog inventory mismatch")))
    (for-each (lambda (r)
      (let (declared (find (lambda (d) (eq? (string->symbol (.ref d 'predicate)) (car r))) relations-value))
        (unless (andmap (lambda (row) (andmap (lambda (v type)
          (if (eq? type 'boolean) (boolean? v) (and (exact-integer? v) (<= -9223372036854775808 v 9223372036854775807))))
          row (.ref declared 'columns))) (caddr r)) (error "source row type mismatch")))) (reasoning-snapshot-relations snapshot))
    (for-each (lambda (r original)
      (unless (equal? (rule-clause r relations-value) (cons (vector-ref original 0) (vector-ref original 1)))
        (error "original rule content does not match evaluator rule"))) rules-value original-rules)
    (let* ((applications-value (map (lambda (node)
            (let loop ((rs rules-value) (os original-rules))
              (cond ((null? rs) (error "proof rule label missing"))
                    ((equal? (proof-node-label node) (vector-ref (car os) 2)) (list (proof-node-id node) (.ref (car rs) 'identity)))
                    (else (loop (cdr rs) (cdr os))))))
          (filter (lambda (n) (eq? (proof-node-kind n) 'rule)) (positive-proof-nodes (reasoning-receipt-proof receipt)))))
           (program-digest-value (.ref canonical 'semantic-digest))
           (proof-digest-value (.ref verified 'semantic-digest)))
      (.o kind: 'temporal.rule-correspondence.v1 program-digest: program-digest-value
          proof-digest: proof-digest-value generation: (.ref canonical 'generation)
          applications: applications-value semantic-digest: (digest (list 'temporal.rule-correspondence.v1 program-digest-value proof-digest-value applications-value))
          rule-correspondence-verified?: #t source-authenticated?: #f selection-admitted?: #f action-authorized?: #f durable?: #f))))
(def (poo-flow-temporal-rule-correspondence-replay held program admission snapshot candidate receipt steps nodes)
  (unless (tag? held 'temporal.rule-correspondence.v1) (error "invalid rule correspondence kind"))
  (let (canonical (poo-flow-temporal-rule-correspondence-from-ascent program admission snapshot candidate receipt steps nodes))
    (unless (andmap (lambda (s) (and (.slot? held s) (equal? (.ref held s) (.ref canonical s))))
      '(program-digest proof-digest generation applications semantic-digest rule-correspondence-verified?
        source-authenticated? selection-admitted? action-authorized? durable?))
      (error "rule correspondence replay mismatch")) canonical))

;;; Named owner handoff: native POO program/output to original ASCENT candidate.
;;; This bounded projection is for trusted adapters, not a general user DSL.
(def (poo-flow-temporal-rule-program-ascent-query program snapshot output)
  (let* ((canonical (poo-flow-temporal-rule-program (.ref program 'identity) (.ref program 'catalog-digest)
                     (.ref program 'generation) (.ref program 'ascent-generation)
                     (.ref program 'relations) (.ref program 'rules)))
         (source-names (map car (reasoning-snapshot-relations snapshot)))
         (relations (.ref canonical 'relations)))
    (unless (and (equal? (.ref canonical 'semantic-digest) (.ref program 'semantic-digest))
                 (equal? (.ref output 'generation) (.ref canonical 'generation)))
      (error "stale query projection"))
    (append '(candidate)
      (map (lambda (r) (list 'relation (string->symbol (.ref r 'predicate)) (length (.ref r 'columns))))
           (filter (lambda (r) (not (memq (string->symbol (.ref r 'predicate)) source-names))) relations))
      (map (lambda (r) (cons 'rule (rule-clause r relations))) (.ref canonical 'rules))
      (list (cons 'query (cons (string->symbol (.ref output 'evaluator-relation)) (.ref output 'row)))
            '(limits 128 128 128)))))
