# SPDX-FileCopyrightText: 2026 tao3k team and Contributors
# SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
from pathlib import Path
from cffi import FFI
ffibuilder = FFI()
ffibuilder.cdef('typedef struct poo_flow_temporal_store poo_flow_temporal_store;\n/* Borrowed input: a projection of a freshly replayed native POO admission.\n * Host control code supplies this; never expose raw basis/grant APIs as tools.\n * Names are bounded UTF-8 C strings (128 bytes), digests canonical sha256 IDs. */\ntypedef struct {\n  char admission[129], source[129], source_digest[129];\n  char subject[129], scope[129], policy[129], revision[129], proof[129];\n  uint64_t generation;\n} poo_flow_temporal_basis;\ntypedef struct {\n  char store_identity[65], key[129], request_digest[129];\n  char admission[129], subject[129], scope[129], policy[129];\n  char revision[129], proof[129], source_digest[129], authority[129];\n  uint64_t previous_version, version, authorization_fence, source_generation;\n} poo_flow_temporal_commit_receipt;\n/* 0 success, 1 invalid input, 2 pointer conflict, 3 authorization denied,\n * 4 stale source, 5 idempotency mismatch, 6 storage error, 7 not found.\n * Transactions serialize across handles/processes. Receipts are immutable.\n * Registry, grant and commit calls are host controls, not semantic byte ops.\n * First-root profile: only version 0 / empty predecessor may select a root.\n * Grant authorizes local pointer selection only, never an external effect. */\nint32_t poo_flow_temporal_store_open(const char *path, poo_flow_temporal_store **out);\nvoid poo_flow_temporal_store_close(poo_flow_temporal_store *store);\nint32_t poo_flow_temporal_store_source(poo_flow_temporal_store *store,\n    const char *source, const char *digest, uint64_t generation);\nint32_t poo_flow_temporal_store_authorize(poo_flow_temporal_store *store,\n    const char *subject, const char *scope, const char *policy,\n    const char *authority, uint64_t fence, int32_t enabled);\nint32_t poo_flow_temporal_store_pointer(poo_flow_temporal_store *store,\n    const char *subject, const char *scope, uint64_t *version, char selected[129]);\nint32_t poo_flow_temporal_store_receipt(poo_flow_temporal_store *store,\n    const char *key, poo_flow_temporal_commit_receipt *out);\nint32_t poo_flow_temporal_store_commit(poo_flow_temporal_store *store,\n    const poo_flow_temporal_basis *basis, const char *key, const char *request_digest,\n    uint64_t expected_version, const char *expected_revision, uint64_t fence,\n    poo_flow_temporal_commit_receipt *out);\n')
runtime_c = Path(__file__).resolve().parent.parents[4] / 'bindings' / 'runtime-c'
ffibuilder.set_source('poo_flow_runtime._native._temporal_store',
    (runtime_c / 'src' / 'temporal_store.c').read_text(),
    include_dirs=[str(runtime_c / 'include')], libraries=['sqlite3', 'pthread'])
