;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Pure request construction. No provider execution or raw rule DSL on this API.
(import (only-in :clan/poo/object .ref)
 (only-in :std/crypto/digest sha256) (only-in :std/encoding/hex hex-encode)
 (only-in :std/list/list find every delete-duplicates/hash)
 (only-in :poo-flow/modules/temporal-causality/objects poo-flow-temporal-query)
 (only-in :poo-flow/modules/temporal-causality/types poo-flow-temporal-query?)
 (only-in :poo-flow/modules/temporal-causality/funs poo-flow-temporal-model-replay)
 (only-in :poo-flow/modules/temporal-causality/candidates/types poo-flow-candidate-scope?)
 (only-in :poo-flow/modules/temporal-causality/candidates/funs poo-flow-candidate-scope)
 "types.ss" "objects.ss")
(export poo-flow-ascent-source-binding poo-flow-ascent-candidate-request poo-flow-ascent-candidate-request-replay)
(def +pin+ "74f0046bb6137b4fce22db5ae398b9812734c137")
(def (digest v) (string-append "sha256:" (hex-encode (sha256 (string->utf8 (object->string v))))))
(def (text? v) (and (string? v) (> (string-length v) 0)))
(def (query-replay query)
 (unless (poo-flow-temporal-query? query) (error "invalid Temporal candidate query"))
 (poo-flow-temporal-query (.ref query 'identity) (.ref query 'hypothesis-identity) (.ref query 'exploration-limit)))
(def (target model query)
 (unless (poo-flow-temporal-query? query) (error "invalid Temporal candidate query"))
 (or (find (lambda (h) (equal? (.ref h 'identity) (.ref query 'hypothesis-identity))) (.ref model 'hypotheses))
     (error "ASCENT candidate target is absent")))
(def (poo-flow-ascent-source-binding model query cut generation)
 (let* ((model (poo-flow-temporal-model-replay model)) (query (query-replay query)) (h (target model query)))
  (unless (and (text? cut) (exact-integer? generation) (>= generation 0)) (error "invalid ASCENT source binding"))
  (digest (list 'poo-flow.ascent-observed-precedence.v1 +pin+ (.ref model 'semantic-digest)
                (.ref query 'identity) (.ref query 'hypothesis-identity) (.ref query 'exploration-limit)
                (.ref h 'cause-observation-id) (.ref h 'effect-observation-id) cut generation))))
(def (poo-flow-ascent-candidate-request id scope model query
       iterations: (iterations 64) derived-limit: (derived 4096) output-limit: (output 4096)
       proof-work: (work 100000) proof-nodes: (nodes 8192))
 (request-value id scope model query iterations derived output work nodes))
;;; Replay calls the positional kernel directly; keyword syntax is public only.
(def (request-value id scope model query iterations derived output work nodes)
 (unless (and (text? id) (poo-flow-candidate-scope? scope)
              (every (lambda (n) (and (exact-integer? n) (> n 0))) (list iterations derived output work nodes)))
   (error "invalid ASCENT candidate request"))
 (let* ((canonical-scope (poo-flow-candidate-scope (.ref scope 'identity) (.ref scope 'evidence-cut-digest)
              (.ref scope 'generation) (.ref scope 'source-coverage-digest) (.ref scope 'required-providers)))
        (model (poo-flow-temporal-model-replay model)) (query (query-replay query)) (h (target model query))
        (sources (delete-duplicates/hash (map (lambda (o) (.ref o 'provenance-identity)) (.ref model 'observations)))))
  (unless (and (equal? (.ref canonical-scope 'semantic-digest) (.ref scope 'semantic-digest))
               (memq 'ascent (.ref scope 'required-providers)) (= (length sources) 1)
               (<= (length (.ref model 'observations)) 1024) (<= (length (.ref model 'hypotheses)) 1024)
               (<= iterations 1024) (<= derived 4096) (<= output 4096) (<= work 1000000) (<= nodes 16384))
    (error "ASCENT precedence profile needs a current scope and one bounded declared source"))
  (let* ((binding (poo-flow-ascent-source-binding model query (.ref scope 'evidence-cut-digest) (.ref scope 'generation)))
         (digest (digest (list 'poo-flow.ascent-request.v1 id (.ref scope 'semantic-digest) binding
                               iterations derived output work nodes))))
   (poo-flow-ascent-request-value id digest 'ascent-observed-precedence-v1 +pin+ canonical-scope model query
                                 (car sources) binding iterations derived output work nodes))))
(def (poo-flow-ascent-candidate-request-replay request)
 (unless (poo-flow-ascent-candidate-request? request) (error "invalid ASCENT request object"))
 (let (r (request-value (.ref request 'identity) (.ref request 'scope) (.ref request 'model) (.ref request 'query)
          (.ref request 'iterations) (.ref request 'derived-limit) (.ref request 'output-limit)
          (.ref request 'proof-work) (.ref request 'proof-nodes)))
  (unless (every (lambda (s) (equal? (.ref r s) (.ref request s)))
                   '(semantic-digest profile provider-pin source-identity binding-digest))
    (error "ASCENT request differs from canonical replay")) r))
