;;; -*- Gerbil -*-
;;; Package build implementation used by the thin build.ss entrypoints.

(import :clan/building
        (only-in :gslph/src/build-api/package-receipt
                 gslph-package-build-receipt-status
                 gslph-package-build-receipt-status-ref
                 gslph-package-build-receipt-write)
        (only-in :gerbil/gambit
                 current-directory
                 file-exists?
                 getenv
                 path-expand
                 string=?
                 string-append
                 ##cpu-count)
        (only-in :gerbil/compiler/base
                 __available-cores)
        (only-in :std/make
                 make
                 make-clean)
        (only-in :std/misc/process
                 run-process))

(export #t)

(def (nono-c-binding-include-option)
  (string-append "-I" (path-expand "bindings/nono-c")))

(def +poo-flow-runtime-include-dirs+
  '("src"))

(def +poo-flow-special-source-files+
  '("src/modules/nono-sandbox/_nono.ss"
    "src/cli-support/support.ss"
    "src/cli-support/testing-project.ss"
    "src/cli-support/package-build.ss"
    "src/cli.ss"
    "main.ss"
    "manifest.ss"))

(def +poo-flow-ffi-build-spec+
  `((gsc: "src/modules/nono-sandbox/_nono"
          "-cc-options" ,(nono-c-binding-include-option))
    (ssi: "src/modules/nono-sandbox/_nono")))

(def +poo-flow-cli-library-build-spec+
  '((gxc: "src/cli-support/support.ss")
    (gxc: "src/cli-support/testing-project.ss")
    (gxc: "src/cli-support/package-build.ss")
    (gxc: "src/cli.ss")))

(def +poo-flow-cli-entry-module-build-spec+
  '((gxc: "user-interface/init")
    (gxc: "user-interface/custom/my-module/config")))

(def (poo-flow-cli-entry-build-spec _options)
  +poo-flow-cli-entry-module-build-spec+)

(def (poo-flow-entry-build-spec options)
  (poo-flow-cli-entry-build-spec options))

(def (poo-flow-cli-only-build-spec _options)
  +poo-flow-cli-library-build-spec+)

(def (poo-flow-cli-only-module-build-spec _options)
  +poo-flow-cli-library-build-spec+)

(def (poo-flow-cli-bin-dir)
  (path-expand "bin" (getenv "GERBIL_PATH")))

(def (poo-flow-cli-launcher-path)
  (path-expand "poo-flow" (poo-flow-cli-bin-dir)))

(def (poo-flow-cli-launcher-scheme-path)
  (path-expand "poo-flow-launcher.ss" (poo-flow-cli-bin-dir)))

(def (poo-flow-delete-file-if-exists! path)
  (when (file-exists? path)
    (delete-file path)))

(def (poo-flow-ensure-cli-bin-dir!)
  (unless (file-exists? (poo-flow-cli-bin-dir))
    (create-directory (poo-flow-cli-bin-dir))))

(def (poo-flow-write-cli-launcher-scheme port)
  (display "#!/usr/bin/env gxi\n" port)
  (display ";;; Generated by poo-flow package build; do not edit.\n" port)
  (display "(import :gerbil/gambit :poo-flow/src/cli)\n" port)
  (display "(poo-flow-cli-main (poo-flow-cli-script-args (command-line)))\n" port))

(def (poo-flow-write-cli-launcher-shell port)
  (display "#!/bin/sh\n" port)
  (display "# Generated by poo-flow package build; do not edit.\n" port)
  (display "set -eu\n" port)
  (display "bin_dir=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n" port)
  (display "gerbil_path=$(dirname -- \"$bin_dir\")\n" port)
  (display "case \"${GERBIL_PATH:-}\" in\n" port)
  (display "  \"\") export GERBIL_PATH=\"$gerbil_path\" ;;\n" port)
  (display "  *\"$gerbil_path\"*) ;;\n" port)
  (display "  *) export GERBIL_PATH=\"$gerbil_path:$GERBIL_PATH\" ;;\n" port)
  (display "esac\n" port)
  (display "exec gxi \"$bin_dir/poo-flow-launcher.ss\" \"$@\"\n" port))

(def (poo-flow-write-generated-file! path writer)
  (poo-flow-delete-file-if-exists! path)
  (call-with-output-file path writer))

(def (poo-flow-write-cli-launcher!)
  (poo-flow-package-require-gxpkg-env!)
  (poo-flow-ensure-cli-bin-dir!)
  (poo-flow-write-generated-file!
   (poo-flow-cli-launcher-scheme-path)
   poo-flow-write-cli-launcher-scheme)
  (poo-flow-write-generated-file!
   (poo-flow-cli-launcher-path)
   poo-flow-write-cli-launcher-shell)
  (run-process ["chmod" "755"
                (poo-flow-cli-launcher-scheme-path)
                (poo-flow-cli-launcher-path)]
               stdout-redirection: #f
               stderr-redirection: #f))

(def (poo-flow-with-directory directory thunk)
  (let (previous (current-directory))
    (dynamic-wind
      (lambda () (current-directory directory))
      thunk
      (lambda () (current-directory previous)))))

(def (poo-flow-root-module-path? path)
  (let loop ((index 0))
    (cond
     ((= index (string-length path)) #t)
     ((char=? (string-ref path index) #\/) #f)
     (else (loop (+ index 1))))))

(def (poo-flow-module-files dir exclude-dirs root-only?)
  (poo-flow-with-directory dir
    (lambda ()
      (let (modules (all-gerbil-modules exclude-dirs: exclude-dirs))
        (map (lambda (path) (string-append dir "/" path))
             (if root-only?
               (filter poo-flow-root-module-path? modules)
               modules))))))

(def (poo-flow-package-modules dirs exclude-dirs root-only?)
  (apply append
         (map (lambda (dir)
                (poo-flow-module-files dir exclude-dirs root-only?))
              dirs)))

(def (poo-flow-runtime-modules)
  (filter (lambda (file)
            (not (member file +poo-flow-special-source-files+)))
          (poo-flow-package-modules +poo-flow-runtime-include-dirs+ '() #f)))

(def (poo-flow-gxc-target file _options)
  [gxc: file])

(def (poo-flow-gxc-spec files options)
  (map (lambda (file) (poo-flow-gxc-target file options)) files))

(def (poo-flow-runtime-build-spec options)
  (poo-flow-gxc-spec (poo-flow-runtime-modules) options))

(def (poo-flow-package-build-spec options)
  (if (poo-flow-native-build-options? options)
    (append +poo-flow-ffi-build-spec+
            (poo-flow-runtime-build-spec options)
            (poo-flow-entry-build-spec options))
    (append (poo-flow-runtime-build-spec options)
            +poo-flow-cli-library-build-spec+
            (poo-flow-entry-build-spec options))))

(def (spec)
  (poo-flow-package-build-spec []))

(def (poo-flow-package-srcdir)
  (path-expand "."))

(def (poo-flow-package-require-gxpkg-env!)
  (unless (getenv "GERBIL_PATH" #f)
    (error "poo-flow package builds require gxpkg env; run gxpkg env gxi build.ss compile")))

(def (poo-flow-package-cores-from-env name)
  (let (value (getenv name #f))
    (and value
         (let (cores (string->number value))
           (and (integer? cores)
                (> cores 0)
                cores)))))

(def (poo-flow-package-worker-count)
  (or (poo-flow-package-cores-from-env "GERBIL_BUILD_CORES")
      (max 1 (##cpu-count))))

(def (poo-flow-package-parallelize)
  (let (worker-count (poo-flow-package-worker-count))
    (set! __available-cores worker-count)
    worker-count))

(def (poo-flow-make-options options)
  (match options
    ([build-cli: _ . rest]
     (poo-flow-make-options rest))
    ([force: _ . rest]
     (poo-flow-make-options rest))
    ([key value . rest]
     (cons key
           (cons value
                 (poo-flow-make-options rest))))
    ([] [])))

(def (poo-flow-package-options options)
  (let (parallelize (poo-flow-package-parallelize))
    (if parallelize
      (append (poo-flow-make-options options) [parallelize: parallelize])
      (poo-flow-make-options options))))

(def (poo-flow-package-stage-options stage options)
  (if (> (length stage) 1)
    (poo-flow-package-options options)
    (poo-flow-make-options options)))

(def (poo-flow-package-message action label stage)
  (display "... poo-flow ")
  (display action)
  (display " ")
  (display label)
  (display " targets=")
  (display (length stage))
  (let (parallelize (and (> (length stage) 1)
                         (poo-flow-package-worker-count)))
    (when parallelize
      (display " parallelize=")
      (display parallelize)))
  (newline)
  (force-output))

(def (poo-flow-all? pred xs)
  (match xs
    ([] #t)
    ([x . rest]
     (and (pred x) (poo-flow-all? pred rest)))))

(def (poo-flow-package-libdir)
  (path-expand "lib" (getenv "GERBIL_PATH")))

(def (poo-flow-package-libdir-prefix)
  (path-expand "poo-flow" (poo-flow-package-libdir)))

(def (poo-flow-stage-cache-stamp-path options)
  (path-expand
   (cond
    ((poo-flow-cli-build-options? options) ".compile-cli.stamp")
    (else ".compile-package.stamp"))
   (poo-flow-package-libdir-prefix)))

(def (poo-flow-diagnostic-source-path spec)
  (match spec
    ([gxc: file . _] (path-expand file (poo-flow-package-srcdir)))
    (_ #f)))

(def (poo-flow-stage-source-files stage)
  (let lp ((rest stage) (sources []))
    (match rest
      ([] (append (reverse sources)
                  (map (lambda (file)
                         (path-expand file (poo-flow-package-srcdir)))
                       '("build.ss" "gerbil.pkg"))))
      ([spec . rest]
       (let (source (poo-flow-diagnostic-source-path spec))
         (if source
           (lp rest (cons source sources))
           (lp rest sources)))))))

(def (poo-flow-diagnostic-gxc-spec? spec)
  (match spec
    ([gxc: . _] #t)
    (_ #f)))

(def (poo-flow-diagnostic-gxc-outputs file)
  [(path-expand (string-append file "i")
                (poo-flow-package-libdir-prefix))])

(def (poo-flow-diagnostic-outputs spec)
  (match spec
    ([gxc: file . _] (poo-flow-diagnostic-gxc-outputs file))
    (_ [])))

(def (poo-flow-stage-cacheable? stage options)
  (and (not (poo-flow-native-build-options? options))
       (poo-flow-all? poo-flow-diagnostic-gxc-spec? stage)))

(def (poo-flow-stage-cache-valid? stage options)
  (and (not (poo-flow-force-build-options? options))
       (poo-flow-stage-cacheable? stage options)
       (let* ((stamp (poo-flow-stage-cache-stamp-path options))
              (sources (poo-flow-stage-source-files stage))
              (outputs (apply append (map poo-flow-diagnostic-outputs stage)))
              (status (gslph-package-build-receipt-status
                       stamp
                       expected-sources: sources
                       expected-outputs: outputs)))
         (eq? (gslph-package-build-receipt-status-ref status 'status 'stale)
              'current))))

(def (poo-flow-stage-cache-touch! stage options)
  (when (poo-flow-stage-cacheable? stage options)
    (gslph-package-build-receipt-write
     (poo-flow-stage-cache-stamp-path options)
     (poo-flow-stage-source-files stage)
     (apply append (map poo-flow-diagnostic-outputs stage)))))

(def (poo-flow-make label stage options)
  (poo-flow-package-require-gxpkg-env!)
  (poo-flow-package-message "check" label stage)
  (if (poo-flow-stage-cache-valid? stage options)
    (begin
      (poo-flow-package-message "skip" label stage)
      (display "|note kind=build-cache message=\"package-local gxc direct outputs are current; skipped std/make no-op rebuild\"")
      (newline))
    (begin
      (poo-flow-package-message "compile" label stage)
      (apply make stage
             srcdir: (poo-flow-package-srcdir)
             (poo-flow-package-stage-options stage options))
      (poo-flow-stage-cache-touch! stage options))))

(def (poo-flow-make-clean label stage)
  (poo-flow-package-require-gxpkg-env!)
  (poo-flow-package-message "clean" label stage)
  (apply make-clean stage
         srcdir: (poo-flow-package-srcdir)
         (poo-flow-package-stage-options stage [])))

(def (poo-flow-gxc-spec-file spec)
  (match spec
    ([gxc: file . _] file)
    (_ (error "poo-flow direct gxc stage only supports gxc specs" spec))))

(def (poo-flow-gxc-source-file file)
  (cond
   ((file-exists? file) file)
   ((file-exists? (string-append file ".ss"))
    (string-append file ".ss"))
   (else file)))

(def (poo-flow-run-gxc-spec! spec)
  (let* ((file (poo-flow-gxc-spec-file spec))
         (source (poo-flow-gxc-source-file file)))
    (display "|gxc file=")
    (write source)
    (newline)
    (run-process ["gxc" source]
                 stdin-redirection: #f
                 stdout-redirection: #f
                 stderr-redirection: #f)))

(def (poo-flow-gxc-stage label stage options)
  (poo-flow-package-require-gxpkg-env!)
  (poo-flow-package-message "check" label stage)
  (if (poo-flow-stage-cache-valid? stage options)
    (begin
      (poo-flow-package-message "skip" label stage)
      (display "|note kind=build-cache message=\"package-local direct gxc outputs are current; skipped focused cli rebuild\"")
      (newline))
    (begin
      (poo-flow-package-message "compile" label stage)
      (for-each poo-flow-run-gxc-spec! stage)
      (poo-flow-stage-cache-touch! stage options))))

(def (poo-flow-entry-options release optimized debug cli force verbose)
  (append
   (if release [build-release: #t] [])
   (if optimized [build-optimized: #t] [])
   (if debug [debug: #t] [])
   (if cli [build-cli: #t] [])
   (if force [force: #t] [])
   (if verbose [verbose: 9] [])))

(def (poo-flow-release-build-options? options)
  (match options
    ([build-release: value . _] value)
    ([_ _ . rest] (poo-flow-release-build-options? rest))
    ([] #f)))

(def (poo-flow-optimized-build-options? options)
  (match options
    ([build-optimized: value . _] value)
    ([_ _ . rest] (poo-flow-optimized-build-options? rest))
    ([] #f)))

(def (poo-flow-debug-build-options? options)
  (match options
    ([debug: value . _] value)
    ([_ _ . rest] (poo-flow-debug-build-options? rest))
    ([] #f)))

(def (poo-flow-cli-build-options? options)
  (match options
    ([build-cli: value . _] value)
    ([_ _ . rest] (poo-flow-cli-build-options? rest))
    ([] #f)))

(def (poo-flow-force-build-options? options)
  (match options
    ([force: value . _] value)
    ([_ _ . rest] (poo-flow-force-build-options? rest))
    ([] #f)))

(def (poo-flow-native-build-options? options)
  (or (poo-flow-release-build-options? options)
      (poo-flow-optimized-build-options? options)
      (poo-flow-debug-build-options? options)))

(def (poo-flow-compile-build-spec options)
  (cond
   ((poo-flow-cli-build-options? options)
    (poo-flow-cli-only-build-spec options))
   ((poo-flow-release-build-options? options)
    (poo-flow-package-build-spec options))
   (else
    (poo-flow-package-build-spec options))))

(def (poo-flow-package-compile options)
  (if (poo-flow-cli-build-options? options)
    (begin
      (poo-flow-gxc-stage "cli-modules"
                          (poo-flow-cli-only-module-build-spec options)
                          options)
      (poo-flow-write-cli-launcher!))
    (begin
      (poo-flow-make "package" (poo-flow-compile-build-spec options) options)
      (poo-flow-write-cli-launcher!))))

(def (poo-flow-clean)
  (poo-flow-make-clean "package" (poo-flow-package-build-spec [])))
