;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Public API is POO values; JSON is the private runtime transport only.
(import (only-in :clan/poo/object .ref) (only-in :std/list/list every find delete-duplicates/hash)
        (only-in :std/encoding/json write-json string->json JSONReadOptions current-json-read-options)
        (only-in :std/misc/process run-process) (only-in :std/string/misc string-trim-eol)
        (only-in :std/os/signal kill SIGKILL)
        (only-in :gerbil-parser/src/runtime/artifact sha256-text)
        "bundle-types.ss" "bundle-objects.ss"
        (only-in "funs.ss" poo-flow-tla-parse-source poo-flow-tla-model-outline))
(export poo-flow-tla-source-file poo-flow-tla-toolchain poo-flow-tla-bundle
        poo-flow-tla-bundle-replay poo-flow-tla-check-bundle! poo-flow-tla-checked-bundle-replay)
(def (identifier? text)
  (and (string? text) (> (string-length text) 0) (char-alphabetic? (string-ref text 0))
       (every (lambda (c) (or (char-alphabetic? c) (char-numeric? c) (eqv? c #\_))) (string->list text))
       (every (lambda (c) (< (char->integer c) 128)) (string->list text))))
(def (framed-sha values)
  (sha256-text (call-with-output-string
                (lambda (p) (for-each (lambda (s) (display (u8vector-length (string->utf8 s)) p)
                                               (display ":" p) (display s p) (display "," p)) values)))))
(def (sorted-by values slot) (list-sort (lambda (a b) (string<? (.ref a slot) (.ref b slot))) values))
(def (unique? values) (= (length values) (length (delete-duplicates/hash values))))
(def (source-row f) (list (.ref f 'identity) (.ref f 'semantic-digest)))
(def (tool-row f) (list (.ref f 'path) (.ref f 'semantic-digest)))
(def (poo-flow-tla-source-file name text)
  (unless (and (string? name) (string? text) (> (string-length name) 4)
               (member (substring name (- (string-length name) 4) (string-length name)) '(".tla" ".cfg"))
               (identifier? (substring name 0 (- (string-length name) 4))))
    (error "source bundle permits flat TLA module/config filenames"))
  (let* ((tla? (equal? (substring name (- (string-length name) 4) (string-length name)) ".tla"))
         (document (and tla? (poo-flow-tla-parse-source text))))
    (when (and document (not (equal? (.ref (poo-flow-tla-model-outline document) 'module-identity)
                                     (substring name 0 (- (string-length name) 4)))))
      (error "TLA filename and declared module identity differ"))
    (poo-flow-tla-source-file-value name text (sha256-text text) document)))
(def (poo-flow-tla-toolchain java jar artifacts)
  (unless (and (string? java) (string? jar) (list? artifacts) (pair? artifacts)
               (every poo-flow-tla-tool-artifact? artifacts)
               (unique? (map (lambda (a) (.ref a 'path)) artifacts))) (error "invalid owner-pinned TLC toolchain"))
  (let* ((artifacts (sorted-by artifacts 'path))
         (sha (framed-sha (append (list "poo-flow.tlc.toolchain.v1" java jar) (apply append (map tool-row artifacts))))))
    (poo-flow-tla-toolchain-value java jar artifacts sha)))
(def (poo-flow-tla-bundle root sources toolchain workers: (workers 1))
  (unless (and (identifier? root) (list? sources) (pair? sources) (every poo-flow-tla-source-file? sources)
               (poo-flow-tla-toolchain? toolchain) (exact-integer? workers) (> workers 0)
               (unique? (map (lambda (f) (.ref f 'identity)) sources))) (error "invalid TLA source bundle"))
  (let ((sources (sorted-by sources 'identity)))
    (unless (every (lambda (name) (find (lambda (f) (equal? (.ref f 'identity) name)) sources))
                   (list (string-append root ".tla") (string-append root ".cfg"))) (error "bundle lacks root or config"))
    (poo-flow-tla-bundle-value root sources toolchain workers
      (framed-sha (append (list "poo-flow.tlc.private-bundle.v1" root (number->string workers) (.ref toolchain 'semantic-digest))
                          (apply append (map source-row sources)))))))
(def (poo-flow-tla-bundle-replay bundle)
  (unless (poo-flow-tla-bundle? bundle) (error "invalid TLA source bundle"))
  (let* ((t (.ref bundle 'toolchain))
         (tools (poo-flow-tla-toolchain (.ref t 'java) (.ref t 'jar) (.ref t 'artifacts)))
         (files (map (lambda (f) (poo-flow-tla-source-file (.ref f 'identity) (.ref f 'content))) (.ref bundle 'sources)))
         (canonical (poo-flow-tla-bundle (.ref bundle 'identity) files tools workers: (.ref bundle 'workers))))
    (unless (and (equal? (.ref t 'semantic-digest) (.ref tools 'semantic-digest))
                 (equal? (map source-row files) (map source-row (.ref bundle 'sources)))
                 (equal? (.ref canonical 'semantic-digest) (.ref bundle 'semantic-digest)))
      (error "source bundle differs from replayed contents and pins")) canonical))
(def (checked-id bundle-sha tool-sha output-sha)
  (framed-sha (list "poo-flow.tlc.checked-bundle.v1" bundle-sha tool-sha output-sha)))
(def (poo-flow-tla-checked-bundle-replay receipt bundle)
  (poo-flow-tla-bundle-replay bundle)
  (unless (and (poo-flow-tla-checked-bundle? receipt)
               (equal? (.ref receipt 'bundle-digest) (.ref bundle 'semantic-digest))
               (equal? (.ref receipt 'toolchain-digest) (.ref (.ref bundle 'toolchain) 'semantic-digest))
               (equal? (.ref receipt 'output-digest) (sha256-text (.ref receipt 'output)))
               (equal? (.ref receipt 'identity) (checked-id (.ref receipt 'bundle-digest) (.ref receipt 'toolchain-digest)
                                                         (.ref receipt 'output-digest))))
    (error "checked bundle differs from source/toolchain/output replay")) receipt)
(def (poo-flow-tla-check-bundle! bundle python: (python "python3"))
  (let* ((bundle (poo-flow-tla-bundle-replay bundle)) (tools (.ref bundle 'toolchain))
         (request (make-hash-table)) (files (make-hash-table)) (tool-json (make-hash-table))
         (directory (string-trim-eol (run-process (list "mktemp" "-d" (path-expand "poo-flow-bundle.XXXXXX" (getenv "TMPDIR" "/tmp"))))))
         (manifest (path-expand "request.json" directory)) (result #f))
    (unwind-protect
      (begin
        (for-each (lambda (f) (hash-put! files (.ref f 'identity) (.ref f 'content))) (.ref bundle 'sources))
        (hash-put! tool-json "java" (.ref tools 'java)) (hash-put! tool-json "jar" (.ref tools 'jar))
        (hash-put! tool-json "artifacts" (map tool-row (.ref tools 'artifacts)))
        (hash-put! request "root" (.ref bundle 'identity)) (hash-put! request "workers" (.ref bundle 'workers))
        (hash-put! request "sources" files) (hash-put! request "toolchain" tool-json)
        (call-with-output-file manifest (lambda (p) (write-json p request)))
        (run-process (list python "-m" "poo_flow_runtime.tla_bundle" manifest) stderr-redirection: #t
          coprocess: (lambda (process)
            (close-output-port process)
            (let loop ()
              (let* ((reader (spawn (lambda () (read-line process)))) (line (thread-join! reader 5 'quiet)))
                (cond ((eq? line 'quiet) (kill (process-pid process) SIGKILL) (thread-terminate! reader)
                                         (error "frozen bundle backend exceeded five-second output deadline"))
                      ((eof-object? line) (void))
                      ((and (>= (string-length line) 19) (equal? (substring line 0 19) "POO-FROZEN-RECEIPT "))
                       (when result (error "duplicate frozen bundle receipt"))
                       (set! result (parameterize ((current-json-read-options (JSONReadOptions object-as-hash: #t)))
                                      (string->json (substring line 19 (string-length line))))) (loop))
                      (else (displayln line) (force-output) (loop)))))))
        (unless (and result (equal? (hash-get result "schema") "poo-flow.tlc.private-bundle.v1")
                     (eq? (hash-get result "checked") #t) (= (hash-get result "exit_code") 0)
                     (equal? (hash-get result "bundle") (.ref bundle 'semantic-digest))
                     (equal? (hash-get result "toolchain") (.ref tools 'semantic-digest))
                     (equal? (hash-get result "sources") (map source-row (.ref bundle 'sources)))
                     (eq? (hash-get result "semantic_refinement") #f) (eq? (hash-get result "action_authorized") #f))
          (error "frozen bundle run failed or differs from exact POO inputs"))
        (poo-flow-tla-checked-bundle-replay
          (poo-flow-tla-checked-bundle-value
            (checked-id (.ref bundle 'semantic-digest) (.ref tools 'semantic-digest) (hash-get result "output_digest"))
            (.ref bundle 'semantic-digest) (.ref tools 'semantic-digest) (hash-get result "output") (hash-get result "output_digest")) bundle))
      (delete-file-or-directory directory #t))))
