;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref .slot? object?)
        (only-in :clan/poo/mop define-type Type. element?) (only-in :std/list/list every))
(export PooFlowTlaSourceFile PooFlowTlaToolArtifact PooFlowTlaToolchain PooFlowTlaBundle PooFlowTlaCheckedBundle
        poo-flow-tla-source-file? poo-flow-tla-tool-artifact? poo-flow-tla-toolchain? poo-flow-tla-bundle? poo-flow-tla-checked-bundle?)
(def (base? v kind slots)
  (and (object? v) (.slot? v 'kind) (eq? (.ref v 'kind) kind) (every (lambda (s) (.slot? v s)) slots)))
(def (text? v) (and (string? v) (> (string-length v) 0)))
(def (source? v) (and (base? v 'tla/source-file '(identity content semantic-digest document))
                     (text? (.ref v 'identity)) (string? (.ref v 'content)) (text? (.ref v 'semantic-digest))))
(def (artifact? v) (and (base? v 'tla/tool-artifact '(path semantic-digest))
                       (text? (.ref v 'path)) (text? (.ref v 'semantic-digest))))
(def (toolchain? v) (and (base? v 'tla/toolchain '(java jar artifacts semantic-digest))
                        (text? (.ref v 'java)) (text? (.ref v 'jar))
                        (list? (.ref v 'artifacts)) (every artifact? (.ref v 'artifacts)) (text? (.ref v 'semantic-digest))))
(def (bundle? v) (and (base? v 'tla/source-bundle '(identity sources toolchain workers semantic-digest))
                     (text? (.ref v 'identity)) (list? (.ref v 'sources)) (every source? (.ref v 'sources))
                     (toolchain? (.ref v 'toolchain)) (exact-integer? (.ref v 'workers)) (> (.ref v 'workers) 0)
                     (text? (.ref v 'semantic-digest))))
(def (checked? v) (and (base? v 'tla/checked-bundle '(identity bundle-digest toolchain-digest output output-digest semantic-refinement? action-authorized?))
                      (every text? (map (lambda (s) (.ref v s)) '(identity bundle-digest toolchain-digest output output-digest)))
                      (eq? (.ref v 'semantic-refinement?) #f) (eq? (.ref v 'action-authorized?) #f)))
(define-type (PooFlowTlaSourceFile @ Type.) .element?: source?)
(define-type (PooFlowTlaToolArtifact @ Type.) .element?: artifact?)
(define-type (PooFlowTlaToolchain @ Type.) .element?: toolchain?)
(define-type (PooFlowTlaBundle @ Type.) .element?: bundle?)
(define-type (PooFlowTlaCheckedBundle @ Type.) .element?: checked?)
(def (poo-flow-tla-source-file? v) (element? PooFlowTlaSourceFile v))
(def (poo-flow-tla-tool-artifact? v) (element? PooFlowTlaToolArtifact v))
(def (poo-flow-tla-toolchain? v) (element? PooFlowTlaToolchain v))
(def (poo-flow-tla-bundle? v) (element? PooFlowTlaBundle v))
(def (poo-flow-tla-checked-bundle? v) (element? PooFlowTlaCheckedBundle v))
