;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref .slot? object?)
        (only-in :clan/poo/mop define-type Type. element?)
        (only-in :std/list/list every)
        (only-in :poo-flow/modules/temporal-causality/types
                 poo-flow-temporal-model? poo-flow-temporal-query?)
        (only-in :poo-flow/modules/temporal-causality/behavior/types
                 poo-flow-temporal-behavior-model? poo-flow-temporal-property?))
(export PooFlowTlaTemporalEmission poo-flow-tla-temporal-emission?
        PooFlowTlaBehaviorEmission poo-flow-tla-behavior-emission?)
(def (emission? value)
  (and (object? value)
       (every (lambda (slot) (.slot? value slot))
              '(kind model query data-source check-source config-source
                     model-digest semantic-subset model-checking?))
       (eq? (.ref value 'kind) 'poo-flow.tla-plus.temporal-emission)
       (poo-flow-temporal-model? (.ref value 'model))
       (poo-flow-temporal-query? (.ref value 'query))
       (equal? (.ref value 'model-digest)
               (.ref (.ref value 'model) 'semantic-digest))
       (every string? (list (.ref value 'data-source)
                            (.ref value 'check-source)
                            (.ref value 'config-source)))
       (eq? (.ref value 'semantic-subset)
            'poo-flow.tla-plus.literal-hypothesis-family.v2)
       (eq? (.ref value 'model-checking?) #f)))
(define-type (PooFlowTlaTemporalEmission @ Type.) .element?: emission?)
(def (poo-flow-tla-temporal-emission? value)
  (element? PooFlowTlaTemporalEmission value))
(def (behavior-emission? value)
  (and (object? value)
       (every (lambda (slot) (.slot? value slot))
              '(kind model property data-source check-source config-source model-digest semantic-subset model-checking?))
       (eq? (.ref value 'kind) 'poo-flow.tla-plus.behavior-emission)
       (poo-flow-temporal-behavior-model? (.ref value 'model))
       (poo-flow-temporal-property? (.ref value 'property))
       (equal? (.ref value 'model-digest) (.ref (.ref value 'model) 'semantic-digest))
       (every string? (list (.ref value 'data-source) (.ref value 'check-source) (.ref value 'config-source)))
       (eq? (.ref value 'semantic-subset) 'poo-flow.tla-plus.logical-step-behavior.v1)
       (eq? (.ref value 'model-checking?) #f)))
(define-type (PooFlowTlaBehaviorEmission @ Type.) .element?: behavior-emission?)
(def (poo-flow-tla-behavior-emission? value) (element? PooFlowTlaBehaviorEmission value))
