"""Generate Scheme contract artifacts from user-provided JSON Schema."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, TextIO

_SCHEME_SYMBOL_SAFE = re.compile(r"[^A-Za-z0-9_+\-*/<>=!?$%&.:@~^/]")
_SCHEME_IDENTIFIER_SAFE = re.compile(r"[^A-Za-z0-9_+\-*/<>=!?$%&.:@~^]")


def json_schema_to_scheme_contract(
    schema: Mapping[str, Any],
    *,
    name: str = "funflow-custom-stage",
    source_ref: str = "json-schema",
    owner: str = "funflow",
    object_kind: str | None = None,
    object_key: str | None = None,
) -> str:
    """Render a Scheme source fragment for a JSON Schema contract artifact."""

    definition_prefix = _scheme_identifier(name)
    owner_symbol = _scheme_symbol(owner)
    object_kind_symbol = _scheme_symbol(
        object_kind or _default_object_kind(definition_prefix)
    )
    object_key_symbol = _scheme_symbol(object_key or f"funflow/{definition_prefix}")
    schema_datum = _scheme_json_datum(schema)
    source_ref_datum = _scheme_string(source_ref)
    return "\n".join(
        [
            ";;; -*- Gerbil -*-",
            ";;; Generated by poo-flow-jsonschema-contract.",
            ";;; Boundary: user-provided JSON Schema to Scheme contract artifact.",
            "",
            "(import (only-in :poo-flow/src/contract/json-schema-receipt",
            "                 poo-flow-json-schema->contract-artifact",
            "                 poo-flow-json-schema-contract-artifact->alist))",
            "",
            f"(export {definition_prefix}-schema",
            f"        {definition_prefix}-contract-artifact",
            f"        {definition_prefix}-contract-receipt)",
            "",
            ";; : JsonLikeSchema",
            f"(def {definition_prefix}-schema",
            f"  '{schema_datum})",
            "",
            ";; : PooFlowJsonSchemaContractArtifact",
            f"(def {definition_prefix}-contract-artifact",
            "  (poo-flow-json-schema->contract-artifact",
            f"   {definition_prefix}-schema",
            f"   '((source-ref . {source_ref_datum})",
            f"     (owner . {owner_symbol})",
            f"     (object-kind . {object_kind_symbol})",
            f"     (object-key . {object_key_symbol}))))",
            "",
            ";; : (-> Alist)",
            f"(def ({definition_prefix}-contract-receipt)",
            "  (poo-flow-json-schema-contract-artifact->alist",
            f"   {definition_prefix}-contract-artifact))",
            "",
        ]
    )


def load_json_schema(path: str | Path) -> Mapping[str, Any]:
    """Read a JSON Schema file as a mapping."""

    schema_path = Path(path)
    with schema_path.open("r", encoding="utf-8") as stream:
        value = json.load(stream)
    if not isinstance(value, Mapping):
        raise ValueError("JSON Schema root must be an object")
    return value


def main(argv: Sequence[str] | None = None, stdout: TextIO | None = None) -> int:
    """Command-line entrypoint for JSON Schema to Scheme contract generation."""

    parser = argparse.ArgumentParser(
        prog="poo-flow-jsonschema-contract",
        description="Generate a Scheme JSON Schema contract artifact.",
    )
    parser.add_argument("schema", help="path to a JSON Schema file")
    parser.add_argument(
        "--name",
        default="funflow-custom-stage",
        help="Scheme definition prefix for the generated contract",
    )
    parser.add_argument(
        "--source-ref",
        default=None,
        help="source-ref stored in the generated contract artifact",
    )
    parser.add_argument("--owner", default="funflow", help="contract owner symbol")
    parser.add_argument("--object-kind", default=None, help="object kind symbol")
    parser.add_argument("--object-key", default=None, help="object key symbol")
    parser.add_argument("--output", default=None, help="output Scheme source path")
    args = parser.parse_args(argv)

    schema_path = Path(args.schema)
    source = json_schema_to_scheme_contract(
        load_json_schema(schema_path),
        name=args.name,
        source_ref=args.source_ref or str(schema_path),
        owner=args.owner,
        object_kind=args.object_kind,
        object_key=args.object_key,
    )
    if args.output:
        Path(args.output).write_text(source, encoding="utf-8")
    else:
        output = stdout or sys.stdout
        output.write(source)
    return 0


def _default_object_kind(definition_prefix: str) -> str:
    parts = [part for part in re.split(r"[-_/]+", definition_prefix) if part]
    return "PooFlow" + "".join(part.capitalize() for part in parts) + "Object"


def _scheme_identifier(value: str) -> str:
    normalized = _SCHEME_IDENTIFIER_SAFE.sub("-", value.strip())
    normalized = re.sub(r"-+", "-", normalized).strip("-")
    if not normalized:
        normalized = "json-schema-contract"
    if normalized[0].isdigit():
        normalized = f"schema-{normalized}"
    return normalized


def _scheme_symbol(value: str) -> str:
    normalized = _SCHEME_SYMBOL_SAFE.sub("-", value.strip())
    normalized = re.sub(r"-+", "-", normalized).strip("-")
    if not normalized:
        normalized = "json-schema"
    if normalized[0].isdigit():
        normalized = f"schema-{normalized}"
    return normalized


def _scheme_json_datum(value: Any) -> str:
    if isinstance(value, Mapping):
        return "(" + " ".join(_scheme_json_row(k, v) for k, v in value.items()) + ")"
    if isinstance(value, list):
        return "(" + " ".join(_scheme_json_datum(item) for item in value) + ")"
    if isinstance(value, tuple):
        return "(" + " ".join(_scheme_json_datum(item) for item in value) + ")"
    if isinstance(value, bool):
        return "#t" if value else "#f"
    if isinstance(value, str):
        return _scheme_string(value)
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return _scheme_float(value)
    if value is None:
        return "json-null"
    raise TypeError(f"unsupported JSON Schema value: {type(value).__name__}")


def _scheme_json_row(key: Any, value: Any) -> str:
    if not isinstance(key, str):
        raise TypeError("JSON Schema object keys must be strings")
    return f"({_scheme_string(key)} . {_scheme_json_datum(value)})"


def _scheme_float(value: float) -> str:
    if value != value or value in (float("inf"), float("-inf")):
        raise ValueError("JSON Schema numbers must be finite")
    return repr(value)


def _scheme_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


__all__ = [
    "json_schema_to_scheme_contract",
    "load_json_schema",
    "main",
]
