;;; -*- Gerbil -*-
;;; Boundary: public facade for module loader source declarations.
;;; Invariant: backend receipts and tree/catalog declarations live in leaf owners.

(import :poo-flow/src/module-system/loader-backend
        :poo-flow/src/module-system/loader-tree)

(export make-poo-flow-module-loader-entry
        poo-flow-module-loader-entry?
        poo-flow-module-loader-entry-source
        poo-flow-module-loader-entry-module
        make-poo-flow-module-loader-backend
        poo-flow-module-loader-backend?
        poo-flow-module-loader-backend-name
        poo-flow-module-loader-backend-source-kind
        poo-flow-module-loader-backend-load
        poo-flow-module-loader-backend-metadata
        make-poo-flow-lazy-load-plan
        poo-flow-lazy-load-plan?
        poo-flow-lazy-load-plan-source
        poo-flow-lazy-load-plan-backends
        poo-flow-lazy-load-plan-forced?
        poo-flow-lazy-load-plan-receipt
        poo-flow-lazy-load-plan-metadata
        make-poo-flow-module-load-receipt
        poo-flow-module-load-receipt?
        poo-flow-module-load-receipt-source
        poo-flow-module-load-receipt-module
        poo-flow-module-load-receipt-backend-name
        poo-flow-module-load-receipt-loaded?
        poo-flow-module-load-receipt-code
        poo-flow-module-load-receipt-messages
        poo-flow-module-load-receipt-metadata
        poo-flow-module-static-loader
        poo-flow-module-loader-backend-supports?
        poo-flow-lazy-load-source-receipt
        poo-flow-make-lazy-load-plan
        poo-flow-force-lazy-load-source-receipt
        poo-flow-force-lazy-load-plan
        poo-flow-module-load-source-receipt
        poo-flow-module-load-source-receipts
        poo-flow-module-load-receipt->alist
        poo-flow-module-tree-entrypoint
        poo-flow-module-tree-source
        poo-flow-module-tree-config-source
        poo-flow-module-tree-objects-source
        poo-flow-module-tree-source-refs
        poo-flow-module-tree-lazy-load-plans
        poo-flow-src-modules-root
        poo-flow-src-module-tree-entrypoints
        poo-flow-module-system-source
        poo-flow-module-system-source-refs
        poo-flow-module-category-names
        poo-flow-module-tree-entrypoint-module-name
        poo-flow-module-tree-entrypoint-name-conflict?
        poo-flow-module-tree-entrypoint-conflicts
        poo-flow-src-module-tree-entrypoint-conflicts
        poo-flow-src-modules-source-refs
        poo-flow-src-modules-lazy-load-plans
        poo-flow-module-auto-import-root-identity
        poo-flow-module-auto-import-entry-node
        poo-flow-module-auto-imports-node
        poo-flow-module-auto-imports-mk-merge
        poo-flow-module-auto-imports-result-source-refs
        poo-flow-user-tree-source
        poo-flow-user-tree-entrypoint-policy
        poo-flow-user-tree-source-allowed-responsibilities
        poo-flow-user-tree-source-denied-responsibilities
        poo-flow-user-tree-source-allows?
        poo-flow-user-tree-source-policy-violations
        poo-flow-user-tree-source-valid?
        poo-flow-user-tree-init-source
        poo-flow-user-tree-objects-source
        poo-flow-user-tree-config-source
        poo-flow-user-tree-modules-config-source
        poo-flow-user-tree-source-refs
        poo-flow-user-tree-lazy-load-plans
        poo-flow-module-load-source
        poo-flow-module-load-sources
        poo-flow-module-load-catalog)
