;;; -*- Gerbil -*-
;;; Boundary: profile fragment name resolution for composition syntax.
;;; Invariant: mirrors load! binding names without importing the loader owner.

(import (only-in :gerbil/expander/core
                 current-expander-context
                 expander-context-id))

(export poo-flow-composition-profile-module)

(begin-syntax
  ;; Engineering note: policy-sensitive helpers in this owner keep explicit
  ;; contracts adjacent to definitions so downstream reports stay actionable.
  ;; : (-> Any Any)
  (def (poo-flow-composition-string-prefix? prefix value)
    (let ((prefix-length (string-length prefix))
          (value-length (string-length value)))
      (and (>= value-length prefix-length)
           (string=? (substring value 0 prefix-length) prefix))))

  ;; : (-> Any Any)
  (def (poo-flow-composition-path-segments value)
    (let ((length (string-length value)))
      (let loop ((index 0) (start 0) (segments '()))
        (cond
         ((= index length)
          (reverse (cons (substring value start index) segments)))
         ((char=? (string-ref value index) #\/)
          (loop (+ index 1)
                (+ index 1)
                (cons (substring value start index) segments)))
         (else
          (loop (+ index 1) start segments))))))

  ;; : (-> Any Any)
  (def (poo-flow-composition-member-tail needle values)
    (let loop ((rest values))
      (cond
       ((null? rest) #f)
       ((equal? (car rest) needle) rest)
       (else (loop (cdr rest))))))

  ;; : (-> Any Any)
  (def (poo-flow-composition-module-context-source-path)
    (let* ((context-id
            (expander-context-id (current-expander-context)))
           (context-name
            (and (symbol? context-id)
                 (symbol->string context-id)))
           (package-prefix "poo-flow/"))
      (and context-name
           (let (relative-context-name
                 (if (poo-flow-composition-string-prefix? package-prefix
                                                          context-name)
                   (substring context-name
                              (string-length package-prefix)
                              (string-length context-name))
                   context-name))
             (string-append relative-context-name ".ss")))))

  ;; : (-> Any Any)
  (def (poo-flow-composition-current-custom-module-name)
    (let* ((context-source-path
            (poo-flow-composition-module-context-source-path))
           (source-segments
            (if context-source-path
              (poo-flow-composition-path-segments context-source-path)
              []))
           (custom-tail
            (poo-flow-composition-member-tail "custom" source-segments)))
      (if (and custom-tail (pair? (cdr custom-tail)))
        (cadr custom-tail)
        "module")))

  ;; : (-> Any Any)
  (def (poo-flow-composition-profile-binding-syntax ctx profile-name)
    (let (profile-key (syntax->datum profile-name))
      (unless (symbol? profile-key)
        (error "use-profile expects a symbolic profile fragment name"
               profile-name))
      (datum->syntax
       ctx
       (string->symbol
        (string-append "poo-flow-custom-"
                       (poo-flow-composition-current-custom-module-name)
                       "-"
                       (symbol->string profile-key)
                       "-module"))))))

;; poo-flow-composition-profile-module
;; : (-> Syntax Syntax)
;; | doc m%
;;   Resolves a loaded profile fragment name to the binding generated by load!.
;;   Boundary: this expands only to an identifier and adds no runtime registry.
;;   # Examples
;;   ```scheme
;;   (poo-flow-composition-profile-module langchain)
;;   ;; => poo-flow-custom-<module>-langchain-module
;;   ```
(defsyntax (poo-flow-composition-profile-module stx)
  (syntax-case stx ()
    ((ctx profile-name)
     (poo-flow-composition-profile-binding-syntax
      (syntax ctx)
      (syntax profile-name)))))
