;;; -*- Gerbil -*-
;;; Boundary: effective method execution consumes cached plans.
;;; Invariant: invocation results are never cached.
(import (only-in :clan/poo/object .ref)
        (only-in :clan/poo/mop element?) "types.ss" "objects.ss")
(export poo-combination-call poo-combination-bind poo-call-next-method poo-next-method?)
(def (require-frame frame)
  (unless (element? CombinationFrame frame) (combination-fail 'invalid-invocation-frame)) frame)
(def (frame-fail frame code)
  (combination-fail code generic: (.ref (.ref (.ref frame 'plan) 'generic) 'identity)
                    qualifier: (.ref frame 'qualifier) method: (.ref (.ref frame 'method) 'identity)))
(def (arguments-valid! generic arguments)
  (let ((count (length (cdr arguments))) (required (.ref generic 'required)))
    (unless (if (.ref generic 'rest?) (>= count required) (= count required))
      (combination-fail 'argument-count-mismatch generic: (.ref generic 'identity)))))
(def (same-methods? left right)
  (or (eq? left right)
      (and (pair? left) (pair? right) (eq? (car left) (car right))
           (same-methods? (cdr left) (cdr right)))))
(def (same-plan? left right)
  (or (eq? left right)
      (andmap (lambda (q) (same-methods? (.ref left q) (.ref right q)))
              '(around before primary after))))
(def (poo-next-method? frame)
  (require-frame frame)
  (and (if (memq (.ref frame 'qualifier) '(around primary)) #t #f)
       (if (.ref frame 'next) #t #f)))
(def (poo-call-next-method frame . replacement)
  (require-frame frame)
  (unless (memq (.ref frame 'qualifier) '(around primary))
    (frame-fail frame 'next-forbidden-in-auxiliary))
  (let* ((plan (.ref frame 'plan)) (generic (.ref plan 'generic))
         (arguments (if (null? replacement) (.ref frame 'arguments) replacement)))
    (arguments-valid! generic arguments)
    ;; Replacement applicability is checked even when there is no next.
    ;; No-argument next keeps the original lexical arguments and captured plan.
    (unless (or (null? replacement) (same-plan? plan (receiver-plan generic (car arguments))))
      (frame-fail frame 'changed-applicable-methods))
    (unless (.ref frame 'next) (frame-fail frame 'no-next-method))
    ((.ref frame 'next) arguments)))
(def (invoke method plan arguments next qualifier)
  (apply (.ref method 'body) (make-frame plan arguments next qualifier method) arguments))
(def (ignore-values thunk) (call-with-values thunk (lambda _ (void))))
(def (execute-plan plan arguments)
  (let ((generic (.ref plan 'generic)) (around (.ref plan 'around))
        (before (.ref plan 'before)) (primary (.ref plan 'primary))
        (after (.ref plan 'after-order)))
    (when (and (null? around) (null? before) (null? primary) (null? after))
      (combination-fail 'no-applicable-method generic: (.ref generic 'identity)))
    (when (null? primary)
      (combination-fail 'no-primary-method generic: (.ref generic 'identity)))
    (def (run-primary methods args)
      (invoke (car methods) plan args
              (and (pair? (cdr methods)) (lambda (new) (run-primary (cdr methods) new))) 'primary))
    (def (run-auxiliary methods args qualifier)
      (for-each (lambda (method)
                  (ignore-values (lambda () (invoke method plan args #f qualifier)))) methods))
    (def (core args)
      (run-auxiliary before args 'before)
      (call-with-values (lambda () (run-primary primary args))
        (lambda results
          (run-auxiliary after args 'after)
          (apply values results))))
    (def (run-around methods args)
      (if (null? methods) (core args)
          (invoke (car methods) plan args (lambda (new) (run-around (cdr methods) new)) 'around)))
    (run-around around arguments)))
(def (poo-combination-call generic receiver . arguments)
  (require-generic generic)
  (let (all-arguments (cons receiver arguments))
    (arguments-valid! generic all-arguments)
    (execute-plan (receiver-plan generic receiver) all-arguments)))
(def (poo-combination-bind generic)
  (require-generic generic)
  ;; Ordinary function binding; no new macro or generated global name.
  (lambda (receiver . arguments) (apply poo-combination-call generic receiver arguments)))
