;;; -*- Gerbil -*-
(import (only-in :std/test test-suite test-case check-equal? check-exception)
        (only-in :clan/poo/object .o .ref .cc .mix)
        (only-in :clan/poo/mop element? .defgeneric)
        "../src/module-system/poo-method-combination/interface.ss")
(export poo-method-combination-contract-test)
(def (code? expected)
  (lambda (e) (and (poo-combination-failure? e) (eq? (.ref e 'code) expected))))
(def (value-method _frame _receiver value) value)
(def (next-method frame _receiver . _values) (poo-call-next-method frame))
(def g (poo-combination-generic 'contract 'contract/plan required: 1 rest?: #f))
(def m (poo-combination-method 'value value-method))
(def b (poo-method-bundle primary: m))
(def base (poo-method-prototype (poo-method-root g) g b))
(.defgeneric (native-value receiver) slot: native/value)
(.defgeneric (native-type-value receiver value) from: type slot: native/value)
(def poo-method-combination-contract-test
  (test-suite "module: native method combination contracts"
    (test-case "native Type descriptors reject lookalikes and retain extension"
      (check-equal? (element? CombinationGeneric g) #t)
      (check-equal? (element? CombinationMethod m) #t)
      (check-equal? (element? CombinationBundle b) #t)
      (check-equal? (element? CombinationMethod (.cc m 'description 'extension)) #t)
      (check-equal? (element? CombinationMethod (.o identity: 'value body: value-method)) #f)
      (check-equal? (element? CombinationMethod (.cc m 'body 42)) #f)
      (check-equal? (element? CombinationBundle (.cc b 'before 'not-a-method)) #f)
      (check-equal? (poo-combination-failure? (.o code: 'invalid-method)) #f)
      (check-equal? (eq? (poo-method-root g) (poo-method-root g)) #t))
    (test-case "checked constructors and all public entry points"
      (for-each (lambda (thunk) (check-exception (thunk) (code? 'invalid-generic)))
        (list (lambda () (poo-combination-generic 1 'slot))
              (lambda () (poo-combination-generic 'id 1))
              (lambda () (poo-combination-generic 'id 'slot from: 'multi))
              (lambda () (poo-combination-generic 'id 'slot required: -1))
              (lambda () (poo-combination-generic 'id 'slot required: 1.5))
              (lambda () (poo-combination-generic 'id 'slot rest?: 'yes))
              (lambda () (poo-combination-generic 'id 'poo/combination/owners))
              (lambda () (poo-method-root 'not-a-generic))
              (lambda () (poo-combination-bind 'not-a-generic))
              (lambda () (poo-combination-call 'not-a-generic base 1))))
      (check-exception (poo-combination-method 'bad 1) (code? 'invalid-method))
      (check-exception (poo-combination-method 1 value-method) (code? 'invalid-method))
      (check-exception (poo-method-bundle before: 1) (code? 'invalid-bundle))
      (check-exception (poo-method-prototype base g (.o)) (code? 'invalid-bundle))
      (check-exception (poo-method-prototype (.o) g b) (code? 'missing-method-root))
      (check-exception (poo-combination-call g 42 1) (code? 'invalid-receiver))
      (check-exception (poo-next-method? (.o)) (code? 'invalid-invocation-frame))
      (check-exception (poo-call-next-method (.o)) (code? 'invalid-invocation-frame)))
    (test-case "fixed and rest argument contracts run before any body"
      (check-equal? ((poo-combination-bind g) base 3) 3)
      (check-exception (poo-combination-call g base) (code? 'argument-count-mismatch))
      (check-exception (poo-combination-call g base 1 2) (code? 'argument-count-mismatch))
      (def (all-values _frame _receiver . values) values)
      (let* ((rest-g (poo-combination-generic 'rest 'rest/plan required: 1))
             (receiver (poo-method-prototype (poo-method-root rest-g) rest-g
                         (poo-method-bundle primary: (poo-combination-method 'all all-values)))))
        (check-equal? (poo-combination-call rest-g receiver 1 2 3) '(1 2 3))
        (check-exception (poo-combination-call rest-g receiver) (code? 'argument-count-mismatch))))
    (test-case "type dispatch shares plan, never receiver or results"
      (def (payload _frame receiver value) (list (.ref receiver 'payload) value))
      (let* ((type-g (poo-combination-generic 'typed 'typed/plan from: 'type required: 1 rest?: #f))
             (type (poo-method-prototype (poo-method-root type-g) type-g
                     (poo-method-bundle primary: (poo-combination-method 'payload payload))))
             (one (.cc (.o payload: 1) '.type type))
             (two (.cc one 'payload 2)))
        (check-equal? (poo-combination-call type-g one 'a) '(1 a))
        (check-equal? (poo-combination-call type-g two 'b) '(2 b))
        (check-exception (poo-combination-call type-g (.o) 1) (code? 'missing-dispatch-type))
        (check-exception (poo-combination-call type-g (.o .type: 42) 1) (code? 'invalid-dispatch-type))
        (check-exception (poo-combination-call type-g (.o .type: (.o)) 1) (code? 'no-applicable-method))))
    (test-case "native generic semantics are unchanged"
      (check-equal? (native-value (.o native/value: 42)) 42)
      (def (plus receiver value) (+ (.ref receiver 'payload) value))
      (check-equal? (native-type-value (.o .type: (.o native/value: plus) payload: 7) 3) 10))
    (test-case "multiple independent generics compose; same-slot ownership rejects"
      (let* ((other (poo-combination-generic 'other 'other/plan))
             (other-base (poo-method-prototype (poo-method-root other) other b))
             (both (.mix base other-base))
             (conflict (poo-combination-generic 'conflict 'contract/plan))
             (conflict-base (poo-method-prototype (poo-method-root conflict) conflict b)))
        (check-equal? (poo-combination-call g both 7) 7)
        (check-equal? (poo-combination-call other both 8) 8)
        (check-exception (poo-combination-call g (.mix base conflict-base) 1)
                         (code? 'generic-slot-collision))
        (check-exception (poo-combination-call g (.mix conflict-base base) 1)
                         (code? 'generic-slot-collision))))
    (test-case "malformed plans reject and source slot exceptions propagate unchanged"
      (check-exception (poo-combination-call g (.cc base 'contract/plan 42) 1)
                       (code? 'invalid-method-plan))
      (let (bad-plan (.cc (.ref base 'contract/plan) 'primary 'not-methods))
        (check-exception (poo-combination-call g (.cc base 'contract/plan bad-plan) 1)
                         (code? 'invalid-method-plan)))
      (let (sentinel (.o source: 'slot-computation))
        (check-exception
         (poo-combination-call g (.o contract/plan: (raise sentinel)) 1)
         (lambda (e) (eq? e sentinel)))))
    (test-case "invalid C3 remains an upstream error; unrelated slots stay lazy"
      (let* ((left (.mix base)) (right (.mix base))
             (invalid (.mix (.mix left right) (.mix right left))))
        (check-exception (poo-combination-call g invalid 1)
                         (lambda (e) (not (poo-combination-failure? e)))))
      (let (forced? #f)
        (let (receiver (.mix base (.o unrelated: (begin (set! forced? #t) 'value))))
          (check-equal? (poo-combination-call g receiver 7) 7)
          (check-equal? forced? #f))))
    (test-case "ordered applicability, not just a set, is preserved"
      (let* ((left (poo-method-prototype base g
                     (poo-method-bundle primary: (poo-combination-method 'left next-method))))
             (right (poo-method-prototype base g
                      (poo-method-bundle primary: (poo-combination-method 'right next-method))))
             (target #f))
        (def (change frame _receiver _value) (poo-call-next-method frame target 1))
        (let* ((bundle (poo-method-bundle around: (poo-combination-method 'change change)))
               (receiver (poo-method-prototype (.mix left right) g bundle)))
          (set! target (poo-method-prototype (.mix right left) g bundle))
          (check-exception (poo-combination-call g receiver 1) (code? 'changed-applicable-methods)))))
    (test-case "next failure retains generic, qualifier and method identity"
      (let (receiver (poo-method-prototype (poo-method-root g) g
                       (poo-method-bundle primary: (poo-combination-method 'last next-method))))
        (check-exception (poo-combination-call g receiver 1)
          (lambda (e)
            (and (element? CombinationFailure e) (eq? (.ref e 'code) 'no-next-method)
                 (eq? (.ref e 'generic) 'contract) (eq? (.ref e 'qualifier) 'primary)
                 (eq? (.ref e 'method) 'last))))))))
