;;; -*- Gerbil -*-
;;; Whole invocation semantics, beyond descriptor and applicability checks.
(import (only-in :std/test test-suite test-case check-equal? check-exception)
        (only-in :clan/poo/object .o .ref .cc)
        "../src/research/poo-method-combination/interface.ss")
(export poo-method-combination-next-test)
(def g (poo-combination-generic 'invocation 'invocation/plan required: 1 rest?: #f))
(def root (poo-method-root g))
(def (code? expected)
  (lambda (e) (and (poo-combination-failure? e) (eq? (.ref e 'code) expected))))
(def (value _frame _receiver value) value)
(def (layer base around before primary after)
  (def (method name body) (and body (poo-combination-method name body)))
  (poo-method-prototype base g
    (poo-method-bundle around: (method 'around around) before: (method 'before before)
                       primary: (method 'primary primary) after: (method 'after after))))
(def poo-method-combination-next-test
  (test-suite "research: complete effective invocation scenarios"
    (test-case "primary shadow skips inherited primary, but not auxiliary methods"
      (let (events '())
        (def (record x) (set! events (append events (list x))))
        (def (before _f _r _v) (record 'before))
        (def (after _f _r _v) (record 'after))
        (def (inherited _f _r _v) (record 'inherited) 'wrong)
        (def (shadow frame _r _v)
          (record 'shadow) (check-equal? (poo-next-method? frame) #t) 'answer)
        (let (receiver (layer (layer root #f before inherited after) #f #f shadow #f))
          (check-equal? (poo-combination-call g receiver 0) 'answer)
          (check-equal? events '(before shadow after)))))
    (test-case "around short circuit suppresses the entire inner core"
      (let (events '())
        (def (inner _f _r _v) (set! events (cons 'inner events)))
        (def (stop frame _r _v)
          (check-equal? (poo-next-method? frame) #t) (values 'stopped 'outer))
        (let (receiver (layer root stop inner inner inner))
          (check-equal? (call-with-values (lambda () (poo-combination-call g receiver 0)) list)
                        '(stopped outer))
          (check-equal? events '()))))
    (test-case "before and after exceptions retain identity and stop later work"
      (let ((events '()) (sentinel (.o source: 'auxiliary)))
        (def (record _f _r _v) (set! events (cons 'ran events)))
        (def (explode _f _r _v) (raise sentinel))
        (check-exception (poo-combination-call g (layer root #f explode record record) 0)
                         (lambda (e) (eq? e sentinel)))
        (check-equal? events '())
        (check-exception
         (poo-combination-call g (layer (layer root #f #f value explode) #f #f #f record) 0)
         (lambda (e) (eq? e sentinel)))
        (check-equal? events '())))
    (test-case "primary next replacements affect delegated methods, not auxiliary arguments"
      (let (events '())
        (def (auxiliary _f receiver argument)
          (set! events (append events (list (list (.ref receiver 'payload) argument)))))
        (def (read-value _f receiver argument) (list (.ref receiver 'payload) argument))
        (def (replace frame receiver _argument)
          (poo-call-next-method frame (.cc receiver 'payload 'replacement) 42))
        (let (receiver (.cc (layer (layer root #f auxiliary read-value auxiliary) #f #f replace #f)
                            'payload 'original))
          (check-equal? (poo-combination-call g receiver 7) '(replacement 42))
          (check-equal? events '((original 7) (original 7))))))
    (test-case "multiple around next calls each execute the full core"
      (let (events '())
        (def (before _f _r argument) (set! events (append events (list (list 'before argument)))))
        (def (after _f _r argument) (set! events (append events (list (list 'after argument)))))
        (def (twice frame receiver _argument)
          (list (poo-call-next-method frame receiver 1) (poo-call-next-method frame)))
        (check-equal? (poo-combination-call g (layer root twice before value after) 7) '(1 7))
        (check-equal? events '((before 1) (after 1) (before 7) (after 7)))))
    (test-case "recursive generic invocation retains each outer lexical frame"
      (def (recurse frame receiver argument)
        (if (= argument 0) (poo-call-next-method frame)
            (+ (poo-combination-call g receiver (- argument 1)) (poo-call-next-method frame))))
      (check-equal? (poo-combination-call g (layer (layer root #f #f value #f) #f #f recurse #f) 4) 10))
    (test-case "type-based next receives a new receiver with the same type plan"
      (let* ((typed (poo-combination-generic 'typed 'typed/plan from: 'type required: 1 rest?: #f))
             (typed-root (poo-method-root typed)))
        (def (read-payload _frame receiver argument) (list (.ref receiver 'payload) argument))
        (def (replace frame receiver argument) (poo-call-next-method frame (.cc receiver 'payload 2) argument))
        (let* ((base (poo-method-prototype typed-root typed
                       (poo-method-bundle primary: (poo-combination-method 'payload read-payload))))
               (type (poo-method-prototype base typed
                       (poo-method-bundle primary: (poo-combination-method 'replace replace))))
               (receiver (.cc (.o payload: 1) '.type type)))
          (check-equal? (poo-combination-call typed receiver 'argument) '(2 argument)))))
    (test-case "retained lexical frame replays next without an expiry protocol"
      (let (saved #f)
        (def (capture frame _receiver _argument) (set! saved frame) 'captured)
        (let (receiver (layer (layer root #f #f value #f) #f #f capture #f))
          (check-equal? (poo-combination-call g receiver 7) 'captured)
          (check-equal? (poo-next-method? saved) #t)
          (check-equal? (poo-call-next-method saved receiver 9) 9)
          (check-equal? (poo-call-next-method saved) 7)
          (check-equal? (poo-call-next-method saved) 7))))
    (test-case "replacement checks still apply to the last primary"
      (def (bad-arity frame receiver _argument) (poo-call-next-method frame receiver))
      (check-exception (poo-combination-call g (layer root #f #f bad-arity #f) 0)
                       (code? 'argument-count-mismatch))
      (def (changed frame _receiver _argument) (poo-call-next-method frame root 0))
      (check-exception (poo-combination-call g (layer root #f #f changed #f) 0)
                       (code? 'changed-applicable-methods)))))
