;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .o .ref) :std/test (only-in :std/error Error? Error-message) (only-in :std/encoding/json write-json)
 (only-in :core/observability/debug PooFlowDebugMemoryAnomaly? PooFlowDebugMemoryAnomaly-receipt poo-flow-debug-memory-receipt-sexp)
 (only-in :core/observability/testing-case poo-flow-test-case)
 :poo-flow/modules/temporal-causality/interface
 :poo-flow/modules/temporal-causality/candidates/ascent/interface
 :poo-flow/modules/temporal-causality/candidates/ascent/runtime
 (only-in :gerbil-ascent/candidate/reasoning reasoning-receipt-proof)
 (only-in :gerbil-ascent/candidate/provenance positive-proof-roots))
(export temporal-ascent-provider-test main)
(def model
 (poo-flow-temporal-model "provider-model" (list (poo-flow-temporal-clock-domain "local" 'logical-version))
  (list (poo-flow-temporal-model-observation "cause" "local" 1 "source" 'observed)
        (poo-flow-temporal-model-observation "effect" "local" 2 "source" 'observed))
  (list (poo-flow-temporal-hypothesis "target" "cause" "effect" '())) #t))
(def query (poo-flow-temporal-query "query" "target" #f))
(def binding (poo-flow-ascent-source-binding model query "cut" 1))
(def scope (poo-flow-candidate-scope "scope" "cut" 1 binding '(ascent)))
(def (completed label value)
 (displayln "PROVIDER-STAGE-OK " label) (force-output) value)
(def (request (m model) (q query) (s scope))
 (let (r (completed "request" (poo-flow-ascent-candidate-request "request" s m q)))
  (completed "request-replayed" (poo-flow-ascent-candidate-request-replay r))))
(def (execute r)
 (with-catch
  (lambda (e)
   (displayln "EXECUTE-ERROR " (if (Error? e) (Error-message e) "native exception"))
   (when (PooFlowDebugMemoryAnomaly? e)
    (displayln "MEMORY-REJECTION " (poo-flow-debug-memory-receipt-sexp (PooFlowDebugMemoryAnomaly-receipt e))))
   (force-output) (raise e))
  (lambda () (completed "native-execution" (poo-flow-ascent-candidate-execute! r)))))
(def (verify r e) (completed "independent-proof-check" (poo-flow-ascent-candidate-verify r e)))
(def authority (poo-flow-temporal-source-authority "source-owner" "issuer" "source" "key" "knowledge" (make-u8vector 32 7)))
(def as-of (poo-flow-temporal-instant "now" "knowledge" 5 "source" 'observed))
(def assertion (poo-flow-temporal-source-attest authority "coverage" 'candidate-source-model-binding binding 0 10))
(def (admit r e (a assertion)) (completed "source-and-temporal-admission" (poo-flow-ascent-candidate-admission r e authority a as-of "subject" "projection" "policy")))
(def temporal-ascent-provider-test
 (test-suite "real ASCENT candidate verification to Temporal admission"
  (poo-flow-test-case "native provider, independent proof and separate source authority admit a native handoff"
   (let* ((r (request)) (e (execute r)) (x (verify r e)) (a (admit r e)))
    (check (.ref x 'status) => 'reviewable) (check (.ref x 'admitted?) => #f)
    (check (.ref a 'source-verified?) => #t) (check (.ref a 'admitted?) => #t)
    (check (.ref (.ref a 'evaluation) 'classification) => 'necessary)
    (let* ((evaluation (.ref a 'evaluation))
           (root (poo-flow-temporal-conclusion-root "root" "subject" "scope" "cut" "projection" "policy" "ascent-generation/1" "necessary" (.ref evaluation 'identity)))
           (journal (poo-flow-temporal-conclusion-journal "journal" (list root))))
     (check (.ref (poo-flow-temporal-publication journal root model "nonce" 2000000000 evaluation: evaluation) 'operation) => "assert"))))
  (poo-flow-test-case "source tampering cannot upgrade a checked exchange"
   (let* ((r (request)) (e (execute r))
          (a (admit r e (.o (:: @ assertion) signature: (make-u8vector 32 0)))))
    (check (.ref (.ref a 'exchange) 'status) => 'reviewable)
    (check (.ref a 'source-verified?) => #f) (check (.ref a 'evaluation) => #f) (check (.ref a 'admitted?) => #f)))
  (poo-flow-test-case "expired coverage and absent coverage remain unadmitted"
   (let* ((r (request)) (e (execute r))
          (expired (poo-flow-temporal-source-attest authority "expired" 'candidate-source-model-binding binding 0 5))
          (missing (request model query (poo-flow-candidate-scope "scope" "cut" 1 #f '(ascent)))))
    (check (.ref (admit r e expired) 'admitted?) => #f)
    (check (.ref (admit missing (execute missing)) 'admitted?) => #f)))
  (poo-flow-test-case "changed cut generation or model rejects receipt reuse"
   (let* ((r (request)) (e (execute r))
          (changed (request model query (poo-flow-candidate-scope "scope" "new-cut" 2 binding '(ascent)))))
    (check-exception (verify changed e) true)
    (check-exception (poo-flow-ascent-candidate-request-replay (.o (:: @ r) binding-digest: "forged")) true)
    (let* ((other (poo-flow-temporal-overlapping-model "different" (.ref model 'domains) (.ref model 'observations) (.ref model 'hypotheses) #t))
           (native (.ref (execute (request other)) 'native-receipt)))
     (check-exception (verify r (.o (:: @ e) native-receipt: native)) true))))
  (poo-flow-test-case "a forged proof root is rejected by the independent checker"
   (let* ((r (request)) (e (execute r)) (p (reasoning-receipt-proof (.ref e 'native-receipt))))
    (set-car! (positive-proof-roots p) 999999)
    (check (.ref (verify r e) 'status) => 'rejected)
    (check (.ref (admit r e) 'admitted?) => #f)))
  (poo-flow-test-case "proof budget exhaustion cannot be promoted from native completion"
   (let* ((r (poo-flow-ascent-candidate-request "bounded" scope model query proof-work: 1))
          (e (execute r)))
    (check (.ref (verify r e) 'status) => 'pending)
    (check (.ref (admit r e) 'admitted?) => #f)))
  (poo-flow-test-case "incomplete native output remains pending"
   (let* ((m (poo-flow-temporal-model "bounded-native" (.ref model 'domains) (.ref model 'observations)
                 (list (poo-flow-temporal-hypothesis "other" "cause" "effect" '())
                       (poo-flow-temporal-hypothesis "target" "cause" "effect" '())) #t))
          (r (poo-flow-ascent-candidate-request "bounded-native" scope m query derived-limit: 1))
          (e (execute r)))
    (check (.ref (verify r e) 'status) => 'pending)
    (check (.ref (admit r e) 'admitted?) => #f)))
  (poo-flow-test-case "an empty positive query result grants no closed absence claim"
   (let* ((m (poo-flow-temporal-model "declared" (.ref model 'domains)
                 (list (poo-flow-temporal-model-observation "cause" "local" 1 "source" 'declared)
                       (poo-flow-temporal-model-observation "effect" "local" 2 "source" 'observed)) (.ref model 'hypotheses) #t))
          (r (request m)) (e (execute r)))
    (check (.ref (verify r e) 'status) => 'pending)
    (check (.ref (admit r e) 'admitted?) => #f)))
  (poo-flow-test-case "a missing required GQL provider cannot be ignored"
   (let* ((r (request model query (poo-flow-candidate-scope "scope" "cut" 1 binding '(ascent gql))))
          (e (execute r)))
    (check (.ref (verify r e) 'missing-providers) => '(gql))
    (check (.ref (admit r e) 'admitted?) => #f)))
  (poo-flow-test-case "native Temporal exploration still gates a valid provider proof"
   (let* ((m (poo-flow-temporal-model "frontier" (.ref model 'domains) (.ref model 'observations)
                 (list (poo-flow-temporal-hypothesis "a" "cause" "effect" '())
                       (poo-flow-temporal-hypothesis "z" "cause" "effect" '())) #t))
          (q (poo-flow-temporal-query "query" "z" 1))
          (b (poo-flow-ascent-source-binding m q "cut" 1))
          (r (request m q (poo-flow-candidate-scope "scope" "cut" 1 b '(ascent))))
          (e (execute r))
          (a (admit r e (poo-flow-temporal-source-attest authority "coverage" 'candidate-source-model-binding b 0 10))))
    (check (.ref (.ref a 'exchange) 'status) => 'reviewable)
    (check (.ref a 'source-verified?) => #t)
    (check (.ref (.ref a 'evaluation) 'classification) => 'unknown)
    (check (.ref a 'admitted?) => #f)))))

;;; Qualification fixture: actual provider check and source authentication gate
;;; the handoff. Keys stay in this test owner and never enter the payload.
(def (main)
 (let* ((r (request)) (e (execute r)) (a (admit r e))
        (evaluation (.ref a 'evaluation)))
  (unless (.ref a 'admitted?) (error "native provider admission failed"))
  (let* ((root (poo-flow-temporal-conclusion-root "root" "subject" "scope" "cut" "projection" "policy" "ascent-generation/1" "necessary" (.ref evaluation 'identity)))
         (journal (poo-flow-temporal-conclusion-journal "journal" (list root)))
         (handoff (poo-flow-temporal-publication journal root model "nonce" 2000000000 evaluation: evaluation))
         (result (make-hash-table)))
   (hash-put! result "publication" (.ref handoff 'wire-payload))
   (hash-put! result "provider_pin" (.ref r 'provider-pin))
   (hash-put! result "binding" (.ref r 'binding-digest))
   (display "ASCENT-HANDOFF ") (write-json (current-output-port) result) (newline) (force-output))))
