;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test (only-in :poo-flow/testing-api poo-flow-test-case)
        :poo-flow/src/ffi/scheme-wire
        :poo-flow/src/ffi/temporal-support :poo-flow/src/ffi/temporal-policy)
(export temporal-support-wire-test)
(def (wire x) (scheme-wire-read (scheme-wire-write x)))
(def (revision id op predecessor n)
  (hash (identity id) (subject "source") (operation op) (predecessor predecessor)
    (admitted n) (validRange (if (equal? op "retract") #f '(0 10)))
    (content (if (equal? op "retract") #f id))))
(def (task n)
  (hash (schema "poo-flow.temporal-support-request.v1")
    (program (hash (identity "named-wire") (policy "named-wire-policy") (complete #t)
      (conclusions '("claim" "child" "empty"))
      (supports (list
        (hash (identity "support") (conclusion "claim") (proof "original")
          (premises (list (hash (subject "source") (revision "r1")))) (parents '()))
        (hash (identity "downstream") (conclusion "child") (proof "original-child")
          (premises '()) (parents '("claim")))))))
    (journal (hash (identity "journal") (admissionDomain "txn") (validDomain "valid")
      (revisions (list (revision "r1" "assert" #f 1) (revision "r2" "retract" "r1" 2)))))
    (asOf n) (validAt #f) (budget 128)))
(def (instant n)
  (hash (identity (number->string n)) (domain "policy-clock") (coordinate n)
    (provenance "host") (modality "observed")))
(def (refresh generation now)
  (temporal-policy-refresh (wire (hash (schema "poo-flow.temporal-policy-refresh-request.v1")
    (policy (hash (identity "named-wire-policy") (revision "v1") (start (instant 1)) (end (instant 3))))
    (generation generation) (effectiveAt (instant now))))))
(def (query registered n expected)
  (wire (hash (schema "poo-flow.temporal-support-claim-request.v1")
    (expectedGeneration (hash-ref registered 'generation))
    (expectedPolicyDigest (hash-ref registered 'policyDigest))
    (task (task n)) (claim "child") (expectedContextBinding expected))))
(def temporal-support-wire-test
  (test-suite "named support wire projection"
    (poo-flow-test-case "reverse projection and Context selection use native owners"
      (let* ((revision (temporal-support-revise-call
                        (wire (hash (schema "poo-flow.temporal-support-revision-request.v1") (task (task 2)) (previousAsOf 1)))))
             (registered (refresh 1 1))
             (first (temporal-policy-claim-call (query registered 1 #f)))
             (stale (temporal-policy-claim-call (query registered 2 (hash-ref first 'bindingDigest)))))
        (check (hash-ref revision 'affectedConclusions) => '("child" "claim"))
        (check (hash-ref revision 'changedSubjects) => '("source"))
        (check (hash-ref first 'status) => "supported")
        (check (hash-ref stale 'contextStatus) => "stale-context")
        (check (hash-ref stale 'status) => "unknown")
        (check (hash-ref (hash-ref stale 'claim) 'status) => "unsupported")
        (check (hash-ref (temporal-policy-claim-call (query registered 1 (hash-ref first 'bindingDigest))) 'bindingDigest)
               => (hash-ref first 'bindingDigest))
        (let* ((latest (refresh 2 3)) (expired (temporal-policy-claim-call (query latest 1 #f))))
          (check (hash-ref expired 'status) => "unknown")
          (check (hash-ref expired 'policyStatus) => "expired-policy")
          (check (hash-ref (hash-ref expired 'claim) 'status) => "supported")
          (check-exception (temporal-policy-claim-call (query registered 1 #f)) true)
          (let (foreign (query latest 1 #f))
            (hash-put! foreign "claim" "foreign")
            (check-exception (temporal-policy-claim-call foreign) true))
          (let (injected (query latest 1 #f))
            (hash-put! injected "effectiveAt" (instant 1))
            (check-exception (temporal-policy-claim-call injected) true)))))))
