;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;;
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Finite positive binary rules. Relations, rules, and results are POO
;;; objects; the evaluation uses the existing indexed relation expression.

(import (only-in :clan/poo/object .o .ref .call)
        (only-in :clan/poo/trie UIntTrieSet)
        (only-in :clan/poo/support/base until))

(export poo-flow-ascent-binary-relation
        poo-flow-ascent-binary-copy-rule
        poo-flow-ascent-binary-join-rule
        poo-flow-ascent-evaluate-binary-program)

(def (poo-flow-ascent-binary-relation relation-name source-set)
  (.o (name relation-name) (pairs source-set)))

(def (poo-flow-ascent-binary-copy-rule head-name body-name)
  (.o (kind 'copy) (head head-name) (left body-name)))

(def (poo-flow-ascent-binary-join-rule head-name left-name right-name)
  (.o (kind 'join) (head head-name)
      (left left-name) (right right-name)))

(def (poo-flow-ascent-evaluate-binary-program program)
  (let* ((width (.ref program 'radix))
         (sources (.ref program 'relations))
         (rules (.ref program 'rules))
         (limit (.ref program 'max-derived-pairs)))
    (unless (and (exact-integer? width) (> width 1)
                 (exact-integer? limit) (> limit 0)
                 (list? sources) (list? rules))
      (error "invalid ASCENT binary program bounds or declarations"))
    ;; These mutable arrays are private to one evaluation. The public boundary
    ;; remains immutable UIntTrieSet snapshots and POO relation objects.
    (let* ((count (length sources))
           (names (make-vector count #f))
           (positions (make-hash-table))
           (all (make-vector count []))
           (delta (make-vector count []))
           (all-index (make-vector count #f))
           (delta-index (make-vector count #f))
           (seen (make-vector count #f))
           (dense? (<= width 512))
           (total 0)
           (position-counter 0))
      (def (new-index)
        (if dense? (make-vector width []) (make-hash-table)))
      (def (index-targets index node)
        (if dense? (vector-ref index node) (or (hash-get index node) [])))
      (def (index-add! index pair)
        (let ((from (quotient pair width)) (to (modulo pair width)))
          (if dense?
            (vector-set! index from (cons to (vector-ref index from)))
            (hash-put! index from (cons to (index-targets index from))))))
      (def (new-seen)
        (if dense? (make-u8vector (* width width) 0) (make-hash-table)))
      (def (seen? storage pair)
        (if dense? (= (u8vector-ref storage pair) 1)
            (hash-get storage pair)))
      (def (mark-seen! storage pair)
        (if dense? (u8vector-set! storage pair 1)
            (hash-put! storage pair #t)))
      (for-each
       (lambda (relation)
         (let* ((name (.ref relation 'name))
                (pairs (.ref relation 'pairs))
                (position position-counter)
                (all-links (new-index))
                (present (new-seen)))
           (unless (and (symbol? name) (not (hash-get positions name)))
             (error "invalid or duplicate ASCENT relation" name))
           (.call UIntTrieSet .foldl
                  (lambda (pair _)
                    (unless (and (exact-integer? pair) (<= 0 pair)
                                 (< pair (* width width)))
                      (error "invalid ASCENT binary pair" pair))
                    (mark-seen! present pair)
                    (index-add! all-links pair)
                    (vector-set! all position
                                 (cons pair (vector-ref all position)))
                    (set! total (+ total 1)))
                  (void) pairs)
           (vector-set! names position name)
           (hash-put! positions name (+ position 1))
           (set! position-counter (+ position-counter 1))
           (vector-set! seen position present)
           (vector-set! all-index position all-links)
           (vector-set! delta position (vector-ref all position))
           (vector-set! delta-index position all-links)))
       sources)
      (def (position-of name)
        (let (slot (hash-get positions name))
          (unless slot (error "unknown ASCENT relation" name))
          (- slot 1)))
      (def compiled
        (map (lambda (rule)
               (let (kind (.ref rule 'kind))
                 (unless (memq kind '(copy join))
                   (error "invalid ASCENT binary rule" kind))
                 (list kind
                       (position-of (.ref rule 'head))
                       (position-of (.ref rule 'left))
                       (and (eq? kind 'join)
                            (position-of (.ref rule 'right))))))
             rules))
      (when (> total limit)
        (error "ASCENT derived pair budget exceeded" limit))
      (let (active? #t)
        (until (not active?)
          (let ((pending (make-vector count []))
                (next (make-vector count []))
                (next-index (make-vector count #f)))
            (let initialize ((i 0))
              (when (< i count)
                (vector-set! next-index i (new-index))
                (initialize (+ i 1))))
            (def (emit! head pair)
              (vector-set! pending head (cons pair (vector-ref pending head))))
            (def (compose! head left-pairs right-index)
              (for-each
               (lambda (pair)
                 (let ((origin (quotient pair width))
                       (middle (modulo pair width)))
                   (for-each
                    (lambda (target)
                      (emit! head (+ (* origin width) target)))
                    (index-targets right-index middle))))
               left-pairs))
            (for-each
             (lambda (rule)
               (let ((kind (car rule)) (head (cadr rule))
                     (left (caddr rule)) (right (cadddr rule)))
                 (if (eq? kind 'copy)
                   (for-each (lambda (pair) (emit! head pair))
                             (vector-ref delta left))
                   (begin
                     (unless (null? (vector-ref delta left))
                       (compose! head (vector-ref delta left)
                                 (vector-ref all-index right)))
                     (unless (null? (vector-ref delta right))
                       (compose! head (vector-ref all left)
                                 (vector-ref delta-index right)))))))
             compiled)
            (set! active? #f)
            (let commit ((i 0))
              (when (< i count)
                (for-each
                 (lambda (pair)
                   (unless (seen? (vector-ref seen i) pair)
                     (mark-seen! (vector-ref seen i) pair)
                     (set! active? #t)
                     (set! total (+ total 1))
                     (when (> total limit)
                       (error "ASCENT derived pair budget exceeded" limit))
                     (vector-set! all i (cons pair (vector-ref all i)))
                     (vector-set! next i (cons pair (vector-ref next i)))
                     (index-add! (vector-ref all-index i) pair)
                     (index-add! (vector-ref next-index i) pair)))
                 (vector-ref pending i))
                (commit (+ i 1))))
            (set! delta next)
            (set! delta-index next-index))))
      (let (results (make-vector count #f))
        (let publish ((i 0))
          (when (< i count)
            (vector-set! results i
                         (.call UIntTrieSet .<-list (vector-ref all i)))
            (publish (+ i 1))))
      (.o (relation-names (vector->list names))
          (pairs-of
           (lambda (name)
             (vector-ref results (position-of name)))))))))
