;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Inert declarations project to the native Library; no registry or grant IO.
(import (only-in :std/list/list every)
        (only-in :clan/poo/object .ref)
        :poo-flow/src/semantic/context-restriction)
(export context-restriction-compose-call context-flow-evaluate-call)
(def (field x key)
  (unless (and (hash-table? x) (hash-key? x key)) (error "missing Context field" key))
  (hash-ref x key))
(def (fields x keys)
  (unless (and (hash-table? x) (= (hash-length x) (length keys))
               (every (lambda (key) (hash-key? x key)) keys))
    (error "unexpected Context fields")))
(def (declaration x)
  (fields x '("schema" "domain" "readers" "destinations" "provenance" "leaseStart" "leaseEnd"))
  (unless (equal? (field x "schema") "poo-flow.context-restriction.v1")
    (error "unsupported Context restriction schema"))
  (poo-flow-context-restriction (field x "domain") (field x "readers")
    (field x "destinations") (field x "provenance") (field x "leaseStart") (field x "leaseEnd")))
(def (compose xs)
  (unless (and (list? xs) (<= 1 (length xs) 32)) (error "Context composition bound"))
  (poo-flow-context-restriction-compose (map declaration xs)))
(def (wire-label x)
  (hash (schema "poo-flow.context-restriction.v1") (domain (.ref x 'domain))
    (readers (.ref x 'readers)) (destinations (.ref x 'destinations))
    (provenance (.ref x 'provenance)) (leaseStart (.ref x 'lease-start)) (leaseEnd (.ref x 'lease-end))))
(def (context-restriction-compose-call x)
  (fields x '("schema" "restrictions"))
  (unless (equal? (field x "schema") "poo-flow.context-restriction-compose-request.v1")
    (error "unsupported Context composition schema"))
  (let (value (compose (field x "restrictions")))
    (hash (schema "poo-flow.context-restriction-compose-result.v1") (abiVersion 1)
      (restriction (wire-label value)) (bindingDigest (.ref value 'semantic-digest))
      (trustBasis "declared-context-restrictions")
      (sourceAuthenticated #f) (flowAdmitted #f) (actionAuthorized #f) (durable #f))))
(def (context-flow-evaluate-call x)
  (fields x '("schema" "restrictions" "expectedRestrictionDigest" "sourceDigest" "contentDigest"
              "principal" "destination" "declaredAt"))
  (unless (equal? (field x "schema") "poo-flow.context-flow-request.v1")
    (error "unsupported Context flow schema"))
  (let* ((label (compose (field x "restrictions"))) (expected (field x "expectedRestrictionDigest")))
    (unless (or (eq? expected #f) (equal? expected (.ref label 'semantic-digest)))
      (error "Context restriction binding mismatch"))
    (let (value (poo-flow-context-flow-decision-replay
                 (poo-flow-context-flow-decision label (field x "sourceDigest") (field x "contentDigest")
                   (field x "principal") (field x "destination") (field x "declaredAt"))))
      (hash (schema "poo-flow.context-flow-result.v1") (abiVersion 1)
        (bindingDigest (.ref value 'semantic-digest))
        (restrictionDigest (.ref label 'semantic-digest)) (restriction (wire-label label))
        (sourceDigest (.ref value 'source-digest)) (contentDigest (.ref value 'content-digest))
        (principal (.ref value 'principal)) (destination (.ref value 'destination))
        (declaredAt (.ref value 'effective-at)) (status (symbol->string (.ref value 'status)))
        (trustBasis "declared-context-restrictions-and-coordinate")
        (sourceAuthenticated #f) (flowAdmitted #f) (actionAuthorized #f) (durable #f)))))
