;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Strict inert projection into POO-owned Host values; no query-controlled state.
(import (only-in :clan/poo/object .ref)
        :poo-flow/modules/memory-core/context-use-host
        (only-in :poo-flow/src/ffi/temporal-policy temporal-policy-native-host)
        (only-in :poo-flow/modules/temporal-causality/truth-maintenance/support/policy-host
                 poo-flow-temporal-support-policy-host-current)
        (only-in :poo-flow/src/ffi/temporal-admission temporal-family-current-call))
(export context-use-refresh context-use-observe)
(def host (poo-flow-context-use-host))
(def (field x key)
  (unless (and (hash-table? x) (hash-key? x key)) (error "missing Context use field" key)) (hash-ref x key))
(def (fields x names)
  (unless (and (hash-table? x) (= (hash-length x) (length names))) (error "unexpected Context use fields"))
  (for-each (lambda (name) (field x name)) names))
(def (contract x)
  (fields x ["actor" "task" "policyDigest" "required" "temporalReceipts" "requireComplete"])
  (poo-flow-context-use-contract (field x "actor") (field x "task") (field x "policyDigest")
    (field x "required") (field x "temporalReceipts") (field x "requireComplete")))
(def (wire-contract x)
  (hash (actor (.ref x 'actor)) (task (.ref x 'task)) (policyDigest (.ref x 'policy-digest))
        (required (.ref x 'required)) (temporalReceipts (.ref x 'temporal-receipts))
        (requireComplete (.ref x 'require-complete?))))
(def (purpose x)
  (cond ((equal? x "display") 'display) ((equal? x "action") 'action)
        (else (error "unsupported Context use purpose"))))
(def (context-use-refresh x)
  (fields x ["schema" "identity" "generation" "manifestDigest" "admissionDigest" "contract"
             "policyIdentity" "policyDigest" "purposes" "enabled"])
  (unless (equal? (field x "schema") "poo-flow.context-use-refresh-request.v1")
    (error "unsupported Context use refresh schema"))
  (unless (list? (field x "purposes")) (error "Context purposes must be a list"))
  (let* ((grant (poo-flow-context-use-grant (field x "identity") (field x "generation")
                 (field x "manifestDigest") (field x "admissionDigest") (contract (field x "contract"))
                 (field x "policyIdentity") (field x "policyDigest")
                 (map purpose (field x "purposes")) (field x "enabled")))
         (current (temporal-family-current-call (hash ("admissionDigest" (.ref grant 'admission-digest))))))
    (unless (or (not (.ref grant 'enabled?)) (equal? (hash-ref current 'status) "current")) (error "Context grant requires current native source"))
    ;; Validate every registration before mutation, including the policy identity.
    (poo-flow-temporal-support-policy-host-current (temporal-policy-native-host) (.ref grant 'policy-identity))
    (poo-flow-context-use-host-refresh! host grant)
    (hash (schema "poo-flow.context-use-refresh-result.v1") (abiVersion 1)
          (identity (.ref grant 'identity)) (generation (.ref grant 'generation))
          (grantDigest (.ref grant 'semantic-digest)) (enabled (.ref grant 'enabled?))
          (actionAuthorized #f) (durable #f))))
(def (context-use-observe x)
  (fields x ["schema" "identity" "expectedGeneration" "purpose" "admissionDigest"])
  (unless (equal? (field x "schema") "poo-flow.context-use-observe-request.v1")
    (error "unsupported Context use observe schema"))
  (let* ((observed (poo-flow-context-use-host-observe host (temporal-policy-native-host)
                    (field x "identity") (field x "expectedGeneration") (purpose (field x "purpose"))))
         (grant (.ref observed 'grant))
         (_ (unless (equal? (field x "admissionDigest") (.ref grant 'admission-digest))
              (error "foreign Context native admission")))
         (current (temporal-family-current-call (hash ("admissionDigest" (.ref grant 'admission-digest)))))
         (snapshot (.ref observed 'policy-snapshot)))
    (hash (schema "poo-flow.context-use-observation.v1") (abiVersion 1)
          (identity (.ref grant 'identity)) (generation (.ref grant 'generation))
          (manifestDigest (.ref grant 'manifest-digest)) (purpose (symbol->string (.ref observed 'purpose)))
          (contract (wire-contract (.ref grant 'contract)))
          (decision (if (equal? (hash-ref current 'status) "current")
                      (symbol->string (.ref observed 'decision)) "denied"))
          (currentSource current) (policyStatus (symbol->string (.ref observed 'policy-status)))
          (policyGeneration (.ref snapshot 'generation))
          (effectiveCoordinate (.ref (.ref snapshot 'effective-at) 'coordinate))
          (trustBasis "host-registered-contract-source-policy-and-clock")
          (sourceAuthenticated #f) (actionAuthorized #f) (durable #f))))
