;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Effectful host registration is separate from pure semantic admission.
(import (only-in :clan/poo/object .ref)
        (only-in :poo-flow/src/ffi/temporal-family temporal-family-values)
        (only-in :poo-flow/modules/temporal-causality/admission/interface
                 poo-flow-temporal-source-snapshot poo-flow-temporal-family-admit)
        (only-in :poo-flow/modules/temporal-causality/applicability/funs
                 poo-flow-temporal-family-applicability)
        (only-in :poo-flow/modules/temporal-causality/lifecycle/interface
                 poo-flow-temporal-family-revision-root
                 poo-flow-temporal-family-revision-change
                 poo-flow-temporal-family-revision-replay
                 poo-flow-temporal-family-revision-journal)
        (only-in :poo-flow/modules/temporal-causality/truth-maintenance/objects
                 poo-flow-temporal-invalidation-plan-value))
(export temporal-source-register temporal-family-admit-call temporal-family-current-call
        temporal-family-revision-root-call temporal-family-revision-change-call
        temporal-family-journal-call temporal-family-revisions temporal-journal-receipt
        temporal-frontier-value temporal-revision-receipt)
(def sources (make-hash-table))
(def admissions (make-hash-table))
(def revisions (make-hash-table))
(def (field object key)
  (unless (and (hash-table? object) (hash-key? object key))
    (error "missing admission field" key))
  (hash-ref object key))
(def (fields object names)
  (unless (and (hash-table? object) (= (hash-length object) (length names)))
    (error "invalid admission fields"))
  (for-each (lambda (key) (field object key)) names))
(def scope-fields ["identity" "authority" "subject" "scope" "cut" "projection" "policy" "generation"])
(def (snapshot object)
  (let* ((scope (field object "scope"))
         (values (temporal-family-values (field object "task"))))
    (fields scope scope-fields)
    (apply poo-flow-temporal-source-snapshot
           (append (map (lambda (key) (field scope key)) scope-fields)
                   (list (car values))))))

;;; Called ONLY through the dedicated C control entrypoint. No semantic byte
;;; operation can replace the registered snapshot or choose its digest.
(def (temporal-source-register object)
  (fields object ["scope" "task"])
  (let* ((source (snapshot object)) (id (.ref source 'identity))
         (old (hash-get sources id)))
    (when old
      (unless (or (> (.ref source 'generation) (.ref old 'generation))
                  (equal? (.ref source 'semantic-digest) (.ref old 'semantic-digest)))
        (error "source generation rollback or conflicting registration")))
    (unless (or old (< (hash-length sources) 128))
      (error "source registry capacity exceeded"))
    (hash-put! sources id source)
    (hash (schema "poo-flow.temporal-source-registration.v1")
          (sourceDigest (.ref source 'semantic-digest))
          (generation (.ref source 'generation))
          (trustBasis "host-registered-snapshot") (sourceAuthenticated #f)
          (actionAuthorized #f))))

(def (temporal-family-admit-call object)
  (fields object ["sourceIdentity" "sourceDigest" "task" "conclusionIdentity"])
  (let* ((source (hash-get sources (field object "sourceIdentity")))
         (_ (unless (and source (equal? (.ref source 'semantic-digest)
                                       (field object "sourceDigest")))
              (error "unregistered or stale source snapshot")))
         (values (temporal-family-values (field object "task")))
         (admission (poo-flow-temporal-family-admit
                     (car values) (cadr values) source (field object "conclusionIdentity")))
         (revision (.ref admission 'conclusion)))
    (let (id (.ref admission 'semantic-digest))
      (unless (or (hash-key? admissions id) (< (hash-length admissions) 128))
        (error "admission history capacity exceeded"))
      (hash-put! admissions id admission))
    (hash (schema "poo-flow.temporal-family-admission.v1")
          (claim "family-relative-classification")
          (trustBasis "host-registered-snapshot") (sourceVerified #t)
          (sourceAuthenticated #f) (actionAuthorized #f)
          (admissionDigest (.ref admission 'semantic-digest))
          (sourceDigest (.ref admission 'source-digest))
          (modelDigest (.ref admission 'model-digest))
          (classification (symbol->string (.ref admission 'classification)))
          (conclusion
           (hash (identity (.ref revision 'identity))
                 (subject (.ref revision 'subject-identity))
                 (scope (.ref revision 'scope-identity))
                 (cut (.ref revision 'cut-digest))
                 (projection (.ref revision 'projection-digest))
                 (policy (.ref revision 'policy-identity))
                 (generation (.ref revision 'generation-identity))
                 (operation "assert") (proofDigest (.ref revision 'proof-identity))
                 (resultDigest (.ref revision 'result-identity)))))))

;;; The registry selects current source state on the owner thread. Payloads
;;; cannot supply a replacement current digest or rewrite historical proofs.
(def (temporal-family-current-call object)
  (fields object ["admissionDigest"])
  (let* ((admission (hash-get admissions (field object "admissionDigest")))
         (_ (unless admission (error "unknown historical family admission")))
         (source (hash-get sources (.ref (.ref admission 'source) 'identity)))
         (applicability (poo-flow-temporal-family-applicability admission source)))
    (hash (schema "poo-flow.temporal-family-applicability.v1")
          (admissionDigest (.ref applicability 'admission-digest))
          (originalSourceDigest (.ref applicability 'original-source-digest))
          (currentSourceDigest (.ref applicability 'current-source-digest))
          (status (symbol->string (.ref applicability 'status)))
          (trustBasis "host-registered-snapshot")
          (sourceAuthenticated #f) (actionAuthorized #f))))

;;; In-process immutable handles only. No journal persistence/current-pointer CAS.
(def (known table id)
  (or (hash-get table id) (error "unknown native history handle")))
(def (bounded-text? value)
  (and (string? value) (< 0 (string-length value) 129)))
(def (bounded-identities? values)
  (and (list? values) (<= (length values) 128)
       (andmap bounded-text? values)))
(def (revision-wire revision)
  (hash (identity (.ref revision 'identity))
        (subject (.ref revision 'subject-identity)) (scope (.ref revision 'scope-identity))
        (cut (.ref revision 'cut-digest)) (projection (.ref revision 'projection-digest))
        (policy (.ref revision 'policy-identity)) (generation (.ref revision 'generation-identity))
        (operation (symbol->string (.ref revision 'operation)))
        (predecessor (.ref revision 'predecessor-identity))
        (proofDigest (.ref revision 'proof-identity)) (resultDigest (.ref revision 'result-identity))
        (invalidationIndexDigest (.ref revision 'invalidation-index-digest))))
(def (retain-revision value)
  (let* ((canonical (poo-flow-temporal-family-revision-replay value))
         (id (.ref canonical 'semantic-digest)))
    (unless (or (hash-key? revisions id) (< (hash-length revisions) 128))
      (error "revision history capacity exceeded"))
    (hash-put! revisions id canonical)
    (temporal-revision-receipt canonical)))
(def (temporal-revision-receipt canonical)
  (hash (schema "poo-flow.temporal-family-revision.v1")
        (revisionDigest (.ref canonical 'semantic-digest))
        (admissionDigest (.ref (.ref canonical 'admission) 'semantic-digest))
        (classification (symbol->string (.ref (.ref canonical 'admission) 'classification)))
        (revision (revision-wire (.ref canonical 'revision)))
        (sourceAuthenticated #f) (runtimeExecuted #f) (actionAuthorized #f)
        (durable #f)))
(def (temporal-family-revision-root-call object)
  (fields object ["admissionDigest"])
  (retain-revision (poo-flow-temporal-family-revision-root
                    (known admissions (field object "admissionDigest")))))
(def (temporal-frontier-value frontier)
  (fields frontier ["indexIdentity" "indexDigest" "previousCut" "revisedCut"
                    "previousProjection" "revisedProjection" "changedSubjects"
                    "affectedConclusions" "inventoryComplete" "trigger"])
  (unless (and (andmap (lambda (key) (bounded-text? (field frontier key)))
                      ["indexIdentity" "indexDigest" "previousCut" "revisedCut"
                       "previousProjection" "revisedProjection"])
               (bounded-identities? (field frontier "changedSubjects"))
               (bounded-identities? (field frontier "affectedConclusions")))
    (error "frontier identity bounds rejected"))
  (let (trigger (field frontier "trigger"))
    (unless (member trigger '("premise-delta" "valid-time-reprojection"))
      (error "invalid frontier trigger"))
    (poo-flow-temporal-invalidation-plan-value
     (field frontier "indexIdentity") (field frontier "indexDigest")
     (field frontier "previousCut") (field frontier "revisedCut")
     (field frontier "previousProjection") (field frontier "revisedProjection")
     (field frontier "changedSubjects") (field frontier "affectedConclusions")
     (field frontier "inventoryComplete") (string->symbol trigger))))
(def (temporal-family-revision-change-call object)
  (fields object ["previousDigest" "admissionDigest" "operation" "frontier"])
  (let (operation (field object "operation"))
    (unless (member operation '("correct" "retract")) (error "invalid revision operation"))
    (retain-revision
     (poo-flow-temporal-family-revision-change
      (known revisions (field object "previousDigest"))
      (known admissions (field object "admissionDigest"))
      (temporal-frontier-value (field object "frontier")) (string->symbol operation)))))
(def (temporal-family-revisions ids)
  (unless (and (bounded-identities? ids) (pair? ids)) (error "journal inventory bound"))
  (map (lambda (id) (known revisions id)) ids))
(def (temporal-journal-receipt identity values)
  (let (journal (poo-flow-temporal-family-revision-journal identity values))
    (hash (schema "poo-flow.temporal-family-journal.v1")
          (identity (.ref journal 'identity)) (journalDigest (.ref journal 'semantic-digest))
          (revisions (map revision-wire (.ref journal 'revisions)))
          (entries (map (lambda (value) (temporal-revision-receipt
                         (poo-flow-temporal-family-revision-replay value))) values))
          (sourceAuthenticated #f) (runtimeExecuted #f) (actionAuthorized #f) (durable #f))))
(def (temporal-family-journal-call object)
  (fields object ["identity" "revisionDigests"])
  (unless (bounded-text? (field object "identity")) (error "journal identity bound"))
  (temporal-journal-receipt (field object "identity")
                          (temporal-family-revisions (field object "revisionDigests"))))
