;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Full Family premise projection/replay. No current Source or handle mutation.
(import (only-in :clan/poo/object .ref)
        (only-in :poo-flow/src/ffi/scheme-wire scheme-wire-write)
        (only-in :poo-flow/src/ffi/temporal-family temporal-family-values temporal-family-task)
        (only-in :poo-flow/src/ffi/temporal-admission
                 temporal-family-revisions temporal-journal-receipt
                 temporal-frontier-value temporal-revision-receipt)
        (only-in :poo-flow/modules/temporal-causality/admission/interface
                 poo-flow-temporal-source-snapshot poo-flow-temporal-family-admit)
        (only-in :poo-flow/modules/temporal-causality/lifecycle/interface
                 poo-flow-temporal-family-archive poo-flow-temporal-family-revision-root
                 poo-flow-temporal-family-revision-change))
(export temporal-family-archive-export-call temporal-family-archive-replay-call)
(def (field object key)
  (unless (and (hash-table? object) (hash-key? object key)) (error "missing archive field" key))
  (hash-ref object key))
(def (fields object keys)
  (unless (and (hash-table? object) (= (hash-length object) (length keys)))
    (error "invalid archive fields"))
  (for-each (lambda (key) (field object key)) keys))
(def (text? value) (and (string? value) (< 0 (string-length value) 129)))
(def scope-fields '(identity authority-identity subject-identity scope-identity
                    cut-digest projection-digest policy-identity generation))
(def scope-keys ["identity" "authority" "subject" "scope" "cut" "projection" "policy" "generation"])
(def (scope-wire source)
  (let (result (make-hash-table))
    (for-each (lambda (key slot) (hash-put! result key (.ref source slot))) scope-keys scope-fields)
    result))
(def (frontier-wire value)
  (hash (indexIdentity (.ref value 'index-identity)) (indexDigest (.ref value 'index-digest))
        (previousCut (.ref value 'previous-cut-digest)) (revisedCut (.ref value 'revised-cut-digest))
        (previousProjection (.ref value 'previous-projection-digest))
        (revisedProjection (.ref value 'revised-projection-digest))
        (changedSubjects (.ref value 'changed-subject-identities))
        (affectedConclusions (.ref value 'affected-conclusion-identities))
        (inventoryComplete (.ref value 'inventory-complete?))
        (trigger (symbol->string (.ref value 'trigger)))))
(def (entry-wire value)
  (let* ((admission (.ref value 'admission)) (source (.ref admission 'source))
         (query (.ref admission 'query)))
    (hash (revisionDigest (.ref value 'semantic-digest))
          (admissionDigest (.ref admission 'semantic-digest))
          (conclusionIdentity (.ref admission 'conclusion-identity))
          (task (temporal-family-task (.ref admission 'model) query))
          (source (hash (scope (scope-wire source))
                        (task (temporal-family-task (.ref source 'model) query))))
          (predecessorDigest (and (.ref value 'predecessor)
                                 (.ref (.ref value 'predecessor) 'semantic-digest)))
          (operation (symbol->string (.ref (.ref value 'revision) 'operation)))
          (frontier (and (.ref value 'frontier) (frontier-wire (.ref value 'frontier))))
          (revision (hash-get (temporal-revision-receipt value) 'revision)))))
(def (temporal-family-archive-export-call object)
  (fields object ["identity" "revisionDigests"])
  (let* ((archive (poo-flow-temporal-family-archive (field object "identity")
                    (temporal-family-revisions (field object "revisionDigests"))))
         (value (hash (schema "poo-flow.temporal-family-proof-archive.v1")
                 (identity (.ref archive 'identity)) (archiveDigest (.ref archive 'semantic-digest))
                 (journalDigest (.ref (.ref archive 'journal) 'semantic-digest))
                 (entries (map entry-wire (.ref archive 'family-revisions)))))
         (request (hash (archive value) (expectedDigest (.ref archive 'semantic-digest)))))
    ;; Every exported archive must fit a subsequent exact ABI replay request.
    (when (> (u8vector-length (string->utf8 (scheme-wire-write request))) 1048576)
      (error "archive replay byte bound exceeded"))
    value))
(def (temporal-family-archive-replay-call object)
  (fields object ["archive" "expectedDigest"])
  (let* ((payload (field object "archive")) (expected (field object "expectedDigest"))
         (pending (make-hash-table)) (resolved (make-hash-table)))
    (fields payload ["schema" "identity" "archiveDigest" "journalDigest" "entries"])
    (unless (and (equal? (field payload "schema") "poo-flow.temporal-family-proof-archive.v1")
                 (text? expected) (equal? expected (field payload "archiveDigest"))
                 (list? (field payload "entries")) (<= 1 (length (field payload "entries")) 128))
      (error "archive schema, trusted digest or inventory differs"))
    (for-each (lambda (entry)
      (fields entry ["revisionDigest" "admissionDigest" "conclusionIdentity" "task" "source"
                     "predecessorDigest" "operation" "frontier" "revision"])
      (let (id (field entry "revisionDigest"))
        (unless (and (text? id) (not (hash-key? pending id))) (error "duplicate archive revision"))
        (hash-put! pending id entry))) (field payload "entries"))
    (def (resolve id ancestors)
      (when (member id ancestors) (error "cyclic archive predecessor"))
      (or (hash-get resolved id)
          (let* ((entry (or (hash-get pending id) (error "missing archive predecessor")))
                 (source-payload (field entry "source"))
                 (_ (fields source-payload ["scope" "task"]))
                 (scope (field source-payload "scope"))
                 (_ (fields scope scope-keys))
                 (source-values (temporal-family-values (field source-payload "task")))
                 (source (apply poo-flow-temporal-source-snapshot
                          (append (map (lambda (key) (field scope key)) scope-keys)
                                  (list (car source-values)))))
                 (values (temporal-family-values (field entry "task")))
                 (_ (unless (equal?
                      (scheme-wire-write (field (field source-payload "task") "query"))
                      (scheme-wire-write (field (field entry "task") "query")))
                      (error "source task query differs from admission query")))
                 (admission (poo-flow-temporal-family-admit (car values) (cadr values) source
                             (field entry "conclusionIdentity")))
                 (operation (field entry "operation"))
                 (previous (field entry "predecessorDigest"))
                 (value (cond
                   ((equal? operation "assert")
                    (unless (and (eq? previous #f) (eq? (field entry "frontier") #f))
                      (error "archive root has a predecessor or frontier"))
                    (poo-flow-temporal-family-revision-root admission))
                   ((member operation '("correct" "retract"))
                    (unless (text? previous) (error "archive predecessor identity bound"))
                    (poo-flow-temporal-family-revision-change
                     (resolve previous (cons id ancestors)) admission
                     (temporal-frontier-value (field entry "frontier")) (string->symbol operation)))
                   (else (error "invalid archive revision operation")))))
            (unless (and (equal? (.ref admission 'semantic-digest) (field entry "admissionDigest"))
                         (equal? (.ref value 'semantic-digest) id)
                         (equal? (scheme-wire-write (hash-get (temporal-revision-receipt value) 'revision))
                                 (scheme-wire-write (field entry "revision"))))
              (error "archive proof or revision differs from replayed premises"))
            (hash-put! resolved id value) value)))
    (let* ((values (map (lambda (entry) (resolve (field entry "revisionDigest") '()))
                       (field payload "entries")))
           (archive (poo-flow-temporal-family-archive (field payload "identity") values)))
      (unless (and (equal? (.ref archive 'semantic-digest) expected)
                   (equal? (.ref (.ref archive 'journal) 'semantic-digest) (field payload "journalDigest")))
        (error "archive graph digest mismatch"))
      (hash (schema "poo-flow.temporal-family-proof-replay.v1")
            (archiveDigest (.ref archive 'semantic-digest))
            (journal (temporal-journal-receipt (.ref archive 'identity) (.ref archive 'family-revisions)))
            (currentSourceSelected #f) (handlesRestored #f) (sourceAuthenticated #f)
            (actionAuthorized #f) (runtimeExecuted #f) (durable #f)))))
