;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Strict owner wire projections of the native Library proof Host.
(import (only-in :clan/poo/object .ref)
        :poo-flow/modules/temporal-causality/evaluator/proof-host
        (only-in :poo-flow/src/ffi/temporal-policy temporal-policy-proof-host)
        (only-in :poo-flow/src/ffi/temporal-proof temporal-derivation-context-input temporal-rule-program-input)
        (only-in :poo-flow/src/ffi/temporal-support temporal-support-journal-input temporal-support-result))
(export temporal-proof-state-refresh temporal-proof-register temporal-proof-current)
(def host (temporal-policy-proof-host))
(def (field x k)
  (unless (and (hash-table? x) (hash-key? x k)) (error "missing proof host field" k)) (hash-ref x k))
(def (request x schema keys)
  (unless (and (hash-table? x) (= (hash-length x) (length keys))) (error "unexpected proof host fields"))
  (for-each (lambda (k) (field x k)) keys)
  (unless (equal? (field x "schema") schema) (error "unsupported proof host schema")))
(def (temporal-proof-state-refresh x)
  (request x "poo-flow.temporal-proof-state-refresh-request.v1" ["schema" "identity" "generation" "program" "journal"])
  (let (v (poo-flow-temporal-proof-host-refresh! host (field x "identity") (field x "generation")
             (temporal-rule-program-input (field x "program")) (temporal-support-journal-input (field x "journal"))))
    (hash (schema "poo-flow.temporal-proof-state-refresh-result.v1") (abiVersion 1)
          (identity (.ref v 'identity)) (generation (.ref v 'generation)) (stateDigest (.ref v 'semantic-digest))
          (trustBasis "host-registered-catalog-journal")
          (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f))))
(def (temporal-proof-register x)
  (request x "poo-flow.temporal-proof-register-request.v1"
    ["schema" "stateIdentity" "expectedStateDigest" "policyIdentity" "task"])
  (let* ((inputs (temporal-derivation-context-input (field x "task")))
         (v (poo-flow-temporal-proof-host-register! host (field x "stateIdentity") (field x "expectedStateDigest")
              (list-ref inputs 2) (field x "policyIdentity"))))
    (hash (schema "poo-flow.temporal-proof-register-result.v1") (abiVersion 1)
          (registration (.ref v 'identity)) (proofDigest (.ref v 'proof-digest))
          (originalStateDigest (.ref v 'original-state-digest)) (proofAdmitted (.ref v 'proof-admitted?))
          (trustBasis "host-registered-source-relative-native-proof")
          (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f))))
(def (temporal-proof-current x)
  (request x "poo-flow.temporal-proof-current-request.v1"
    ["schema" "registration" "expectedStateGeneration" "expectedPolicyGeneration" "expectedPolicyDigest" "budget"])
  (let* ((v (poo-flow-temporal-proof-host-current host (field x "registration") (field x "expectedStateGeneration")
               (field x "expectedPolicyGeneration") (field x "expectedPolicyDigest") (field x "budget")))
         (g (.ref v 'guard)) (now (.ref g 'effective-at)))
    (hash (schema "poo-flow.temporal-proof-current-result.v1") (abiVersion 1)
          (registration (.ref v 'registration)) (bindingDigest (.ref v 'semantic-digest))
          (proofDigest (.ref v 'proof-digest)) (originalStateDigest (.ref v 'original-state-digest))
          (currentStateDigest (.ref v 'current-state-digest)) (stateGeneration (.ref v 'state-generation))
          (policyGeneration (field x "expectedPolicyGeneration")) (policyDigest (.ref g 'policy-digest))
          (effectiveAt (hash (identity (.ref now 'identity)) (domain (.ref now 'domain-identity))
            (coordinate (.ref now 'coordinate)) (provenance (.ref now 'provenance-identity)) (modality "observed")))
          (evaluation (temporal-support-result (.ref g 'evaluation)))
          (status (symbol->string (.ref v 'status))) (current (.ref v 'current?)) (proofAdmitted (.ref v 'proof-admitted?))
          (trustBasis "host-registered-source-relative-native-proof")
          (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f))))
