;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Dedicated host control state; ordinary queries supply neither policy nor clock.
(import (only-in :clan/poo/object .ref)
        (only-in :poo-flow/modules/temporal-causality/time/objects poo-flow-temporal-instant)
        (only-in :poo-flow/modules/temporal-causality/truth-maintenance/support/policy poo-flow-temporal-support-policy poo-flow-temporal-support-claim)
        :poo-flow/modules/temporal-causality/truth-maintenance/support/policy-host
        (only-in :poo-flow/src/ffi/temporal-support temporal-support-input temporal-support-result))
(export temporal-policy-refresh temporal-policy-guard-call temporal-policy-native-host temporal-policy-claim-call)
(def (temporal-policy-native-host) host)
(def host (poo-flow-temporal-support-policy-host))
(def (field x key)
  (unless (and (hash-table? x) (hash-key? x key)) (error "missing policy field" key)) (hash-ref x key))
(def (fields x names)
  (unless (and (hash-table? x) (= (hash-length x) (length names))) (error "unexpected policy fields"))
  (for-each (lambda (name) (field x name)) names))
(def (instant x)
  (fields x ["identity" "domain" "coordinate" "provenance" "modality"])
  (unless (and (equal? (field x "modality") "observed") (exact-integer? (field x "coordinate")))
    (error "host policy requires observed integer instant"))
  (poo-flow-temporal-instant (field x "identity") (field x "domain") (field x "coordinate") (field x "provenance") 'observed))
(def (wire-instant x)
  (hash (identity (.ref x 'identity)) (domain (.ref x 'domain-identity)) (coordinate (.ref x 'coordinate))
        (provenance (.ref x 'provenance-identity)) (modality (symbol->string (.ref x 'modality)))))
(def (temporal-policy-refresh x)
  (fields x ["schema" "policy" "generation" "effectiveAt"])
  (unless (equal? (field x "schema") "poo-flow.temporal-policy-refresh-request.v1") (error "unsupported host policy schema"))
  (let (p (field x "policy"))
    (fields p ["identity" "revision" "start" "end"])
    (let* ((policy-value (poo-flow-temporal-support-policy (field p "identity") (field p "revision")
                           (instant (field p "start")) (instant (field p "end"))))
           (snapshot (poo-flow-temporal-support-policy-host-refresh! host policy-value (field x "generation") (instant (field x "effectiveAt")))))
      (hash (schema "poo-flow.temporal-policy-refresh-result.v1") (abiVersion 1)
            (policyIdentity (.ref policy-value 'identity)) (policyDigest (.ref policy-value 'semantic-digest))
            (generation (.ref snapshot 'generation)) (effectiveAt (wire-instant (.ref snapshot 'effective-at)))
            (trustBasis "host-registered-policy-snapshot")
            (proofAdmitted #f) (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f)))))
(def (guard-value x)
  (fields x ["schema" "expectedGeneration" "expectedPolicyDigest" "task"])
  (unless (equal? (field x "schema") "poo-flow.temporal-support-guard-request.v1") (error "unsupported host guard schema"))
  (apply poo-flow-temporal-support-policy-host-guard
    host (field x "expectedGeneration") (field x "expectedPolicyDigest")
    (temporal-support-input (field x "task"))))
(def (wire-guard result)
  (hash (schema "poo-flow.temporal-support-guard-result.v1") (abiVersion 1)
    (bindingDigest (.ref result 'semantic-digest)) (policyDigest (.ref result 'policy-digest))
    (expectedPolicyDigest (.ref result 'expected-policy-digest))
    (policyStatus (symbol->string (.ref result 'policy-status))) (policyApplicable (.ref result 'policy-applicable?))
    (effectiveAt (wire-instant (.ref result 'effective-at)))
    (evaluation (temporal-support-result (.ref result 'evaluation)))
    (proofAdmitted #f) (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f)))
(def (temporal-policy-guard-call x) (wire-guard (guard-value x)))

;;; Selection is relative to the supplied journal cut and named inventory, with
;;; policy/clock authority exclusively taken from the existing host registry.
(def (temporal-policy-claim-call x)
  (fields x ["schema" "expectedGeneration" "expectedPolicyDigest" "task" "claim" "expectedContextBinding"])
  (unless (equal? (field x "schema") "poo-flow.temporal-support-claim-request.v1")
    (error "unsupported support claim schema"))
  (let* ((guard (guard-value
           (hash ("schema" "poo-flow.temporal-support-guard-request.v1")
             ("expectedGeneration" (field x "expectedGeneration"))
             ("expectedPolicyDigest" (field x "expectedPolicyDigest")) ("task" (field x "task")))))
         (selection (poo-flow-temporal-support-claim guard (field x "claim") (field x "expectedContextBinding")))
         (claim (.ref selection 'claim)))
    (hash (schema "poo-flow.temporal-support-claim-result.v1") (abiVersion 1)
      (claim (hash (identity (.ref claim 'identity)) (status (symbol->string (.ref claim 'status)))
              (activeSupports (.ref claim 'active-support-identities))))
      (status (symbol->string (.ref selection 'status)))
      (contextStatus (symbol->string (.ref selection 'context-status)))
      (bindingDigest (.ref selection 'binding-digest))
      (policyStatus (symbol->string (.ref guard 'policy-status))) (guard (wire-guard guard))
      (trustBasis "declared-journal-cut-and-host-policy")
      (proofAdmitted #f) (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f))))
