;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Read-only inert v1 projection into the original POO support/evidence owners.
(import (only-in :clan/poo/object .ref)
        :poo-flow/modules/temporal-causality/truth-maintenance/support/interface
        :poo-flow/modules/temporal-causality/revisions/interface
        :poo-flow/modules/temporal-causality/time/objects)
(export temporal-support-call temporal-support-input temporal-support-result temporal-support-journal-input temporal-support-revise-call)
(def (field x key)
  (unless (and (hash-table? x) (hash-key? x key)) (error "missing support field" key))
  (hash-ref x key))
(def (fields x names)
  (unless (and (hash-table? x) (= (hash-length x) (length names)))
    (error "unexpected support fields"))
  (for-each (lambda (key) (field x key)) names))
(def (bounded-list x limit)
  (unless (and (list? x) (<= (length x) limit)) (error "support inventory bound")) x)
(def (instant domain position)
  (unless (and (integer? position) (exact? position)) (error "support clock coordinate"))
  (poo-flow-temporal-instant (number->string position) domain position "abi-caller" 'observed))
(def (temporal-support-input x)
  (fields x ["schema" "program" "journal" "asOf" "validAt" "budget"])
  (unless (equal? (field x "schema") "poo-flow.temporal-support-request.v1")
    (error "unsupported support schema"))
  (let* ((p (field x "program")) (j (field x "journal")))
    (fields p (if (hash-key? p "conclusions")
                ["identity" "policy" "complete" "conclusions" "supports"]
                ["identity" "policy" "complete" "supports"]))
    (fields j ["identity" "admissionDomain" "validDomain" "revisions"])
    (let* ((supports (map (lambda (s)
             (fields s ["identity" "conclusion" "proof" "premises" "parents"])
             (poo-flow-temporal-support (field s "identity") (field s "conclusion") (field s "proof")
               (map (lambda (v) (fields v ["subject" "revision"])
                      (poo-flow-temporal-support-premise (field v "subject") (field v "revision")))
                    (bounded-list (field s "premises") 128))
               (bounded-list (field s "parents") 128))) (bounded-list (field p "supports") 128)))
           (program (if (hash-key? p "conclusions")
                      (poo-flow-temporal-support-inventory (field p "identity") (field p "policy")
                        (field p "complete") (bounded-list (field p "conclusions") 128) supports)
                      (poo-flow-temporal-support-program (field p "identity") (field p "policy")
                        (field p "complete") supports)))
           (journal (temporal-support-journal-input j))
           (valid (field x "validAt"))
           (as-of (instant (field j "admissionDomain") (field x "asOf")))
           (valid-at (and valid (instant (field j "validDomain") valid))))
      (list program journal as-of valid-at (field x "budget")))))
(def (temporal-support-journal-input j)
  (fields j ["identity" "admissionDomain" "validDomain" "revisions"])
  (let* ((revisions (map (lambda (r)
             (fields r ["identity" "subject" "operation" "predecessor" "admitted" "validRange" "content"])
             (let* ((operation (field r "operation"))
                    (op (cond ((equal? operation "assert") 'assert) ((equal? operation "correct") 'correct)
                              ((equal? operation "retract") 'retract) (else (error "invalid support revision operation"))))
                    (range (field r "validRange"))
                    (interval (and range (begin
                      (unless (and (list? range) (= (length range) 2)) (error "invalid support validity range"))
                      (poo-flow-temporal-interval (field r "identity")
                        (instant (field j "validDomain") (car range))
                        (instant (field j "validDomain") (cadr range)) #t #f)))))
               (poo-flow-temporal-evidence-revision (field r "identity") (field r "subject") op
                 (field r "predecessor") (instant (field j "admissionDomain") (field r "admitted"))
                 interval (field r "content")))) (bounded-list (field j "revisions") 128))))
    (poo-flow-temporal-evidence-journal (field j "identity") (field j "admissionDomain") revisions)))
(def (temporal-support-call x)
  (temporal-support-result (apply poo-flow-temporal-support-evaluate (temporal-support-input x))))
(def (temporal-support-result result)
      (hash (schema "poo-flow.temporal-support-result.v1") (abiVersion 1)
            (programDigest (.ref result 'program-digest)) (bindingDigest (.ref result 'semantic-digest))
            (cutDigest (.ref result 'cut-digest)) (projectionDigest (.ref result 'projection-digest))
            (evaluatedSupports (.ref result 'evaluated-support-count)) (budgetExhausted (.ref result 'budget-exhausted?))
            (conclusions (map (lambda (r) (hash (identity (.ref r 'identity))
                         (status (symbol->string (.ref r 'status)))
                         (activeSupports (.ref r 'active-support-identities)))) (.ref result 'conclusions)))
            (proofAdmitted #f) (sourceAuthenticated #f) (actionAuthorized #f) (durable #f)))

(def (temporal-support-revise-call x)
  (fields x ["schema" "task" "previousAsOf"])
  (unless (equal? (field x "schema") "poo-flow.temporal-support-revision-request.v1")
    (error "unsupported support revision schema"))
  (let* ((task (field x "task")) (inputs (temporal-support-input task))
         (previous (instant (field (field task "journal") "admissionDomain") (field x "previousAsOf")))
         (plan (poo-flow-temporal-support-reverse-plan (car inputs) (cadr inputs)
                 previous (caddr inputs) (list-ref inputs 3))))
    (hash (schema "poo-flow.temporal-support-revision-result.v1") (abiVersion 1)
      (indexDigest (.ref plan 'index-digest))
      (changedSubjects (.ref plan 'changed-subject-identities))
      (affectedConclusions (.ref plan 'affected-conclusion-identities))
      (inventoryComplete (.ref plan 'inventory-complete?))
      (previous (temporal-support-result (poo-flow-temporal-support-evaluate
                  (car inputs) (cadr inputs) previous (list-ref inputs 3) (list-ref inputs 4))))
      (current (temporal-support-result (apply poo-flow-temporal-support-evaluate inputs)))
      (proofAdmitted #f) (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f))))
