;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Trusted owner projection; recompute original native proof, never read proof flags.
(import (only-in :clan/poo/object .ref)
        (only-in :gerbil-ascent/candidate/reasoning reasoning-source-snapshot reasoning-attempt reasoning-receipt-proof)
        (only-in :gerbil-ascent/candidate/provenance positive-proof-nodes positive-proof-roots
                 proof-node-id proof-node-row proof-node-relation)
        :poo-flow/modules/temporal-causality/evaluator/interface
        (only-in :poo-flow/src/ffi/temporal-support temporal-support-journal-input))
(export temporal-derivation-admit)
(def (field x k)
  (unless (and (hash-table? x) (hash-key? x k)) (error "missing derivation field" k)) (hash-ref x k))
(def (fields x ks)
  (unless (and (hash-table? x) (= (hash-length x) (length ks))) (error "unexpected derivation fields"))
  (for-each (lambda (k) (field x k)) ks))
(def (bounded x n)
  (unless (and (list? x) (<= 1 (length x) n)) (error "derivation inventory bound")) x)
(def (unique! xs)
  (let (seen (make-hash-table)) (for-each (lambda (x)
    (when (hash-key? seen x) (error "duplicate derivation identity")) (hash-put! seen x #t)) xs)))
(def (term t)
  (case (string->symbol (field t "kind"))
    ((variable) (fields t ["kind" "name"]) (poo-flow-temporal-rule-variable (field t "name")))
    ((literal) (fields t ["kind" "value"]) (poo-flow-temporal-rule-literal (field t "value")))
    (else (error "unsupported derivation term"))))
(def (atom a)
  (fields a ["relationId" "terms"])
  (poo-flow-temporal-rule-atom (field a "relationId") (map term (bounded (field a "terms") 32))))
(def (program p)
  (fields p ["schema" "identity" "catalogDigest" "generation" "ascentGeneration" "relations" "rules"])
  (unless (equal? (field p "schema") "poo-flow.mrr-rule-program.v1") (error "unsupported rule projection schema"))
  (poo-flow-temporal-rule-program (field p "identity") (field p "catalogDigest") (field p "generation") (field p "ascentGeneration")
    (map (lambda (r) (fields r ["identity" "predicate" "columns"])
           (poo-flow-temporal-rule-relation (field r "identity") (field r "predicate")
             (map string->symbol (bounded (field r "columns") 32)))) (bounded (field p "relations") 32))
    (map (lambda (r) (fields r ["identity" "head" "body"])
           (poo-flow-temporal-rule (field r "identity") (atom (field r "head"))
             (map atom (bounded (field r "body") 32)))) (bounded (field p "rules") 32))))
(def (fact f)
  (fields f ["schema" "identity" "generation" "relationId" "evaluatorRelation" "row"])
  (unless (equal? (field f "schema") "poo-flow.mrr-fact-request.v1") (error "unsupported fact projection schema"))
  (poo-flow-temporal-mrr-fact-content (field f "identity") (field f "generation") (field f "relationId")
    (field f "evaluatorRelation") (bounded (field f "row") 32)))
(def (temporal-derivation-admit request)
  (fields request ["schema" "projection" "journal" "sourceBindings" "workSteps" "maximumNodes"])
  (unless (equal? (field request "schema") "poo-flow.temporal-derivation-admit-request.v1") (error "unsupported derivation admit schema"))
  (let* ((data (field request "projection")) (steps (field request "workSteps")) (max-nodes (field request "maximumNodes")))
    (fields data ["schema" "identity" "program" "rootFact" "facts" "derivations"])
    (unless (and (equal? (field data "schema") "poo-flow.mrr-derivation-projection.v1")
                 (exact-integer? steps) (<= 1 steps 4096) (exact-integer? max-nodes) (<= 1 max-nodes 128))
      (error "invalid derivation proof bounds"))
    (let* ((owned-program (program (field data "program")))
           (original-facts (bounded (field data "facts") 128))
           (facts (map (lambda (row)
             (fields row ["content" "contentDigest" "source"])
             (unless (boolean? (field row "source")) (error "invalid fact source marker"))
             (let (f (fact (field row "content")))
               (unless (and (equal? (.ref f 'semantic-digest) (field row "contentDigest"))
                            (equal? (.ref f 'generation) (.ref owned-program 'generation)))
                 (error "fact digest or generation mismatch")) f)) original-facts))
           (get-fact (lambda (id)
             (or (find (lambda (f) (equal? (.ref f 'identity) id)) facts) (error "unknown original fact"))))
           (derivations (map (lambda (d)
             (fields d ["identity" "rule" "generation" "output" "supports"])
             (poo-flow-temporal-mrr-derivation (field d "identity") (field d "rule") (field d "generation")
               (get-fact (field d "output")) (bounded (field d "supports") 128))) (bounded (field data "derivations") 128)))
           (source-facts (filter (lambda (x) x) (map (lambda (f row) (and (field row "source") f)) facts original-facts)))
           (output (get-fact (field data "rootFact")))
           (journal (temporal-support-journal-input (field request "journal"))))
      (for-each (lambda (f)
        (let (r (find (lambda (r) (equal? (.ref r 'identity) (.ref f 'relation-identity))) (.ref owned-program 'relations)))
          (unless (and r (equal? (.ref r 'predicate) (.ref f 'evaluator-relation))
                       (= (length (.ref r 'columns)) (length (.ref f 'row)))
                       (andmap (lambda (v t) (if (eq? t 'boolean) (boolean? v) (exact-integer? v))) (.ref f 'row) (.ref r 'columns)))
            (error "fact catalog row mismatch")))) facts)
      (unique! (map (lambda (f) (.ref f 'identity)) facts))
      (unique! (map (lambda (d) (.ref d 'identity)) derivations))
      (unique! (map (lambda (d) (.ref (.ref d 'output) 'identity)) derivations))
      (unless (pair? source-facts) (error "proof requires source facts"))
      (for-each (lambda (f row)
        (unless (eq? (field row "source") (not (find (lambda (d) (equal? (.ref (.ref d 'output) 'identity) (.ref f 'identity))) derivations)))
          (error "source marker and derivation authority differ"))) facts original-facts)
      (let* ((snapshot (reasoning-source-snapshot (string->symbol (field data "identity")) (.ref owned-program 'ascent-generation)
                 (filter-map (lambda (r)
                   (let (rows (map (lambda (f) (.ref f 'row))
                         (filter (lambda (f) (equal? (.ref f 'relation-identity) (.ref r 'identity))) source-facts)))
                     (and (pair? rows) (list (string->symbol (.ref r 'predicate)) (length (.ref r 'columns)) rows)))) (.ref owned-program 'relations))))
             (candidate (poo-flow-temporal-rule-program-ascent-query owned-program snapshot output))
             (receipt (reasoning-attempt snapshot candidate steps))
             (admission (poo-flow-temporal-positive-proof-from-ascent (field data "identity") snapshot candidate receipt steps max-nodes))
             (nodes (positive-proof-nodes (reasoning-receipt-proof receipt)))
             (node-bindings (map (lambda (f)
               (let* ((matches (filter (lambda (n) (and (equal? (proof-node-row n) (.ref f 'row))
                         (equal? (symbol->string (proof-node-relation n)) (.ref f 'evaluator-relation)))) nodes))
                      (d (find (lambda (d) (equal? (.ref (.ref d 'output) 'identity) (.ref f 'identity))) derivations)))
                 (unless (= (length matches) 1) (error "ambiguous or absent proof fact correspondence"))
                 (poo-flow-temporal-proof-node-fact (proof-node-id (car matches)) f d))) facts))
             (source-inputs (bounded (field request "sourceBindings") 128))
             (source-bindings (map (lambda (b)
               (fields b ["fact" "subject" "revision"])
               (let* ((f (get-fact (field b "fact")))
                      (node (find (lambda (n) (equal? (.ref (.ref n 'fact) 'identity) (.ref f 'identity))) node-bindings)))
                 (unless (member f source-facts) (error "binding is not an original source"))
                 (poo-flow-temporal-proof-source-binding (.ref node 'node) f (field b "subject") (field b "revision")))) source-inputs))
             (roots (positive-proof-roots (reasoning-receipt-proof receipt)))
             (root-d (find (lambda (d) (equal? (.ref (.ref d 'output) 'identity) (.ref output 'identity))) derivations)))
        (unless (and root-d (= (length roots) 1)) (error "selected original derived root required"))
        (let* ((bound (poo-flow-temporal-proof-support (.ref root-d 'identity) admission snapshot candidate receipt steps max-nodes
                        (car roots) output source-bindings journal))
               (correspondence (poo-flow-temporal-rule-correspondence-from-ascent owned-program admission snapshot candidate receipt steps max-nodes))
               (joint (poo-flow-temporal-mrr-derivation-from-ascent (field data "identity") owned-program correspondence bound admission
                        snapshot candidate receipt steps max-nodes node-bindings output source-bindings journal))
               (support (.ref joint 'support)))
          (hash (schema "poo-flow.temporal-derivation-admit-result.v1") (abiVersion 1)
                (bindingDigest (.ref joint 'semantic-digest)) (proofDigest (.ref admission 'proof-digest))
                (catalogDigest (.ref owned-program 'catalog-digest)) (generation (.ref owned-program 'generation))
                (derivationIdentity (.ref joint 'derivation-identity)) (ruleIdentity (.ref joint 'rule-identity))
                (nodeBindings (.ref joint 'node-bindings))
                (support (hash (identity (.ref support 'identity)) (conclusion (.ref support 'conclusion-identity))
                     (proof (.ref support 'proof-identity)) (parents [])
                     (premises (map (lambda (p) (hash (subject (.ref p 'subject-identity)) (revision (.ref p 'revision-identity)))) (.ref support 'premises)))))
                (proofAdmitted (.ref admission 'proof-admitted?))
                (derivationCorrespondenceVerified (.ref joint 'derivation-correspondence-verified?))
                (mrrRuleEquivalenceVerified (.ref joint 'mrr-rule-equivalence-verified?))
                (trustBasis "host-declared-source-relative-native-proof")
                (sourceAuthenticated #f) (selectionAdmitted #f) (actionAuthorized #f) (durable #f)))))))
