;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Finite logical-step behaviors under declared mechanisms and persistent
;;; intervention clamps. Idle is always permitted; no fairness is invented.
(import (only-in :clan/poo/object .o .ref)
        (only-in :std/list/list every any find take foldl delete-duplicates/hash)
        (only-in :std/crypto/digest sha256)
        (only-in :std/encoding/hex hex-encode)
        "types.ss" "objects.ss")
(export poo-flow-temporal-behavior-model poo-flow-temporal-behavior-model-replay
        poo-flow-temporal-behavior-explore poo-flow-temporal-behavior-replay
        poo-flow-temporal-behavior-step-table poo-flow-temporal-behavior-step-table-replay)
(def (digest value)
  (string-append "sha256:" (hex-encode (sha256 (string->utf8 (object->string value))))))
(def (unique? xs) (= (length xs) (length (delete-duplicates/hash xs))))
(def (by-id values)
  (list-sort (lambda (a b) (string<? (.ref a 'identity) (.ref b 'identity))) values))
(def (pairs values)
  (map (lambda (v) (list (.ref v 'identity) (.ref v 'variable) (.ref v 'value))) (by-id values)))
(def (poo-flow-temporal-behavior-model id variables mechanisms interventions horizon)
  (unless (and (list? variables) (pair? variables) (every poo-flow-temporal-state-variable? variables)
               (list? mechanisms) (every poo-flow-temporal-mechanism? mechanisms)
               (list? interventions) (every poo-flow-temporal-intervention? interventions)
               (exact-integer? horizon) (>= horizon 0))
    (error "invalid finite temporal behavior inventory"))
  (for-each (lambda (xs)
              (unless (unique? (map (lambda (v) (.ref v 'identity)) xs))
                (error "duplicate temporal behavior identity")))
            (list variables mechanisms interventions))
  (when (find (lambda (m) (equal? (.ref m 'identity) "idle")) mechanisms)
    (error "idle is the reserved environment stutter identity"))
  (def (check-bindings assignments unique-writes?)
    (unless (unique? (map (lambda (a) (.ref a 'identity)) assignments))
      (error "duplicate temporal condition/assignment identity"))
    (when (and unique-writes? (not (unique? (map (lambda (a) (.ref a 'variable)) assignments))))
      (error "conflicting temporal assignments"))
    (for-each
     (lambda (assignment)
       (let (variable (find (lambda (v) (equal? (.ref v 'identity) (.ref assignment 'variable))) variables))
         (unless (and variable (member (.ref assignment 'value) (.ref variable 'domain)))
           (error "temporal assignment/condition is outside its declared domain")))) assignments))
  (for-each (lambda (v) (unless (unique? (.ref v 'domain)) (error "duplicate state domain value"))) variables)
  (for-each (lambda (m) (check-bindings (.ref m 'guards) #f)
               (check-bindings (.ref m 'assignments) #t)) mechanisms)
  (for-each
   (lambda (i)
     (check-bindings (.ref i 'assignments) #t)
     (unless (<= (.ref i 'onset) horizon) (error "intervention onset is beyond declared horizon"))
     (for-each
      (lambda (protected)
        (unless (find (lambda (v) (equal? (.ref v 'identity) protected)) variables)
          (error "unknown protected variable" protected))
        (when (find (lambda (a) (equal? (.ref a 'variable) protected)) (.ref i 'assignments))
          (error "intervention directly edits a protected variable" protected))) (.ref i 'protected-variables))
     (for-each
      (lambda (other)
        (when (and (not (eq? i other)) (= (.ref i 'onset) (.ref other 'onset))
                   (any (lambda (a) (find (lambda (b) (equal? (.ref a 'variable) (.ref b 'variable)))
                                         (.ref other 'assignments))) (.ref i 'assignments)))
          (error "ambiguous simultaneous intervention clamps"))) interventions)) interventions)
  (let* ((variables (by-id variables)) (mechanisms (by-id mechanisms))
         (interventions (list-sort
                         (lambda (a b) (or (< (.ref a 'onset) (.ref b 'onset))
                                           (and (= (.ref a 'onset) (.ref b 'onset))
                                                (string<? (.ref a 'identity) (.ref b 'identity))))) interventions))
         (row (list 'poo-flow.temporal.behavior.v1 id horizon
                    (map (lambda (v) (list (.ref v 'identity) (list-sort string<? (.ref v 'domain)) (.ref v 'initial))) variables)
                    (map (lambda (m) (list (.ref m 'identity) (pairs (.ref m 'guards))
                                          (pairs (.ref m 'assignments)) (.ref m 'assumption))) mechanisms)
                    (map (lambda (i) (list (.ref i 'identity) (.ref i 'onset) (pairs (.ref i 'assignments))
                                          (list-sort string<? (.ref i 'protected-variables)) (.ref i 'assumption))) interventions))))
    (poo-flow-temporal-behavior-model-value id variables mechanisms interventions horizon (digest row))))
(def (poo-flow-temporal-behavior-model-replay model)
  (unless (poo-flow-temporal-behavior-model? model) (error "invalid temporal behavior model"))
  (let (expected (poo-flow-temporal-behavior-model (.ref model 'identity) (.ref model 'variables)
                   (.ref model 'mechanisms) (.ref model 'interventions) (.ref model 'horizon)))
    (unless (equal? (.ref expected 'semantic-digest) (.ref model 'semantic-digest))
      (error "temporal behavior model digest mismatch")) expected))
(def (holds? conditions state)
  (every (lambda (c) (let (value (find (lambda (a) (equal? (.ref a 'variable) (.ref c 'variable))) state))
                       (and value (equal? (.ref value 'value) (.ref c 'value))))) conditions))
(def (assign state assignments)
  (map (lambda (old) (or (find (lambda (new) (equal? (.ref old 'variable) (.ref new 'variable))) assignments) old)) state))
(def (clamp model state step)
  (foldl (lambda (i s) (if (<= (.ref i 'onset) step) (assign s (.ref i 'assignments)) s))
         state (.ref model 'interventions)))
(def (trace model schedule)
  (let* ((schedule-value schedule)
         (state (map (lambda (v) (poo-flow-temporal-assignment
                                  (.ref v 'identity) (.ref v 'identity) (.ref v 'initial))) (.ref model 'variables)))
         (initial (clamp model state 0)))
    (let loop ((actions schedule) (step 0) (state initial) (history (list initial)))
      (if (null? actions)
        (.o kind: 'temporal/behavior-trace identity: (digest (list (.ref model 'semantic-digest) schedule))
            schedule: schedule-value
            states: (map (lambda (values) (.o kind: 'temporal/behavior-state assignments: values)) (reverse history)))
        (let* ((m (find (lambda (m) (equal? (.ref m 'identity) (car actions))) (.ref model 'mechanisms)))
               (updated (if (and m (holds? (.ref m 'guards) state)) (assign state (.ref m 'assignments)) state))
               (next (clamp model updated (+ step 1))))
          (loop (cdr actions) (+ step 1) next (cons next history)))))))
(def (satisfies? property trace)
  (let* ((states (.ref trace 'states)) (deadline (.ref property 'deadline))
         (prefix (take states (+ deadline 1)))
         (condition (lambda (s) (holds? (.ref property 'conditions) (.ref s 'assignments)))))
    (case (.ref property 'question) ((safety) (every condition prefix)) (else (any condition prefix)))))
(def (poo-flow-temporal-behavior-explore model query)
  (let* ((model (poo-flow-temporal-behavior-model-replay model))
         (property (and (poo-flow-temporal-behavior-query? query) (.ref query 'property))))
    (unless property (error "invalid temporal behavior query"))
    (when (> (.ref property 'deadline) (.ref model 'horizon))
      (error "temporal property deadline exceeds declared behavior horizon"))
    (for-each
     (lambda (c)
       (let (v (find (lambda (v) (equal? (.ref v 'identity) (.ref c 'variable))) (.ref model 'variables)))
         (unless (and v (member (.ref c 'value) (.ref v 'domain))) (error "property condition outside state domain"))))
     (.ref property 'conditions))
    (let ((actions (cons "idle" (map (lambda (m) (.ref m 'identity)) (.ref model 'mechanisms))))
          (horizon (.ref model 'horizon)) (limit (.ref query 'world-limit))
          (node-limit (.ref query 'node-limit)))
      (let loop ((frontier (list '())) (count 0) (witness #f) (counterexample #f) (nodes 0))
        (cond
         ((or (null? frontier) (and limit (>= count limit)) (and node-limit (>= nodes node-limit)))
          (let* ((exhausted (null? frontier))
                 (classification (cond ((and exhausted witness (not counterexample)) 'necessary)
                                       (witness 'possible) (exhausted 'refuted) (else 'unknown))))
            (poo-flow-temporal-behavior-receipt-value
             (digest (list (.ref model 'semantic-digest) (.ref query 'identity)
                           (.ref property 'identity) (.ref property 'question)
                           (pairs (.ref property 'conditions)) (.ref property 'deadline)
                           limit node-limit count classification))
             (.ref model 'semantic-digest) property query classification count exhausted witness counterexample
             (map reverse frontier))))
         ((< (length (car frontier)) horizon)
          (loop (append (map (lambda (action) (cons action (car frontier))) actions) (cdr frontier))
                count witness counterexample (+ nodes 1)))
         (else
          (let* ((world (trace model (reverse (car frontier)))) (satisfied (satisfies? property world)))
            (loop (cdr frontier) (+ count 1) (or witness (and satisfied world))
                  (or counterexample (and (not satisfied) world)) (+ nodes 1)))))))))
(def (poo-flow-temporal-behavior-replay receipt model)
  (unless (poo-flow-temporal-behavior-receipt? receipt) (error "invalid temporal behavior receipt"))
  (let (expected (poo-flow-temporal-behavior-explore model (.ref receipt 'query)))
    (unless (every (lambda (slot) (equal? (.ref expected slot) (.ref receipt slot)))
                   '(identity model-digest classification explored-worlds exhausted? frontier))
      (error "temporal behavior receipt differs from its model/query"))
    (let ((a (.ref expected 'property)) (b (.ref receipt 'property)))
      (unless (and (poo-flow-temporal-property? b)
                   (equal? (.ref a 'identity) (.ref b 'identity))
                   (equal? (.ref a 'question) (.ref b 'question))
                   (equal? (.ref a 'deadline) (.ref b 'deadline))
                   (equal? (pairs (.ref a 'conditions)) (pairs (.ref b 'conditions))))
        (error "temporal behavior receipt property differs from its query")))
    ;; Compare trace content explicitly: POO object identity is not structural equality.
    (for-each
     (lambda (slot)
       (let ((a (.ref expected slot)) (b (.ref receipt slot)))
         (unless (if a (and b (equal? (.ref a 'identity) (.ref b 'identity))
                            (equal? (.ref a 'schedule) (.ref b 'schedule))
                            (equal? (map (lambda (s) (pairs (.ref s 'assignments))) (.ref a 'states))
                                    (map (lambda (s) (pairs (.ref s 'assignments))) (.ref b 'states)))) (not b))
           (error "temporal behavior witness differs from replay")))) '(witness counterexample)) expected))

;;; Every row comes from the same native trace evaluator used by exploration.
;;; Deduplicate states by logical tick + values, not POO allocation identity.
(def (state-values state)
  (map (lambda (a) (.ref a 'value)) (.ref state 'assignments)))
(def (table-row step-row)
  (list (.ref step-row 'coordinate) (state-values (.ref step-row 'before))
        (.ref step-row 'action) (state-values (.ref step-row 'after))))
(def (poo-flow-temporal-behavior-step-table model node-limit: (limit 10000))
  (let* ((model (poo-flow-temporal-behavior-model-replay model))
         (actions (cons "idle" (map (lambda (m) (.ref m 'identity)) (.ref model 'mechanisms))))
         (initial (car (.ref (trace model '()) 'states)))
         (horizon (.ref model 'horizon)))
    (unless (and (exact-integer? limit) (> limit 0)) (error "invalid transition-table node budget"))
    (let loop ((queue (list '())) (seen (list (list 0 (state-values initial)))) (edges '()) (nodes 0))
      (if (or (null? queue) (>= nodes limit))
        (let* ((complete (null? queue)) (ordered (reverse edges))
               (rows (map table-row ordered))
               (sha (digest (list 'poo-flow.temporal.behavior.steps.v1 (.ref model 'semantic-digest)
                                  limit complete nodes rows queue))))
          (.o kind: 'temporal/behavior-step-table identity: sha model-digest: (.ref model 'semantic-digest)
              variable-order: (map (lambda (v) (.ref v 'identity)) (.ref model 'variables))
              initial-values: (state-values initial) steps: ordered explored-nodes: nodes
              exhausted?: complete node-limit: limit frontier: queue action-authorized?: #f))
        (let* ((path (car queue)) (tick (length path))
               (prior-state (list-ref (.ref (trace model path) 'states) tick)))
          (if (= tick horizon)
            (loop (cdr queue) seen edges (+ nodes 1))
            (let (expanded
                  (foldl
                   (lambda (actor acc)
                     (let* ((next-path (append path (list actor)))
                            (next-state (list-ref (.ref (trace model next-path) 'states) (+ tick 1)))
                            (key (list (+ tick 1) (state-values next-state)))
                            (visited (cadr acc))
                            (edge (.o kind: 'temporal/behavior-step coordinate: tick action: actor
                                      before: prior-state after: next-state)))
                       (list (if (member key visited) (car acc) (append (car acc) (list next-path)))
                             (if (member key visited) visited (cons key visited))
                             (cons edge (caddr acc)))))
                   (list (cdr queue) seen edges) actions))
              (loop (car expanded) (cadr expanded) (caddr expanded) (+ nodes 1)))))))))
(def (poo-flow-temporal-behavior-step-table-replay table model)
  (let (expected (poo-flow-temporal-behavior-step-table model node-limit: (.ref table 'node-limit)))
    (unless (and (eq? (.ref table 'kind) 'temporal/behavior-step-table)
                 (every (lambda (slot) (equal? (.ref expected slot) (.ref table slot)))
                        '(identity model-digest variable-order initial-values explored-nodes exhausted? node-limit frontier action-authorized?))
                 (equal? (map table-row (.ref expected 'steps)) (map table-row (.ref table 'steps))))
      (error "transition table differs from native evaluator replay")) expected))
