;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref .slot? object?)
        (only-in :clan/poo/mop define-type Type. element?)
        (only-in :std/list/list every))
(export PooFlowTemporalStateVariable PooFlowTemporalCondition PooFlowTemporalAssignment
        PooFlowTemporalMechanism PooFlowTemporalIntervention PooFlowTemporalBehaviorModel
        PooFlowTemporalProperty PooFlowTemporalBehaviorQuery PooFlowTemporalBehaviorReceipt
        poo-flow-temporal-state-variable? poo-flow-temporal-condition?
        poo-flow-temporal-assignment? poo-flow-temporal-mechanism?
        poo-flow-temporal-intervention? poo-flow-temporal-behavior-model?
        poo-flow-temporal-property? poo-flow-temporal-behavior-query?
        poo-flow-temporal-behavior-receipt?)
(def (text? v) (and (string? v) (> (string-length v) 0)))
(def (shape? v kind slots)
  (and (object? v) (.slot? v 'kind) (eq? (.ref v 'kind) kind)
       (.slot? v 'identity) (text? (.ref v 'identity))
       (every (lambda (slot) (.slot? v slot)) slots)))
(def (variable? v)
  (and (shape? v 'temporal/state-variable '(domain initial))
       (list? (.ref v 'domain)) (pair? (.ref v 'domain))
       (every text? (.ref v 'domain)) (member (.ref v 'initial) (.ref v 'domain))))
(def (condition? v)
  (and (shape? v 'temporal/condition '(variable value))
       (text? (.ref v 'variable)) (text? (.ref v 'value))))
(def (assignment? v)
  (and (shape? v 'temporal/assignment '(variable value))
       (text? (.ref v 'variable)) (text? (.ref v 'value))))
(def (mechanism? v)
  (and (shape? v 'temporal/mechanism '(guards assignments assumption))
       (text? (.ref v 'assumption))
       (list? (.ref v 'guards)) (every condition? (.ref v 'guards))
       (list? (.ref v 'assignments)) (pair? (.ref v 'assignments))
       (every assignment? (.ref v 'assignments))))
(def (intervention? v)
  (and (shape? v 'temporal/intervention '(onset assignments protected-variables assumption))
       (exact-integer? (.ref v 'onset)) (>= (.ref v 'onset) 0)
       (list? (.ref v 'assignments)) (pair? (.ref v 'assignments))
       (every assignment? (.ref v 'assignments))
       (list? (.ref v 'protected-variables)) (every text? (.ref v 'protected-variables))
       (text? (.ref v 'assumption))))
(def (model? v)
  (and (shape? v 'temporal/behavior-model '(variables mechanisms interventions horizon semantic-digest))
       (list? (.ref v 'variables)) (pair? (.ref v 'variables)) (every variable? (.ref v 'variables))
       (list? (.ref v 'mechanisms)) (every mechanism? (.ref v 'mechanisms))
       (list? (.ref v 'interventions)) (every intervention? (.ref v 'interventions))
       (exact-integer? (.ref v 'horizon)) (>= (.ref v 'horizon) 0)
       (text? (.ref v 'semantic-digest))))
(def (property? v)
  (and (shape? v 'temporal/property '(question conditions deadline))
       (memq (.ref v 'question) '(safety reachability bounded-progress))
       (list? (.ref v 'conditions)) (pair? (.ref v 'conditions))
       (every condition? (.ref v 'conditions))
       (exact-integer? (.ref v 'deadline)) (>= (.ref v 'deadline) 0)))
(def (query? v)
  (and (shape? v 'temporal/behavior-query '(property world-limit node-limit))
       (property? (.ref v 'property))
       (every (lambda (n) (or (not n) (and (exact-integer? n) (> n 0))))
              (list (.ref v 'world-limit) (.ref v 'node-limit)))))
(def (receipt? v)
  (and (shape? v 'temporal/behavior-receipt
               '(model-digest property query classification explored-worlds exhausted?
                              witness counterexample frontier fairness actual-causation?))
       (memq (.ref v 'classification) '(possible necessary refuted unknown))
       (boolean? (.ref v 'exhausted?))
       (eq? (.ref v 'fairness) 'none)
       (eq? (.ref v 'actual-causation?) #f)))
(define-type (PooFlowTemporalStateVariable @ Type.) .element?: variable?)
(define-type (PooFlowTemporalCondition @ Type.) .element?: condition?)
(define-type (PooFlowTemporalAssignment @ Type.) .element?: assignment?)
(define-type (PooFlowTemporalMechanism @ Type.) .element?: mechanism?)
(define-type (PooFlowTemporalIntervention @ Type.) .element?: intervention?)
(define-type (PooFlowTemporalBehaviorModel @ Type.) .element?: model?)
(define-type (PooFlowTemporalProperty @ Type.) .element?: property?)
(define-type (PooFlowTemporalBehaviorQuery @ Type.) .element?: query?)
(define-type (PooFlowTemporalBehaviorReceipt @ Type.) .element?: receipt?)
(def (poo-flow-temporal-state-variable? v) (element? PooFlowTemporalStateVariable v))
(def (poo-flow-temporal-condition? v) (element? PooFlowTemporalCondition v))
(def (poo-flow-temporal-assignment? v) (element? PooFlowTemporalAssignment v))
(def (poo-flow-temporal-mechanism? v) (element? PooFlowTemporalMechanism v))
(def (poo-flow-temporal-intervention? v) (element? PooFlowTemporalIntervention v))
(def (poo-flow-temporal-behavior-model? v) (element? PooFlowTemporalBehaviorModel v))
(def (poo-flow-temporal-property? v) (element? PooFlowTemporalProperty v))
(def (poo-flow-temporal-behavior-query? v) (element? PooFlowTemporalBehaviorQuery v))
(def (poo-flow-temporal-behavior-receipt? v) (element? PooFlowTemporalBehaviorReceipt v))
