;;; -*- Gerbil -*-
;;; Boundary: stable facade for memory-core POO objects.

(import :poo-flow/src/modules/memory-core/objects-core
        :poo-flow/src/modules/memory-core/objects-handoff
        :poo-flow/src/modules/memory-core/objects-catalog
        :poo-flow/src/modules/memory-core/objects-validation
        :poo-flow/src/modules/memory-core/objects-durable
        :poo-flow/src/modules/memory-core/objects-builtin)

(export +poo-flow-memory-core-store-spec-kind+
        +poo-flow-memory-core-catalog-kind+
        +poo-flow-memory-core-handoff-manifest-kind+
        +poo-flow-memory-core-policy-validation-receipt-kind+
        +poo-flow-memory-core-durable-job-receipt-kind+
        +poo-flow-memory-durable-job-kinds+
        +poo-flow-memory-durable-job-states+
        poo-flow-memory-store-spec
        poo-flow-memory-store-spec?
        poo-flow-memory-store-spec-ref
        poo-flow-memory-store-spec-scopes
        poo-flow-memory-store-spec-commit-policies
        poo-flow-memory-store-spec-recall-policies
        poo-flow-memory-store-spec->alist
        poo-flow-memory-handoff-manifest
        poo-flow-memory-handoff-manifest?
        poo-flow-memory-handoff-manifest->alist
        poo-flow-memory-catalog
        poo-flow-memory-catalog?
        poo-flow-memory-catalog-ref
        poo-flow-memory-catalog-store-refs
        poo-flow-memory-catalog-store-count
        poo-flow-memory-catalog-find
        poo-flow-memory-catalog->alist
        poo-flow-memory-policy-catalog-validation-receipt
        poo-flow-memory-policy-catalog-validation-receipt?
        poo-flow-memory-policy-catalog-validation-receipt-valid?
        poo-flow-memory-policy-catalog-validation-receipt-diagnostics
        poo-flow-memory-policy-catalog-validation-receipt->alist
        make-poo-flow-memory-durable-job-receipt
        poo-flow-memory-durable-job-receipt?
        poo-flow-memory-durable-job-receipt-job-id
        poo-flow-memory-durable-job-receipt-job-kind
        poo-flow-memory-durable-job-receipt-job-state
        poo-flow-memory-durable-job-receipt-project-id
        poo-flow-memory-durable-job-receipt-root-session-id
        poo-flow-memory-durable-job-receipt-session-id
        poo-flow-memory-durable-job-receipt-agent-id
        poo-flow-memory-durable-job-receipt-store-ref
        poo-flow-memory-durable-job-receipt-durable-policy-ref
        poo-flow-memory-durable-job-receipt-job-store-ref
        poo-flow-memory-durable-job-receipt-checkpoint-store-ref
        poo-flow-memory-durable-job-receipt-source-ref
        poo-flow-memory-durable-job-receipt-source-watermark
        poo-flow-memory-durable-job-receipt-target-watermark
        poo-flow-memory-durable-job-receipt-stale-source?
        poo-flow-memory-durable-job-receipt-retry-policy
        poo-flow-memory-durable-job-receipt-retention-policy
        poo-flow-memory-durable-job-receipt-usage-counter
        poo-flow-memory-durable-job-receipt-scope
        poo-flow-memory-durable-job-receipt-recall
        poo-flow-memory-durable-job-receipt-commit-policy
        poo-flow-memory-durable-job-receipt-valid?
        poo-flow-memory-durable-job-receipt-diagnostics
        poo-flow-memory-durable-job-receipt-metadata
        poo-flow-memory-durable-job-receipt-from-intent
        poo-flow-memory-durable-job-receipt->alist
        poo-flow-memory-durable-job-receipts->alists
        poo-flow-memory-recall-job-receipt
        poo-flow-memory-write-job-receipt
        poo-flow-memory-consolidation-job-receipt
        poo-flow-memory-stale-source-job-receipt
        poo-flow-memory-repair-job-receipt
        poo-flow-memory-core-local-session-store
        poo-flow-memory-core-durable-project-store
        poo-flow-memory-core-default-catalog)
