;;; -*- Gerbil -*-
;;; Runtime proof that every admitted module resolves to the fresh AOT library.
(import (only-in :gerbil/runtime load-module)
        (only-in :gerbil/gambit path-normalize)
        (only-in :std/crypto/digest sha256)
        (only-in :std/text/hex hex-encode)
        (only-in :std/sort sort)
        (only-in :std/srfi/13 string-prefix? string-suffix?))
(export verify-poo-clos-artifacts! poo-clos-dependency-snapshot
        verify-poo-clos-dependencies!)

(def (poo-clos-dependency-snapshot)
  (apply append
    (map (lambda (module)
           (let* ((main (path-normalize (load-module module)))
                  (directory (path-directory main))
                  (stem (path-strip-extension (path-strip-directory main)))
                  (units (filter (lambda (name)
                                   (and (string-prefix? (string-append stem "~") name)
                                        (string-suffix? ".o1" name)))
                                 (directory-files directory))))
             (map (lambda (path)
                    (list path (call-with-input-file path
                                 (lambda (port) (hex-encode (sha256 port))))))
                  (cons main (map (lambda (unit) (path-expand unit directory))
                                  (sort units string<?))))))
         '("clan/base" "clan/poo/proto" "clan/poo/object" "clan/poo/type"
           "clan/poo/mop" "std/test"))))

(def (verify-poo-clos-dependencies! before)
  (unless (equal? before (poo-clos-dependency-snapshot))
    (error "Dependency artifact drift during POO CLOS qualification"))
  (call-with-output-file (getenv "POO_CLOS_AOT_DEPENDENCIES")
    (lambda (port)
      (write (list 'runtime-dependency-fingerprints '(algorithm sha256)
                   '(purpose content-integrity) (cons 'artifacts before)) port)
      (newline port))))

(def (verify-poo-clos-artifacts!)
  (let ((library (getenv "POO_CLOS_AOT_LIB"))
        (manifest (getenv "POO_CLOS_AOT_MODULES")))
    (call-with-input-file manifest
      (lambda (port)
        (let loop ((count 0))
          (let (module (read-line port))
            (if (eof-object? module)
              (begin (when (zero? count) (error "Empty AOT artifact manifest")) count)
              (let ((expected (path-normalize (string-append library "/" module ".o1")))
                    (actual (path-normalize (load-module module))))
                (unless (equal? actual expected)
                  (error "AOT module resolved outside POO CLOS qualification" module actual expected))
                (write (list 'compiled-module module actual))
                (newline)
                (force-output)
                (loop (+ count 1))))))))))
