;;; -*- Gerbil -*-
;;; Test-owned runtime verification, not merely the presence of .o1 files.
(import (only-in :gerbil/runtime load-module)
        (only-in :gerbil/gambit path-normalize)
        (only-in :std/crypto/digest sha256)
        (only-in :std/text/hex hex-encode)
        (only-in :std/sort sort)
        (only-in :std/srfi/13 string-prefix? string-suffix?))
(export verify-combination-artifacts! combination-dependency-snapshot verify-combination-dependencies!)
(def (combination-dependency-snapshot)
  (apply append
    (map (lambda (module)
           (let* ((main (path-normalize (load-module module)))
                  (directory (path-directory main))
                  (stem (path-strip-extension (path-strip-directory main)))
                  (units (filter (lambda (name)
                                   (and (string-prefix? (string-append stem "~") name)
                                        (string-suffix? ".o1" name))) (directory-files directory))))
             (map (lambda (path)
                    (list path (call-with-input-file path (lambda (port) (hex-encode (sha256 port))))))
                  (cons main (map (lambda (unit) (path-expand unit directory)) (sort units string<?))))))
         '("clan/base" "clan/poo/proto" "clan/poo/object" "clan/poo/type" "clan/poo/mop"
           "clan/poo/debug" "std/test"))))
(def (verify-combination-dependencies! before)
  (unless (equal? before (combination-dependency-snapshot))
    (error "Dependency artifact drift during qualification"))
  (call-with-output-file (getenv "POO_COMBINATION_AOT_DEPENDENCIES")
    (lambda (port)
      (write (list 'runtime-dependency-fingerprints '(algorithm sha256)
                   '(purpose content-integrity) (cons 'artifacts before)) port)
      (newline port))))
(def (verify-combination-artifacts!)
  (let ((library (getenv "POO_COMBINATION_AOT_LIB"))
        (manifest (getenv "POO_COMBINATION_AOT_MODULES")))
    (call-with-input-file manifest
      (lambda (port)
        (let loop ((count 0))
          (let (module (read-line port))
            (if (eof-object? module)
              (begin (when (zero? count) (error "Empty AOT artifact manifest")) count)
              (let ((expected (path-normalize (string-append library "/" module ".o1")))
                    (actual (path-normalize (load-module module))))
                (unless (equal? actual expected)
                  (error "AOT module resolved outside qualification artifacts" module actual expected))
                (write (list 'compiled-module module actual)) (newline)
                (loop (+ count 1))))))))))
