;;; -*- Gerbil -*-
;;; Test-owned read-only projection: trial receipts -> bounded statistical summary.
(import (only-in :clan/poo/object .o .ref)
        (only-in :std/sort sort)
        (only-in :std/srfi/1 delete-duplicates)
        (only-in :std/srfi/13 string-prefix?))
(export main combination-performance-summaries)
(def (wire-field fields key)
  (let (field (assq key fields))
    (unless (and field (= (length field) 2)) (error "Missing/malformed trial field" key))
    (cadr field)))
(def (read-trials path)
  (call-with-input-file path
    (lambda (port)
      (let loop ((rows '()))
        (let (line (read-line port))
          (cond ((eof-object? line) (reverse rows))
                ((string-prefix? "(performance-trial " line)
                 (loop (cons (cdr (call-with-input-string line read)) rows)))
                (else (loop rows))))))))
(def (trial-key row)
  (map (lambda (key) (wire-field row key)) '(depth from qualifiers)))
(def (metric row owner name)
  (let (fields (assq owner row))
    (unless fields (error "Missing performance owner" owner))
    (let (value (wire-field (cdr fields) name))
      (unless (and (real? value) (>= value 0)) (error "Invalid performance metric" name value))
      value)))
(def (distribution values)
  (when (null? values) (error "Empty performance distribution"))
  (let* ((ordered (sort values <)) (count-value (length ordered))
         (middle (quotient count-value 2))
         (median-value (if (odd? count-value) (list-ref ordered middle)
                          (/ (+ (list-ref ordered (- middle 1)) (list-ref ordered middle)) 2))))
    (.o count: count-value min: (car ordered) median: median-value max: (car (reverse ordered)))))
(def (summary rows)
  (let* ((head (car rows)) (key-value (trial-key head))
         (iterations-value (wire-field head 'iterations))
         (trial-values (map (lambda (row) (wire-field row 'trial)) rows))
         (combination-value (distribution (map (lambda (row) (metric row 'combination 'wall-ms)) rows)))
         (functional-value (distribution (map (lambda (row) (metric row 'functional 'wall-ms)) rows)))
         (gc-value (distribution (map (lambda (row) (metric row 'combination 'gc-ms)) rows)))
         (allocation-value (distribution (map (lambda (row) (metric row 'combination 'allocated-bytes)) rows))))
    (unless (and (>= (length rows) 2)
                 (= (length trial-values) (length (delete-duplicates trial-values)))
                 (andmap (lambda (row)
                           (and (= iterations-value (wire-field row 'iterations))
                                (wire-field row 'plan-reused?)
                                (= (wire-field row 'expected) (metric row 'combination 'checksum))
                                (= (wire-field row 'expected) (metric row 'functional 'checksum)))) rows))
      (error "Incomplete or inconsistent performance trials" key-value))
    (.o kind: 'poo-combination/performance-summary schema: 'v1 producer: 'poo-flow/modules/poo-method-combination
        key: key-value iterations: iterations-value trials: (length rows)
        combination-ms: combination-value functional-ms: functional-value
        combination-gc-ms: gc-value combination-allocated-bytes: allocation-value
        median-ratio: (and (> (.ref functional-value 'median) 0)
                           (/ (.ref combination-value 'median) (.ref functional-value 'median))))))
(def (combination-performance-summaries path)
  (let loop ((remaining (read-trials path)) (summaries '()))
    (if (null? remaining)
      (if (null? summaries) (error "No performance trials in receipt" path) (reverse summaries))
      (let* ((key (trial-key (car remaining)))
             (matches? (lambda (row) (equal? (trial-key row) key))))
        (loop (filter (lambda (row) (not (matches? row))) remaining)
              (cons (summary (filter matches? remaining)) summaries))))))
(def (main . args)
  (unless (= (length args) 1) (error "Expected one qualification.sexp path"))
  (for-each
   (lambda (value)
     (write
       (append (map (lambda (key) (list key (.ref value key))) '(kind schema producer key iterations trials median-ratio))
               (map (lambda (key)
                      (cons key (map (lambda (field) (list field (.ref (.ref value key) field)))
                                     '(min median max))))
                    '(combination-ms functional-ms combination-gc-ms combination-allocated-bytes))))
     (newline))
   (combination-performance-summaries (car args))))
