;;; Explicit verification boundary. The configured operation is host-trusted;
;;; submitted POO facts and their claimed verification flags are not.
(import (only-in :clan/poo/object .o .ref .slot? object?)
        (only-in :std/srfi/1 find filter))
(export poo-flow-verification-adapter poo-flow-verify poo-flow-verification-valid?
        poo-flow-revoke-verification!)
(def (instant? value) (and (exact-integer? value) (>= value 0)))
(def (text? value) (and (string? value) (> (string-length value) 0)))
(def (poo-flow-verification-adapter identity-value operation snapshot)
  (unless (and (text? identity-value) (procedure? operation) (procedure? snapshot))
    (error "verification adapter requires an identity, operation and snapshot function"))
  ;; Private issuance and revocation state is confined to this explicit boundary.
  ;; A snapshot string is copied: mutable input strings must not mutate seals.
  (let ((issued '()) (sequence 0))
    (def (freeze value)
      (let (result (snapshot value))
        (unless (string? result) (error "verification snapshot must be a string"))
        (string-copy result)))
    (def (verify-value value now until)
      (unless (and (instant? now) (instant? until) (< now until))
        (error "invalid verification validity interval"))
      (let (before (freeze value))
        (if (eq? (operation value now until) #t)
          (begin
            (unless (equal? before (freeze value))
              (error "verification input changed during verification"))
            (set! sequence (+ sequence 1))
            (let* ((id (string-append identity-value "/" (number->string sequence)))
                   (receipt (.o identity: id issuer: identity-value issued-at: now expires-at: until)))
              ;; Receipt identity and validity are read from private storage,
              ;; never from an editable presentation slot on the returned object.
              (set! issued (cons (list receipt before now until (string-copy id) (string-copy identity-value)) issued))
              receipt))
          #f)))
    (def (valid? receipt value now)
      (and (instant? now)
           (let (entry (find (lambda (e) (eq? (car e) receipt)) issued))
             (and entry (<= (list-ref entry 2) now) (< now (list-ref entry 3))
                  (object? receipt)
                  (.slot? receipt 'identity) (.slot? receipt 'issuer)
                  (.slot? receipt 'issued-at) (.slot? receipt 'expires-at)
                  (equal? (.ref receipt 'identity) (list-ref entry 4))
                  (equal? (.ref receipt 'issuer) (list-ref entry 5))
                  (equal? (.ref receipt 'issued-at) (list-ref entry 2))
                  (equal? (.ref receipt 'expires-at) (list-ref entry 3))
                  (equal? (freeze value) (cadr entry)) #t))))
    (def (revoke-value! receipt)
      (set! issued (filter (lambda (e) (not (eq? (car e) receipt))) issued)))
    (.o identity: identity-value verify: verify-value admits?: valid? revoke!: revoke-value!)))
(def (poo-flow-verify adapter value now until)
  ((.ref adapter 'verify) value now until))
(def (poo-flow-verification-valid? adapter receipt value now)
  ((.ref adapter 'admits?) receipt value now))
(def (poo-flow-revoke-verification! adapter receipt)
  ((.ref adapter 'revoke!) receipt))
