#ifndef POO_FLOW_RUNTIME_V0_CONTRACT_H
#define POO_FLOW_RUNTIME_V0_CONTRACT_H

#include <stdint.h>

#define POO_FLOW_RUNTIME_V0_ABI_MAJOR 0u
#define POO_FLOW_RUNTIME_V0_ABI_MINOR 3u
#define POO_FLOW_RUNTIME_V0_BUNDLE_SCHEMA "poo-flow.organization-bundle.draft.3"
#define POO_FLOW_RUNTIME_V0_CONTROL_PACKET_SCHEMA "poo-flow.runtime-v0.control-packet.1"
#define POO_FLOW_RUNTIME_LANGUAGE_PROMOTION_REQUEST_SCHEMA "poo-flow.runtime-language.promotion-request.1"
#define POO_FLOW_RUNTIME_LANGUAGE_PROMOTION_RECEIPT_SCHEMA "poo-flow.runtime-language.promotion-receipt.1"
#define POO_FLOW_RUNTIME_LANGUAGE_PROMOTION_IDEMPOTENCY_KEY_SCHEMA "poo-flow.runtime-language.promotion-idempotency-key.1"
#define POO_FLOW_RUNTIME_LANGUAGE_SOURCE_QUERY_RECEIPT_SCHEMA "poo-flow.runtime-language.source-query-receipt.1"
#define POO_FLOW_RUNTIME_LANGUAGE_ADMISSION_RECEIPT_SCHEMA "poo-flow.runtime-language.admission-receipt.1"
#define POO_FLOW_CONTRACT_ARTIFACT_PROJECTION_RECEIPT_SCHEMA "poo-flow.contract.artifact-projection-receipt.1"
#define POO_FLOW_RUNTIME_V0_LAYOUT_VERSION 1u
#define POO_FLOW_RUNTIME_V0_EVENT_HEADER_BYTES 96u
#define POO_FLOW_RUNTIME_V0_COMPACT_IDENTITY_BITS 128u
#define POO_FLOW_RUNTIME_V0_CAP_CONTROL (UINT64_C(1) << 0)
#define POO_FLOW_RUNTIME_V0_CAP_CHECKPOINT (UINT64_C(1) << 1)
#define POO_FLOW_RUNTIME_V0_CAP_HOT_BATCH (UINT64_C(1) << 2)
#define POO_FLOW_RUNTIME_V0_CAP_BULK_BUFFER (UINT64_C(1) << 3)
#define POO_FLOW_RUNTIME_V0_CAP_CALLER_ARENA (UINT64_C(1) << 4)
#define POO_FLOW_RUNTIME_V0_CAP_PARTIAL_ACCEPTANCE (UINT64_C(1) << 5)
#define POO_FLOW_RUNTIME_V0_CAP_BATCHED_EVIDENCE (UINT64_C(1) << 6)
#define POO_FLOW_RUNTIME_V0_CAP_PROMOTION_MATERIALIZE (UINT64_C(1) << 7)
#define POO_FLOW_RUNTIME_V0_CAP_INJECTION_RECEIPT (UINT64_C(1) << 8)
#define POO_FLOW_RUNTIME_V0_CAP_ROLLBACK (UINT64_C(1) << 9)
#define POO_FLOW_RUNTIME_V0_CAP_EXACTLY_ONCE (UINT64_C(1) << 10)
#define POO_FLOW_RUNTIME_V0_CAP_LANGUAGE_QUALIFICATION (UINT64_C(1) << 11)
#define POO_FLOW_RUNTIME_V0_CAP_SOURCE_QUERY_DATA (UINT64_C(1) << 12)
#define POO_FLOW_RUNTIME_V0_CAP_CONTRACT_ADMISSION_RECEIPT (UINT64_C(1) << 13)
#define POO_FLOW_RUNTIME_V0_CAP_CONTRACT_ARTIFACT_PROJECTION (UINT64_C(1) << 14)

#endif
